-- GENERATED by scripts/gen_taxonomy_seed.py — do not hand-edit.
-- Regenerate against a newer snapshot and diff; zero diff means the taxonomy has not moved.
--
-- ⭐ EVERY 'kind of thing' here is a ROW, never a Postgres ENUM and never a Go constant
-- (DECISIONS.md, 2026-09-12), so adding a class or a currency later is an INSERT.
--
-- ⚠️ EVERY SEED IS `ON CONFLICT DO NOTHING`, not "insert if not exists": the latter is two
-- statements with a race between them. A duplicated taxonomy row is a filter that offers the
-- same option twice, noticed months later by a reader rather than by us. Pinned by
-- TestEverySeedInsertIsIdempotent (AOC-005).

-- +goose Up

-- the 4 archetypes. Tier A, Pierre 2026-09-17 — no item record names one.
CREATE TABLE archetypes (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 6, measured. sort_order is explicit: see the UNCONFIRMED note in the generator.
CREATE TABLE rarities (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE,
    sort_order integer      NOT NULL
);

-- 5, measured. Ordered lightest to heaviest.
CREATE TABLE armour_weights (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE,
    sort_order integer      NOT NULL
);

-- 30, measured. (The AOC-009 plan said 32 — stale.)
CREATE TABLE item_types (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 13 ATOMIC slots. The data's 15 values include 2 compound ones; see the generator.
CREATE TABLE equip_locations (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 24, measured from acquisition_cost. (The plan said 26 — stale.)
CREATE TABLE currencies (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 3, measured.
CREATE TABLE acquisition_types (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 10, measured. PvE 3.5 sorts between 3 and 4, which is why sort_order exists.
CREATE TABLE tiers (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE,
    sort_order integer      NOT NULL
);

-- 3, measured — AOC-016's cleanup is in the data (it was 19).
CREATE TABLE bindings (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- 14, measured and de-typo'd; see FACTION_TYPOS in the generator.
CREATE TABLE factions (
    id         serial PRIMARY KEY,
    slug       varchar(64)  NOT NULL UNIQUE,
    name       varchar(64)  NOT NULL UNIQUE
);

-- classes carry their archetype. max_armour_weight is the CEILING a class may wear, which is
-- a DIFFERENT fact from an item's own armour_weight and must never be populated from it
-- (DECISIONS.md, 2026-09-12). It is Pierre-sourced, not armory-derivable, and unknown for all
-- twelve — so it is nullable and stays NULL. An empty field is a feature; a guess is a bug.
CREATE TABLE classes (
    id                serial PRIMARY KEY,
    archetype_id      integer     NOT NULL REFERENCES archetypes(id),
    slug              varchar(64) NOT NULL UNIQUE,
    name              varchar(64) NOT NULL UNIQUE,
    max_armour_weight integer     NULL REFERENCES armour_weights(id)
);

-- 4 rows
INSERT INTO archetypes (slug, name) VALUES
    ('soldier', 'Soldier'),
    ('priest', 'Priest'),
    ('rogue', 'Rogue'),
    ('mage', 'Mage')
ON CONFLICT (slug) DO NOTHING;

-- 6 rows
INSERT INTO rarities (slug, name, sort_order) VALUES
    ('mundane', 'Mundane', 10),
    ('enchanted', 'Enchanted', 20),
    ('superior', 'Superior', 30),
    ('rare', 'Rare', 40),
    ('epic', 'Epic', 50),
    ('legendary', 'Legendary', 60)
ON CONFLICT (slug) DO NOTHING;

-- 5 rows
INSERT INTO armour_weights (slug, name, sort_order) VALUES
    ('cloth', 'Cloth', 10),
    ('light', 'Light', 20),
    ('medium', 'Medium', 30),
    ('heavy', 'Heavy', 40),
    ('full-plate', 'Full Plate', 50)
ON CONFLICT (slug) DO NOTHING;

-- 30 rows
INSERT INTO item_types (slug, name) VALUES
    ('1hb', '1HB'),
    ('1he', '1HE'),
    ('2hb', '2HB'),
    ('2he', '2HE'),
    ('ammunition', 'Ammunition'),
    ('back', 'Back'),
    ('backpack', 'Backpack'),
    ('belt', 'Belt'),
    ('bow', 'Bow'),
    ('chest', 'Chest'),
    ('consumable', 'Consumable'),
    ('crossbow', 'Crossbow'),
    ('dagger', 'Dagger'),
    ('feet', 'Feet'),
    ('generic', 'Generic'),
    ('hands', 'Hands'),
    ('head', 'Head'),
    ('legs', 'Legs'),
    ('mount', 'Mount'),
    ('necklace', 'Necklace'),
    ('pet', 'Pet'),
    ('polearm', 'Polearm'),
    ('potion', 'Potion'),
    ('ring', 'Ring'),
    ('shield', 'Shield'),
    ('shoulder', 'Shoulder'),
    ('staff', 'Staff'),
    ('talisman', 'Talisman'),
    ('thrown', 'Thrown'),
    ('wrist', 'Wrist')
ON CONFLICT (slug) DO NOTHING;

-- 13 rows
INSERT INTO equip_locations (slug, name) VALUES
    ('head', 'Head'),
    ('shoulder', 'Shoulder'),
    ('chest', 'Chest'),
    ('wrist', 'Wrist'),
    ('hands', 'Hands'),
    ('belt', 'Belt'),
    ('legs', 'Legs'),
    ('feet', 'Feet'),
    ('cloak', 'Cloak'),
    ('main-hand', 'Main Hand'),
    ('off-hand', 'Off Hand'),
    ('left-finger', 'Left Finger'),
    ('right-finger', 'Right Finger')
ON CONFLICT (slug) DO NOTHING;

-- 24 rows
INSERT INTO currencies (slug, name) VALUES
    ('atlantean-shards', 'Atlantean Shards'),
    ('campaign-badges', 'Campaign Badges'),
    ('conquest-trophies', 'Conquest Trophies'),
    ('copper', 'Copper'),
    ('dragon-tear', 'Dragon Tear'),
    ('emerald-essence', 'Emerald Essence'),
    ('gilding-token', 'Gilding Token'),
    ('gold', 'Gold'),
    ('mark-of-acclaim', 'Mark of Acclaim'),
    ('mythical-relic', 'Mythical Relic'),
    ('rare-relic', 'Rare Relic'),
    ('rare-trophy', 'Rare Trophy'),
    ('shard-of-pure-ice', 'Shard of Pure Ice'),
    ('silver', 'Silver'),
    ('simple-relic-i', 'Simple Relic I'),
    ('simple-relic-ii', 'Simple Relic II'),
    ('simple-relic-iii', 'Simple Relic III'),
    ('simple-relic-iv', 'Simple Relic IV'),
    ('simple-relic-v', 'Simple Relic V'),
    ('simple-relic-vi', 'Simple Relic VI'),
    ('simple-trophy-i', 'Simple Trophy I'),
    ('simple-trophy-ii', 'Simple Trophy II'),
    ('simple-trophy-iii', 'Simple Trophy III'),
    ('tin', 'Tin')
ON CONFLICT (slug) DO NOTHING;

-- 3 rows
INSERT INTO acquisition_types (slug, name) VALUES
    ('drop', 'drop'),
    ('quest', 'quest'),
    ('vendor', 'vendor')
ON CONFLICT (slug) DO NOTHING;

-- 10 rows
INSERT INTO tiers (slug, name, sort_order) VALUES
    ('pve-1', 'PvE 1', 10),
    ('pve-2', 'PvE 2', 20),
    ('pve-3', 'PvE 3', 30),
    ('pve-35', 'PvE 3.5', 35),
    ('pve-4', 'PvE 4', 40),
    ('pve-5', 'PvE 5', 50),
    ('pve-6', 'PvE 6', 60),
    ('pvp-1', 'PvP 1', 110),
    ('pvp-2', 'PvP 2', 120),
    ('pvp-3', 'PvP 3', 130)
ON CONFLICT (slug) DO NOTHING;

-- 3 rows
INSERT INTO bindings (slug, name) VALUES
    ('binds-when-equipped', 'Binds when Equipped'),
    ('binds-when-picked-up', 'Binds when Picked Up'),
    ('character-bound', 'Character Bound')
ON CONFLICT (slug) DO NOTHING;

-- 14 rows
INSERT INTO factions (slug, name) VALUES
    ('brittle-blade', 'Brittle Blade'),
    ('children-of-yag-kosha', 'Children of Yag-kosha'),
    ('clan-vigdis', 'Clan Vigdis'),
    ('hyrkanians', 'Hyrkanians'),
    ('jiang-shi', 'Jiang Shi'),
    ('last-legion', 'Last Legion'),
    ('pit-master-s-arena-gladiators', 'Pit Master''s Arena (Gladiators)'),
    ('pit-master-s-arena-pit-fighters', 'Pit Master''s Arena (Pit Fighters)'),
    ('scarlet-circle', 'Scarlet Circle'),
    ('scholars-of-cheng-ho', 'Scholars of Cheng-ho'),
    ('shadows-of-jade', 'Shadows of Jade'),
    ('tamarin-s-tigers', 'Tamarin''s Tigers'),
    ('wolves-of-the-steppes', 'Wolves of the Steppes'),
    ('yellow-priests-of-yun', 'Yellow Priests of Yun')
ON CONFLICT (slug) DO NOTHING;

-- 12 classes, each resolved to its archetype by slug rather than by a hardcoded id
INSERT INTO classes (archetype_id, slug, name) VALUES
    ((SELECT id FROM archetypes WHERE slug = 'soldier'), 'conqueror', 'Conqueror'),
    ((SELECT id FROM archetypes WHERE slug = 'soldier'), 'dark-templar', 'Dark Templar'),
    ((SELECT id FROM archetypes WHERE slug = 'soldier'), 'guardian', 'Guardian'),
    ((SELECT id FROM archetypes WHERE slug = 'priest'), 'bear-shaman', 'Bear Shaman'),
    ((SELECT id FROM archetypes WHERE slug = 'priest'), 'priest-of-mitra', 'Priest of Mitra'),
    ((SELECT id FROM archetypes WHERE slug = 'priest'), 'tempest-of-set', 'Tempest of Set'),
    ((SELECT id FROM archetypes WHERE slug = 'rogue'), 'assassin', 'Assassin'),
    ((SELECT id FROM archetypes WHERE slug = 'rogue'), 'barbarian', 'Barbarian'),
    ((SELECT id FROM archetypes WHERE slug = 'rogue'), 'ranger', 'Ranger'),
    ((SELECT id FROM archetypes WHERE slug = 'mage'), 'demonologist', 'Demonologist'),
    ((SELECT id FROM archetypes WHERE slug = 'mage'), 'herald-of-xotli', 'Herald of Xotli'),
    ((SELECT id FROM archetypes WHERE slug = 'mage'), 'necromancer', 'Necromancer')
ON CONFLICT (slug) DO NOTHING;

-- +goose Down
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS factions;
DROP TABLE IF EXISTS bindings;
DROP TABLE IF EXISTS tiers;
DROP TABLE IF EXISTS acquisition_types;
DROP TABLE IF EXISTS currencies;
DROP TABLE IF EXISTS equip_locations;
DROP TABLE IF EXISTS item_types;
DROP TABLE IF EXISTS armour_weights;
DROP TABLE IF EXISTS rarities;
DROP TABLE IF EXISTS archetypes;
