-- GENERATED by scripts/gen_places_seed.py — do not hand-edit.
-- Regenerate against a newer snapshot and diff; zero diff means the places have not moved.
--
-- ⭐ PLACES ARE ENTITIES WITH PAGES, NOT STRINGS ON AN ITEM (DECISIONS.md, 2026-09-13), and
-- they are a HIERARCHY: region -> map -> place -> place. Some instances contain instances
-- (House of Crom, Warmonk Monastery) and some hang straight off a region with no map at all
-- (Skull Gate Pass, Kuthchemes) — which is why parent_place_id exists and map_id is NULL-able.
--
-- ⭐ AN UNCHAINED DUNGEON IS ITS OWN ROW, not a flag on its twin: seven places exist in both
-- forms and ZERO items are shared between any pair (Pierre, 2026-09-13). The boolean is kept
-- as a cheap filter — 'show me every Unchained dungeon' — but the PLACE is the truth.
--
-- ⚠️ EVERY ROW CARRIES ITS PROVENANCE: source_note says which of the two sources it came
-- from, confidence follows reference/sourcing-standards.md § 3, and open_question holds what
-- is still unknown. `WHERE open_question IS NOT NULL` is the list of things to ask Pierre.
-- An empty field is a feature; a confident guess is a bug that reaches a raid.
--
-- ⚠️ EVERY SEED IS `ON CONFLICT DO NOTHING` (AOC-005's convention, pinned by
-- TestEverySeedInsertIsIdempotent).

-- +goose Up

-- The confidence vocabulary of reference/sourcing-standards.md § 3, as rows rather than an
-- ENUM, because a fifth value must be an INSERT and not a migration of every content table.
CREATE TABLE confidence_levels (
    id         serial PRIMARY KEY,
    slug       varchar(64) NOT NULL UNIQUE,
    name       varchar(64) NOT NULL UNIQUE,
    sort_order integer     NOT NULL
);

-- 8 regions. Pierre confirmed the list is COMPLETE (Tier A, 2026-09-13); the
-- armory knows only 6 of them and would silently lose Tortage and Kush.
CREATE TABLE regions (
    id            serial PRIMARY KEY,
    slug          varchar(64)  NOT NULL UNIQUE,
    name          varchar(64)  NOT NULL UNIQUE,
    sort_order    integer      NOT NULL,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);

-- 26 maps — the playfield an instance's entrance sits in.
-- region_id is NULL-able on purpose: a map the armory knows and Pierre's tree does not may
-- arrive before anyone can say which region it belongs to.
CREATE TABLE maps (
    id            serial PRIMARY KEY,
    region_id     integer      NULL REFERENCES regions(id),
    slug          varchar(64)  NOT NULL UNIQUE,
    name          varchar(96)  NOT NULL UNIQUE,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);

-- 86 places: the dungeons, raids and arenas you zone into.
--
-- ⚠️ map_id is NULL-able and region_id is NOT — not the other way round. Skull Gate Pass and
-- Kuthchemes are entered from the Raid Finder and have no map between them and their region,
-- so a NOT NULL map_id would have no value to put there but a made-up one.
--
-- ⚠️ region_id is carried even when map_id is set. It is redundant by design: 'every place in
-- Stygia' is then one join rather than a COALESCE over two paths, and the generator is the
-- only writer, so the two cannot drift. Pinned by TestEveryPlacesRegionMatchesItsMap.
--
-- armory_instance / armory_dungeon are the source spellings this place was filed under, kept
-- so AOC-011 can join 6,641 item source rows onto these rows without re-deriving the mapping
-- from scratch. They are the alias record too: 'The Pit Master's Arena' is how the armory
-- spells Fight Club Arena.
CREATE TABLE places (
    id              serial PRIMARY KEY,
    region_id       integer      NOT NULL REFERENCES regions(id),
    map_id          integer      NULL REFERENCES maps(id),
    parent_place_id integer      NULL REFERENCES places(id),
    slug            varchar(96)  NOT NULL UNIQUE,
    name            varchar(96)  NOT NULL UNIQUE,
    unchained       boolean      NOT NULL DEFAULT false,
    armory_instance varchar(96)  NULL,
    armory_dungeon  varchar(96)  NULL,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);

-- The importer's join key. Partial, because the places Pierre knows and the armory never
-- filed an item under share (NULL, NULL) and must not collide with each other.
CREATE UNIQUE INDEX places_armory_key ON places (armory_instance, armory_dungeon)
    NULLS NOT DISTINCT
    WHERE armory_instance IS NOT NULL OR armory_dungeon IS NOT NULL;
CREATE INDEX places_region_id_idx ON places (region_id);
CREATE INDEX places_map_id_idx ON places (map_id);
CREATE INDEX places_parent_place_id_idx ON places (parent_place_id);

-- 44 bosses. place_id is NULL-able: five of them were confirmed by Pierre as
-- bosses the armory had filed as places, and they keep their map and region but have no
-- instance recorded. EP-03 hangs the mechanics — the actual product — off these rows.
CREATE TABLE bosses (
    id            serial PRIMARY KEY,
    place_id      integer      NULL REFERENCES places(id),
    map_id        integer      NULL REFERENCES maps(id),
    region_id     integer      NULL REFERENCES regions(id),
    slug          varchar(96)  NOT NULL UNIQUE,
    name          varchar(96)  NOT NULL UNIQUE,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);
CREATE INDEX bosses_place_id_idx ON bosses (place_id);

-- 51 quests — and `name` is NULL for every one of them, on purpose.
-- The armory's quest column holds the quest GIVER ('Muriela'), a hub ('Conall's Valley') or
-- a bucket ('Destiny quests') as often as a quest title, so armory_label records exactly what
-- the source said and `name` waits for someone who knows. An empty field is a feature.
CREATE TABLE quests (
    id            serial PRIMARY KEY,
    region_id     integer      NULL REFERENCES regions(id),
    map_id        integer      NULL REFERENCES maps(id),
    slug          varchar(96)  NOT NULL UNIQUE,
    armory_label  varchar(96)  NOT NULL UNIQUE,
    name          varchar(96)  NULL,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);

-- 2 containers. ⚠️ NOT places, which is the whole reason they have their own
-- table: they have no region and no map, and the dungeons that drop them span several.
CREATE TABLE containers (
    id            serial PRIMARY KEY,
    slug          varchar(96)  NOT NULL UNIQUE,
    name          varchar(96)  NOT NULL UNIQUE,
    confidence_id integer       NOT NULL REFERENCES confidence_levels(id),
    source_note   varchar(300) NOT NULL,
    open_question varchar(300) NULL
);

-- 4 rows
INSERT INTO confidence_levels (slug, name, sort_order) VALUES
    ('verified', 'Verified', 10),
    ('corroborated', 'Corroborated', 20),
    ('unconfirmed', 'Unconfirmed', 30),
    ('disputed', 'Disputed', 40)
ON CONFLICT (slug) DO NOTHING;

-- 8 rows
INSERT INTO regions (slug, name, sort_order, confidence_id, source_note, open_question) VALUES
    ('tortage', 'Tortage', 10, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('cimmeria', 'Cimmeria', 20, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('aquilonia', 'Aquilonia', 30, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('stygia', 'Stygia', 40, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('turan', 'Turan', 50, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('khitai', 'Khitai', 60, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('kush', 'Kush', 70, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL),
    ('hyperborea', 'Hyperborea', 80, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — the region list is complete', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 26 rows
INSERT INTO maps (region_id, slug, name, confidence_id, source_note, open_question) VALUES
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'atzel-s-approach', 'Atzel''s Approach', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), 'chosain-province', 'Chosain Province', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'tortage'), 'city-of-tortage', 'City of Tortage', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), 'coast-of-ardashir', 'Coast of Ardashir', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'conall-s-valley', 'Conall''s Valley', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'conarch-village', 'Conarch Village', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), 'dragon-s-spine', 'Dragon''s Spine', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'eiglophian-mountains', 'Eiglophian Mountains', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'field-of-the-dead', 'Field of the Dead', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), 'gateway-to-khitai', 'Gateway to Khitai', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), 'kara-korum', 'Kara Korum', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), 'khemi', 'Khemi', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 76 source rows filed under this map (Tier A*)', 'present in the armory as a map, absent from Pierre''s geography — confirm it is a map and not an instance'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), 'kheshatta', 'Kheshatta', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), 'khopshef-province', 'Khopshef Province', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'king-conan-s-castle', 'King Conan''s Castle', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 17 source rows filed under this map (Tier A*)', 'present in the armory as a map, absent from Pierre''s geography — confirm it is a map and not an instance'),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'lacheish-plains', 'Lacheish Plains', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), 'northern-grasslands', 'Northern Grasslands', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'old-tarantia', 'Old Tarantia', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), 'paikang', 'Paikang', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'poitain', 'Poitain', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), 'purple-lotus-swamp', 'Purple Lotus Swamp', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'tarantia-common-district', 'Tarantia Common District', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'tarantia-noble-district', 'Tarantia Noble District', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'thunder-river', 'Thunder River', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), 'wild-lands-of-zelata', 'Wild Lands of Zelata', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), 'ymir-s-pass', 'Ymir''s Pass', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 81 rows — every place that is not inside another one
INSERT INTO places (region_id, map_id, parent_place_id, slug, name, unchained, armory_instance, armory_dungeon, confidence_id, source_note, open_question) VALUES
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), NULL, 'abandoned-smugglers-tunnels', 'Abandoned Smugglers Tunnels', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'tortage'), (SELECT id FROM maps WHERE slug = 'city-of-tortage'), NULL, 'acheronian-ruins', 'Acheronian Ruins', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'paikang'), NULL, 'ai-district', 'Ai District', false, 'Ai District', 'Ai District', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 23 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), NULL, 'amphitheatre-of-karutonia', 'Amphitheatre of Karutonia', false, 'Amphitheatre of Karutonia', 'Amphitheatre of Karutonia', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 35 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), NULL, 'amphitheatre-of-karutonia-unchained', 'Amphitheatre of Karutonia (Unchained)', true, 'Amphitheatre of Karutonia', 'Amphitheatre of Karutonia (Unchained)', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'items_clean.json — 22 source rows (Tier A*); located with its non-Unchained twin, Amphitheatre of Karutonia', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'ardashir-arena', 'Ardashir Arena', false, NULL, 'Ardashir Arena', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 48 source rows (Tier A*)', 'armory-only name (48 rows, Turan / Coast of Ardashir). Pierre''s geography knows ''Ardashir Fort'' on the same map. Same place or two?'),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'ardashir-fort', 'Ardashir Fort', false, 'Ardashir Fort', 'Ardashir Fort', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 38 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'armsman-s-arena', 'Armsman''s Arena', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'disputed'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', 'Pierre''s geography lists this as an instance in Tarantia Noble District; the armory files it as a boss inside ''Armsman''s Tavern'''),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'armsman-s-tavern', 'Armsman''s Tavern', false, NULL, 'Armsman''s Tavern', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 12 source rows (Tier A*)', 'armory-only name (12 rows, Aquilonia / Tarantia Noble District). Pierre''s geography knows ''Armsman''s Arena'' on the same map, which the armory files as a BOSS inside this dungeon. Same place or two?'),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-common-district'), NULL, 'attilius-mansion', 'Attilius'' Mansion', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), NULL, 'atzel-s-fortress', 'Atzel''s Fortress', false, 'Atzel''s Fortress', 'Atzel''s Fortress', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 96 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), NULL, 'black-castle', 'Black Castle', false, 'Black Castle', 'Black Castle', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 29 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'black-ring-citadel', 'Black Ring Citadel', false, 'Black Ring Citadel', 'Black Ring Citadel', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 278 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), NULL, 'border-range', 'Border Range', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', 'the armory files 2 source rows with this name in its MAP column; Pierre''s geography calls it an instance'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), NULL, 'bubshur-house', 'Bubshur House', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), NULL, 'cannibal-cave', 'Cannibal Cave', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'caravan-raider-camp', 'Caravan Raider Camp', false, NULL, 'Caravan Raider Camp', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 96 source rows (Tier A*)', 'armory-only name (96 rows, Stygia / Kheshatta). Pierre''s geography knows "Caravan Raider''s Hideout" on the same map. Same place or two?'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'caravan-raider-camp-unchained', 'Caravan Raider Camp (Unchained)', true, NULL, 'Caravan Raider Camp (Unchained)', (SELECT id FROM confidence_levels WHERE slug = 'disputed'), 'items_clean.json — 102 source rows (Tier A*); located with its non-Unchained twin, Caravan Raider Camp', 'sources disagree on where this is: its twin Caravan Raider Camp is in Stygia / Kheshatta, the armory files its 102 rows under Cimmeria / Atzel''s Approach'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'caravan-raider-s-hideout', 'Caravan Raider''s Hideout', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'kara-korum'), NULL, 'caverns-of-malice', 'Caverns of Malice', false, 'Caverns of Malice', 'The Cavern of Malice', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 43 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), NULL, 'coils-of-ubah-kan', 'Coils of Ubah Kan', false, 'Coils of Ubah Kan', 'The Coils of Ubah Kan', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 100 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), NULL, 'cradle-of-decay', 'Cradle of Decay', false, 'Cradle of Decay', 'Cradle of Decay', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 22 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-common-district'), NULL, 'crows-nest', 'Crows'' Nest', false, 'Crows'' Nest', 'Crows'' Nest', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 42 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'dead-man-s-hand', 'Dead Man''s Hand', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'dead-man-s-hand-unchained', 'Dead Man''s Hand (Unchained)', true, 'Dead Man''s Hand', 'Dead Man''s Hand (Unchained)', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'items_clean.json — 9 source rows (Tier A*); located with its non-Unchained twin, Dead Man''s Hand', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'chosain-province'), NULL, 'den-of-the-crowmen', 'Den of the Crowmen', false, 'Den of the Crowmen', 'Den of the Crowmen', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 40 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), NULL, 'fight-club-arena', 'Fight Club Arena', false, NULL, 'The Pit Master''s Arena', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 36 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'lacheish-plains'), NULL, 'frost-swamp', 'Frost Swamp', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), NULL, 'halls-of-eternal-frost', 'Halls of Eternal Frost', false, 'Halls of Eternal Frost', 'Halls of Eternal Frost', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 17 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), NULL, 'halls-of-eternal-frost-unchained', 'Halls of Eternal Frost (Unchained)', true, 'Halls of Eternal Frost', 'Halls of Eternal Frost (Unchained)', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'items_clean.json — 98 source rows (Tier A*); located with its non-Unchained twin, Halls of Eternal Frost', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), NULL, 'house-of-crom', 'House of Crom', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13) — complexes: an instance that contains instances', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'poitain'), NULL, 'imirian-ravine', 'Imirian Ravine', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-common-district'), NULL, 'iron-tower', 'Iron Tower', false, 'Iron Tower', 'The Iron Tower', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 94 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'isle-of-iron-statues', 'Isle of Iron Statues', false, 'Isle of Iron Statues', 'Isle of Iron Statues', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 7 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'paikang'), NULL, 'jade-citadel', 'Jade Citadel', false, 'Jade Citadel', 'Jade Citadel', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 204 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'chosain-province'), NULL, 'jade-dugout', 'Jade Dugout', false, 'Jade Dugout', 'The Jade Dugout', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 41 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), NULL, 'kang-pagoda', 'Kang Pagoda', false, 'Kang Pagoda', 'The Kang Pagoda', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 43 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'kush'), NULL, NULL, 'kuthchemes-temple-onslaught', 'Kuthchemes Temple Onslaught', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', 'Pierre''s geography lists this both as the map ''Kuthchemes'' and as the instance ''Kuthchemes Temple Onslaught''; the armory spells the section differently again. One place or two?'),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), NULL, 'kyllikki-s-crypt', 'Kyllikki''s Crypt', false, 'Kyllikki''s Crypt', 'Kyllikki''s Crypt', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 262 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'purple-lotus-swamp'), NULL, 'oasis-of-zaara', 'Oasis of Zaara', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'onyx-chambers', 'Onyx Chambers', false, 'Onyx Chambers', 'The Onyx Chambers', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 99 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), NULL, 'otherworldly-junction', 'Otherworldly Junction', true, 'Otherworldly Junction', 'Otherworldly Junction', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 177 armory source rows (Tier A*)', 'every one of its 177 armory rows is flagged Unchained, but neither source spells the name that way and it has no non-Unchained twin — is this place Unchained-only?'),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'old-tarantia'), NULL, 'outflow-tunnels', 'Outflow Tunnels', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), NULL, 'palace-of-cetriss', 'Palace of Cetriss', false, 'Palace of Cetriss', 'Palace of Cetriss', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 75 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'chosain-province'), NULL, 'palace-of-yun-rau', 'Palace of Yun Rau', false, 'Palace of Yun Rau', 'Palace of Yun Rau', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 47 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), NULL, 'pillars-of-heaven', 'Pillars of Heaven', false, 'Pillars of Heaven', 'Pillars of Heaven', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 135 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), NULL, 'pyramid-of-the-ancients', 'Pyramid of the Ancients', false, 'Pyramid of the Ancients', 'Pyramid of the Ancients', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 11 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'kara-korum'), NULL, 'refuge-of-the-apostate', 'Refuge of the Apostate', false, 'Refuge of the Apostate', 'Refuge of the Apostate', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 8 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), NULL, 'sanctum-of-the-burning-souls', 'Sanctum of the Burning Souls', false, 'Sanctum of the Burning Souls', 'Sanctum of the Burning Souls', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 49 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'scorpion-cave', 'Scorpion Cave', false, 'Scorpion Cave', 'Scorpion Cave', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 23 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'scorpion-cave-unchained', 'Scorpion Cave (Unchained)', true, 'Scorpion Cave', 'Scorpion Cave (Unchained)', (SELECT id FROM confidence_levels WHERE slug = 'disputed'), 'items_clean.json — 98 source rows (Tier A*); located with its non-Unchained twin, Scorpion Cave', 'sources disagree on where this is: its twin Scorpion Cave is in Stygia / Kheshatta, the armory files its 98 rows under Cimmeria / Atzel''s Approach'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), NULL, 'sepulcher-of-the-wyrm', 'Sepulcher of the Wyrm', false, 'Sepulcher of the Wyrm', 'Sepulcher of the Wyrm', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 46 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'hyperborea'), NULL, NULL, 'skull-gate-pass', 'Skull Gate Pass', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); mapless_instances — entered from the Raid Finder, no map between it and the region', 'the name of the instance INSIDE it is unknown — our data says only ''Wave Boss Random Drop'''),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'conall-s-valley'), NULL, 'spider-caverns', 'Spider Caverns', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'paikang'), NULL, 't-ian-an-district', 'T''ian''an District', false, 'T''ian''an District', 'T''ian''an District', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 44 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), NULL, 'temple-of-erlik', 'Temple of Erlik', false, 'Temple of Erlik', 'Temple of Erlik', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 151 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'chosain-province'), NULL, 'the-abyss-of-kun-whu', 'The Abyss of Kun Whu', false, 'The Abyss of Kun Whu', 'Abyss of Kun Whu', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 46 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'gateway-to-khitai'), NULL, 'the-breach', 'The Breach', false, 'The Breach', 'The Breach', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 13 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'the-catacombs', 'The Catacombs', false, 'The Catacombs', 'The Catacombs', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 29 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'kara-korum'), NULL, 'the-celestial-necropolis', 'The Celestial Necropolis', false, 'The Celestial Necropolis', 'The Celestial Necropolis', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 40 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'the-cistern', 'The Cistern', false, 'The Cistern', 'The Cistern', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 19 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'kara-korum'), NULL, 'the-enigmata-of-yag', 'The Enigmata of Yag', false, 'The Enigmata of Yag', 'The Enigmata of Yag', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 107 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'gateway-to-khitai'), NULL, 'the-forgotten-city', 'The Forgotten City', false, 'The Forgotten City', 'The Forgotten City', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 7 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'the-main-system', 'The Main System', false, 'The Main System', 'The Main System', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 60 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), NULL, 'the-maze', 'The Maze', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), NULL, 'the-prison-colony', 'The Prison Colony', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), NULL, 'the-slaughterhouse-cellar', 'The Slaughterhouse Cellar', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), NULL, 'the-slithering-chaos', 'The Slithering Chaos', false, 'The Slithering Chaos', 'The Slithering Chaos', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 8 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), NULL, 'thoth-amon-s-stronghold', 'Thoth-Amon''s Stronghold', false, 'Thoth-Amon''s Stronghold', 'Thoth Amon''s Stronghold', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 341 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), NULL, 'toirdealbach-s-tomb', 'Toirdealbach''s Tomb', false, 'Toirdealbach''s Tomb', 'Toirdealbach''s Tomb', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 15 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'tortage'), (SELECT id FROM maps WHERE slug = 'city-of-tortage'), NULL, 'tortage-underhalls', 'Tortage Underhalls', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), NULL, 'treasury-of-the-ancients', 'Treasury of the Ancients', false, 'Treasury of the Ancients', 'Treasury of the Ancients', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 11 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'villa-amiel', 'Villa Amiel', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'villa-camillus', 'Villa Camillus', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'villa-lentulus', 'Villa Lentulus', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'villa-paetus', 'Villa Paetus', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), NULL, 'villa-verde', 'Villa Verde', false, NULL, NULL, (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), NULL, 'vistrix-s-lair', 'Vistrix''s Lair', false, 'Vistrix''s Lair', 'Vistrix''s Lair', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 263 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), NULL, 'warmonk-monastery', 'Warmonk Monastery', false, 'Warmonk Monastery', 'Warmonk Monastery', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 1 armory source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), NULL, 'xibaluku', 'Xibaluku', false, 'Xibaluku', 'Xibaluku', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 78 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), NULL, 'yakhmar-s-cave', 'Yakhmar''s Cave', false, 'Yakhmar''s Cave', 'Yakhmar''s Cave', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 264 armory source rows (Tier A*)', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 5 rows — the two complexes' dungeons, in a SEPARATE statement so the
-- parent_place_id sub-select can see the rows above.
INSERT INTO places (region_id, map_id, parent_place_id, slug, name, unchained, armory_instance, armory_dungeon, confidence_id, source_note, open_question) VALUES
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), (SELECT id FROM places WHERE slug = 'warmonk-monastery'), 'coppice-of-the-heart', 'Coppice of the Heart', false, 'Coppice of the Heart', 'Coppice of the Heart', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 58 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), (SELECT id FROM places WHERE slug = 'warmonk-monastery'), 'reliquary-of-flame', 'Reliquary of Flame', false, 'Reliquary of Flame', 'Reliquary of Flame', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 54 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), (SELECT id FROM places WHERE slug = 'house-of-crom'), 'the-vile-nativity', 'The Vile Nativity', false, 'The Vile Nativity (House of Crom)', 'The Vile Nativity', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 52 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), (SELECT id FROM places WHERE slug = 'house-of-crom'), 'threshold-of-divinity', 'Threshold of Divinity', false, 'Threshold of Divinity (House of Crom)', 'Threshold of Divinity', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 100 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'northern-grasslands'), (SELECT id FROM places WHERE slug = 'warmonk-monastery'), 'vortex-of-the-storm', 'Vortex of the Storm', false, 'Vortex of the Storm', 'Vortex of the Storm', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); corroborated by 62 armory source rows (Tier A*)', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 44 rows
INSERT INTO bosses (place_id, map_id, region_id, slug, name, confidence_id, source_note, open_question) VALUES
    ((SELECT id FROM places WHERE slug = 'amphitheatre-of-karutonia-unchained'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'abyssal-convoker', 'Abyssal Convoker', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'thoth-amon-s-stronghold'), (SELECT id FROM maps WHERE slug = 'kheshatta'), (SELECT id FROM regions WHERE slug = 'stygia'), 'arbanus', 'Arbanus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'temple-of-erlik'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'arch-lector-zaal', 'Arch Lector Zaal', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 29 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'temple-of-erlik'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'archfiend-of-gore', 'Archfiend of Gore', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 18 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'armsmaster-uxus', 'Armsmaster Uxus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'temple-of-erlik'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'bat-of-nergal', 'Bat of Nergal', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 26 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'otherworldly-junction'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'champion-of-the-honorguard', 'Champion of the Honorguard', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 28 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'ai-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'cheehwa-one-eye', 'Cheehwa One Eye', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows name it (Tier A*)', NULL),
    (NULL, (SELECT id FROM maps WHERE slug = 'chosain-province'), (SELECT id FROM regions WHERE slug = 'khitai'), 'cheng-ho-battle-commander', 'Cheng-Ho Battle Commander', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'Pierre''s research, 2026-09-13 (open_questions.md § 2) — confirmed a boss, not a place; located by 9 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'ai-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'commander-yeng-wang-yeh', 'Commander Yeng-Wang-Yeh', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 7 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'palace-of-cetriss'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'ethram-fal', 'Ethram-Fal', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 12 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'thoth-amon-s-stronghold'), (SELECT id FROM maps WHERE slug = 'kheshatta'), (SELECT id FROM regions WHERE slug = 'stygia'), 'favored-of-louhi', 'Favored of Louhi', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'general-sheng', 'General Sheng', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 11 source rows name it (Tier A*)', NULL),
    (NULL, (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'gugalanna-of-yimsha', 'Gugalanna of Yimsha', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'Pierre''s research, 2026-09-13 (open_questions.md § 2) — confirmed a boss, not a place; located by 1 armory source row (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'imp', 'Imp', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 13 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'juxia-the-berserk', 'Juxia the Berserk', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'thoth-amon-s-stronghold'), (SELECT id FROM maps WHERE slug = 'kheshatta'), (SELECT id FROM regions WHERE slug = 'stygia'), 'keeper-of-artifacts', 'Keeper of Artifacts', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 22 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'threshold-of-divinity'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'khor-nu-the-archarcanist', 'Khor-nu the Archarcanist', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'otherworldly-junction'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'kyllikki', 'Kyllikki', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 32 source rows name it (Tier A*)', 'the armory puts this boss in Otherworldly Junction (Stygia) while a place of the same name sits in Cimmeria (Kyllikki''s Crypt). AOC-017 § Defect 13: these rows are the Unchained variants'),
    ((SELECT id FROM places WHERE slug = 'palace-of-cetriss'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'lotus-domination', 'Lotus Domination', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 13 source rows name it (Tier A*)', NULL),
    (NULL, (SELECT id FROM maps WHERE slug = 'thunder-river'), (SELECT id FROM regions WHERE slug = 'aquilonia'), 'lunn-the-warmonger', 'Lunn the Warmonger', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'Pierre''s research, 2026-09-13 (open_questions.md § 2) — confirmed a boss, not a place; located by 5 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'ardashir-arena'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'marjan-of-kara-shehr', 'Marjan of Kara-Shehr', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 21 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'thoth-amon-s-stronghold'), (SELECT id FROM maps WHERE slug = 'kheshatta'), (SELECT id FROM regions WHERE slug = 'stygia'), 'master-gyas', 'Master Gyas', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 15 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'noztaal', 'Noztaal', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'obsidian-basilisk', 'Obsidian Basilisk', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 12 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'shadowmaster', 'Shadowmaster', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'threshold-of-divinity'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'shryke-the-storm-shrieker', 'Shryke the Storm-Shrieker', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'ai-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'sxi-ai', 'Sxi Ai', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows name it (Tier A*)', NULL),
    (NULL, (SELECT id FROM maps WHERE slug = 'chosain-province'), (SELECT id FROM regions WHERE slug = 'khitai'), 'tamarin-battle-commander', 'Tamarin Battle Commander', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'Pierre''s research, 2026-09-13 (open_questions.md § 2) — confirmed a boss, not a place; located by 8 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'amphitheatre-of-karutonia-unchained'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'the-devourer', 'The Devourer', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'amphitheatre-of-karutonia-unchained'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'the-dimensionalist', 'The Dimensionalist', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'the-entity', 'The Entity', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 24 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'palace-of-cetriss'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'the-faceless-god', 'The Faceless God', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 24 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'the-ironwright', 'The Ironwright', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'threshold-of-divinity'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'the-lurker-at-the-threshold', 'The Lurker at the Threshold', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 14 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'thoth-amon-s-stronghold'), (SELECT id FROM maps WHERE slug = 'kheshatta'), (SELECT id FROM regions WHERE slug = 'stygia'), 'thoth-amon', 'Thoth-Amon', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 22 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'time-trial', 'Time Trial', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows name it (Tier A*)', 'reads like a challenge mode rather than a boss; the armory files 5 T''ian''an District rows under it'),
    ((SELECT id FROM places WHERE slug = 'ardashir-arena'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), (SELECT id FROM regions WHERE slug = 'turan'), 'tomb-king', 'Tomb King', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 21 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'otherworldly-junction'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'vistrix', 'Vistrix', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 32 source rows name it (Tier A*)', 'the armory puts this boss in Otherworldly Junction (Stygia) while a place of the same name sits in Cimmeria (Vistrix''s Lair). AOC-017 § Defect 13: these rows are the Unchained variants'),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'yah-chieng', 'Yah Chieng', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 29 source rows name it (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'otherworldly-junction'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), (SELECT id FROM regions WHERE slug = 'stygia'), 'yakhmar', 'Yakhmar', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows name it (Tier A*)', 'the armory puts this boss in Otherworldly Junction (Stygia) while a place of the same name sits in Cimmeria (Yakhmar''s Cave). AOC-017 § Defect 13: these rows are the Unchained variants'),
    ((SELECT id FROM places WHERE slug = 't-ian-an-district'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'yi-t-ian', 'Yi-T''ian', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows name it (Tier A*)', NULL),
    (NULL, (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), (SELECT id FROM regions WHERE slug = 'cimmeria'), 'ymir-s-son', 'Ymir''s Son', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'Pierre''s research, 2026-09-13 (open_questions.md § 2) — confirmed a boss, not a place; located by 2 armory source rows (Tier A*)', NULL),
    ((SELECT id FROM places WHERE slug = 'jade-citadel'), (SELECT id FROM maps WHERE slug = 'paikang'), (SELECT id FROM regions WHERE slug = 'khitai'), 'zodiac', 'Zodiac', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 16 source rows name it (Tier A*)', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 51 rows. name stays NULL — see the table comment.
INSERT INTO quests (region_id, map_id, slug, armory_label, confidence_id, source_note, open_question) VALUES
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'king-conan-s-castle'), 'aelfrith', 'Aelfrith', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'dragon-s-spine'), 'arch-lector-tiandal', 'Arch Lector Tiandal', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), 'archpriest-zyras', 'Archpriest Zyras', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'turan'), (SELECT id FROM maps WHERE slug = 'coast-of-ardashir'), 'artus', 'Artus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'ymir-s-pass'), 'atali', 'Atali', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), 'attadeus', 'Attadeus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), 'azusena', 'Azusena', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), 'bodhrann', 'Bodhrann', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), 'captain-nut', 'Captain Nut', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 6 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), 'cian', 'Cian', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'conall-s-valley'), 'conall-s-valley', 'Conall''s Valley', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 21 source rows (Tier A*)', 'this label is the name of a map, so it is not the quest''s name'),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), 'cul-chieftain', 'Cul Chieftain', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), 'delryn', 'Delryn', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), NULL, 'destiny-quests', 'Destiny quests', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 23 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), 'dexion', 'Dexion', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'doran', 'Doran', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), 'dorina', 'Dorina', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    (NULL, NULL, 'dungeon-mastery-excavators', 'Dungeon Mastery: Excavators', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 11 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), 'evodius', 'Evodius', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), 'fendaen', 'Fendaen', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), 'general-lupercus', 'General Lupercus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 6 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), NULL, 'general-zarathus', 'General Zarathus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', 'the armory files it under map ''Border Range'', which is not a seeded map — Pierre''s geography calls that an instance'),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), 'governor-myrtilos', 'Governor Myrtilos', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'thunder-river'), 'guard-captain-marcus', 'Guard Captain Marcus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), 'iti', 'Iti', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'kiebus', 'Kiebus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'king-conan-s-castle'), 'king-conan', 'King Conan', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 12 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'gateway-to-khitai'), 'li-min', 'Li-min', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), 'luciano', 'Luciano', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), NULL, 'milestones-quest-rewards', 'Milestones Quest Rewards', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), 'mizra-suffi', 'Mizra Suffi', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-common-district'), 'muriela', 'Muriela', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'neoric-manywinter', 'Neoric Manywinter', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'oisin', 'Oisin', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'old-tarantia'), 'outflow-tunnels', 'Outflow Tunnels', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', 'this label is the name of a place, so it is not the quest''s name'),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), 'reburrus', 'Reburrus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'eiglophian-mountains'), 'rithriall', 'Rithriall', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'rulvio', 'Rulvio', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'atzel-s-approach'), 'sagan', 'Sagan', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), 'semira', 'Semira', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), 'serafis', 'Serafis', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 2 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), NULL, 'sergeant-vargus', 'Sergeant Vargus', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', 'the armory files it under map ''Border Range'', which is not a seeded map — Pierre''s geography calls that an instance'),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khopshef-province'), 'seth-ur', 'Seth-Ur', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'khemi'), 'silver-atrium', 'Silver Atrium', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'cimmeria'), (SELECT id FROM maps WHERE slug = 'field-of-the-dead'), 'spirit-of-leannan', 'Spirit of Leannan', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 8 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), (SELECT id FROM maps WHERE slug = 'gateway-to-khitai'), 'taichu', 'Taichu', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 3 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'khitai'), NULL, 'the-eleven-sacred-weapons-of-hwanung', 'The Eleven Sacred Weapons of Hwanung', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 25 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), 'twinkle', 'Twinkle', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 1 source row (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'stygia'), (SELECT id FROM maps WHERE slug = 'kheshatta'), 'viltren-al-mackra', 'Viltren Al''mackra', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 5 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'tarantia-noble-district'), 'watch-captain-falco', 'Watch Captain Falco', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL),
    ((SELECT id FROM regions WHERE slug = 'aquilonia'), (SELECT id FROM maps WHERE slug = 'wild-lands-of-zelata'), 'zelata', 'Zelata', (SELECT id FROM confidence_levels WHERE slug = 'unconfirmed'), 'items_clean.json — 4 source rows (Tier A*)', NULL)
ON CONFLICT (slug) DO NOTHING;

-- 2 rows
INSERT INTO containers (slug, name, confidence_id, source_note, open_question) VALUES
    ('acheronian-cache', 'Acheronian Cache', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); 294 armory source rows', NULL),
    ('mystical-excavator-s-kit', 'Mystical Excavator''s Kit', (SELECT id FROM confidence_levels WHERE slug = 'verified'), 'reference_geography.json (Pierre, Tier A, 2026-09-13); 11 armory source rows', NULL)
ON CONFLICT (slug) DO NOTHING;

-- +goose Down
DROP TABLE IF EXISTS containers;
DROP TABLE IF EXISTS quests;
DROP TABLE IF EXISTS bosses;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS maps;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS confidence_levels;
