package items

// The on-disk shape of armory_snapshot/items_clean.json.
//
// ⭐ DECODING REJECTS UNKNOWN FIELDS. The snapshot is generated by a script in another repository
// and it has gained fields three times already (tooltip_source_url, on_hold, on_hold_reason). A
// silently ignored field is a fact that stops arriving without anyone noticing, which on this
// project is the whole failure mode. Drift must break the import, loudly, on the first run.
//
// ⚠️ Pointers, not zero values, on everything the snapshot leaves out. `armour_weight: null` and
// `armour_weight: ""` are different claims — one is "unknown", the other would be a value we made
// up — and this database is full of genuinely unknown fields (CLAUDE.md STEP ZERO).

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
)

// Item is one row of items_clean.json.
type Item struct {
	ItemID            int      `json:"item_id"`
	Name              string   `json:"name"`
	Rarity            *string  `json:"rarity"`
	ItemType          *string  `json:"item_type"`
	PvPSource         bool     `json:"pvp_source"`
	HasPvPStats       bool     `json:"has_pvp_stats"`
	PvPPenalty        bool     `json:"pvp_penalty"`
	Classes           []string `json:"classes"`
	ArmourWeight      *string  `json:"armour_weight"`
	EquipLocation     *string  `json:"equip_location"`
	ItemLevel         *int     `json:"item_level"`
	RequiresLevel     *int     `json:"requires_level"`
	Armor             *int     `json:"armor"`
	Critigation       *int     `json:"critigation"`
	DPS               *float64 `json:"dps"`
	DamageRange       *string  `json:"damage_range"`
	Stats             []Stat   `json:"stats"`
	SpellEffect       []Stat   `json:"spell_effect"`
	Set               *string  `json:"set"`
	SetPieces         *int     `json:"set_pieces"`
	Faction           *string  `json:"faction"`
	FactionRank       *int     `json:"faction_rank"`
	Binding           *string  `json:"binding"`
	NoLongerAvailable any      `json:"no_longer_available"` // false, or a reason string
	TooltipImage      *string  `json:"tooltip_image"`
	TooltipSourceURL  *string  `json:"tooltip_source_url"`
	Sources           []Source `json:"sources"`
}

// Stat is one row of `stats` or of `spell_effect`. The two have the same shape and are
// deliberately kept apart all the way into the database (AOC-010).
type Stat struct {
	Stat       string  `json:"stat"`
	Value      float64 `json:"value"`
	Sign       int     `json:"sign"`
	Unit       string  `json:"unit"`
	DamageType *string `json:"damage_type"`
	PvP        bool    `json:"pvp"`
}

// Source is one place-or-vendor an item comes from. One row per place AND per boss, so an item
// commonly has several (6,641 rows over 4,648 items).
type Source struct {
	AcquisitionType *string `json:"acquisition_type"`
	AcquisitionCost []Cost  `json:"acquisition_cost"`
	Container       *string `json:"container"`
	Unchained       bool    `json:"unchained"`
	Region          *string `json:"region"`
	RegionSource    *string `json:"region_source"`
	Map             *string `json:"map"`
	Instance        *string `json:"instance"`
	DungeonOrRaid   *string `json:"dungeon_or_raid"`
	BossOrNPC       *string `json:"boss_or_npc"`
	Vendor          *string `json:"vendor"`
	Quest           *string `json:"quest"`
	IsRaid          bool    `json:"is_raid"`
	Coords          []int   `json:"coords"`
	Tier            *string `json:"tier"`
	SectionRaw      *string `json:"section_raw"`
	OnHold          bool    `json:"on_hold"`
	OnHoldReason    *string `json:"on_hold_reason"`
}

// Cost is one currency amount on a source row. A source can cost several tokens at once.
type Cost struct {
	Currency string  `json:"currency"`
	Amount   float64 `json:"amount"`
}

// Excluded reports whether this item is one Pierre's 2026-09-13 decision keeps out of the
// database: items that can no longer be obtained. The row stays in the snapshot forever — the
// archive is the preservation — but "an armory consulted before a raid should not list something
// nobody can get". Returns the reason so the importer can print it.
func (i Item) Excluded() (string, bool) {
	switch v := i.NoLongerAvailable.(type) {
	case string:
		if v != "" {
			return v, true
		}
	case bool:
		if v {
			return "no_longer_available", true
		}
	}
	return "", false
}

// LiveSources are the sources the database takes: everything not quarantined. The held rows are
// the 68 Pierre put on hold in 2026-09-13 — Tier 5 Stygian loot filed under Tier 1 Cimmerian
// bosses. We show the item and blank the source: a wrong fact is worse than a missing one.
func (i Item) LiveSources() []Source {
	out := make([]Source, 0, len(i.Sources))
	for _, s := range i.Sources {
		if !s.OnHold {
			out = append(out, s)
		}
	}
	return out
}

// LoadSnapshot reads items_clean.json, refusing any field it does not know about.
func LoadSnapshot(path string) ([]Item, error) {
	f, err := os.Open(path) // #nosec G304 -- operator-supplied path; this is a CLI import tool
	if err != nil {
		return nil, fmt.Errorf("opening snapshot: %w", err)
	}
	defer func() { _ = f.Close() }()
	return DecodeSnapshot(f)
}

// DecodeSnapshot is LoadSnapshot's testable half.
func DecodeSnapshot(r io.Reader) ([]Item, error) {
	dec := json.NewDecoder(r)
	dec.DisallowUnknownFields()
	var items []Item
	if err := dec.Decode(&items); err != nil {
		return nil, fmt.Errorf("decoding snapshot (a new field in the generator will look like "+
			"this, and that is deliberate): %w", err)
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("the snapshot decoded to zero items — refusing to treat that as an empty import")
	}
	return items, nil
}
