// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package sqlcgen

import (
	"context"
)

const listBuildArmourWeights = `-- name: ListBuildArmourWeights :many
SELECT slug, sort_order FROM armour_weights ORDER BY sort_order
`

type ListBuildArmourWeightsRow struct {
	Slug      string
	SortOrder int32
}

// Only read when the picked class has a ceiling: a list row names its weight by slug.
func (q *Queries) ListBuildArmourWeights(ctx context.Context) ([]ListBuildArmourWeightsRow, error) {
	rows, err := q.db.Query(ctx, listBuildArmourWeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildArmourWeightsRow{}
	for rows.Next() {
		var i ListBuildArmourWeightsRow
		if err := rows.Scan(&i.Slug, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildClasses = `-- name: ListBuildClasses :many
SELECT c.slug, c.name, c.short_name, a.name AS archetype_name,
       aw.sort_order AS max_armour_weight_order
FROM classes c
JOIN archetypes a ON a.id = c.archetype_id
LEFT JOIN armour_weights aw ON aw.id = c.max_armour_weight
ORDER BY c.sort_order NULLS LAST, c.name
`

type ListBuildClassesRow struct {
	Slug                 string
	Name                 string
	ShortName            *string
	ArchetypeName        string
	MaxArmourWeightOrder *int32
}

// The class picker, in classes.sort_order (AOC-065), with each class's armour ceiling when one is
// recorded (none is yet: it is Pierre's to supply).
func (q *Queries) ListBuildClasses(ctx context.Context) ([]ListBuildClassesRow, error) {
	rows, err := q.db.Query(ctx, listBuildClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildClassesRow{}
	for rows.Next() {
		var i ListBuildClassesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.ShortName,
			&i.ArchetypeName,
			&i.MaxArmourWeightOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildHands = `-- name: ListBuildHands :many
SELECT DISTINCT iel.equip_location_id
FROM item_equip_locations iel
JOIN items i ON i.item_id = iel.item_id
JOIN item_types it ON it.id = i.item_type_id
WHERE it.two_handed = false
ORDER BY iel.equip_location_id
`

// The hands: the slots a ONE-handed weapon fits (item_types.two_handed = false). A two-hander takes
// both, so it locks every one of these but its own. Derived from the items rather than named, so no
// slot slug is written in code (reference/content-model.md § 0).
func (q *Queries) ListBuildHands(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, listBuildHands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var equip_location_id int32
		if err := rows.Scan(&equip_location_id); err != nil {
			return nil, err
		}
		items = append(items, equip_location_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildItemClasses = `-- name: ListBuildItemClasses :many
SELECT ic.item_id, cl.slug
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = ANY($1::integer[])
ORDER BY ic.item_id, cl.sort_order NULLS LAST, cl.id
`

type ListBuildItemClassesRow struct {
	ItemID int32
	Slug   string
}

func (q *Queries) ListBuildItemClasses(ctx context.Context, itemIds []int32) ([]ListBuildItemClassesRow, error) {
	rows, err := q.db.Query(ctx, listBuildItemClasses, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildItemClassesRow{}
	for rows.Next() {
		var i ListBuildItemClassesRow
		if err := rows.Scan(&i.ItemID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildItemSlots = `-- name: ListBuildItemSlots :many
SELECT iel.item_id, el.slug
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = ANY($1::integer[])
ORDER BY iel.item_id, el.id
`

type ListBuildItemSlotsRow struct {
	ItemID int32
	Slug   string
}

func (q *Queries) ListBuildItemSlots(ctx context.Context, itemIds []int32) ([]ListBuildItemSlotsRow, error) {
	rows, err := q.db.Query(ctx, listBuildItemSlots, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildItemSlotsRow{}
	for rows.Next() {
		var i ListBuildItemSlotsRow
		if err := rows.Scan(&i.ItemID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildItemStats = `-- name: ListBuildItemStats :many
SELECT st.item_id, st.stat, st.unit, st.damage_type, st.pvp,
       (st.sign * st.value * 100)::bigint AS centi
FROM item_stats st
WHERE st.item_id = ANY($1::integer[])
ORDER BY st.item_id, st.id
`

type ListBuildItemStatsRow struct {
	ItemID     int32
	Stat       string
	Unit       string
	DamageType *string
	Pvp        bool
	Centi      int64
}

// In the tooltip's order (the id, as ListItemStats), each value as signed HUNDREDTHS: the column is
// numeric(8,2), so ×100 is a whole number, and the sum is exact integer arithmetic — never a float.
// Stats only: spell effects are another table on purpose, and a build never sums them.
func (q *Queries) ListBuildItemStats(ctx context.Context, itemIds []int32) ([]ListBuildItemStatsRow, error) {
	rows, err := q.db.Query(ctx, listBuildItemStats, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildItemStatsRow{}
	for rows.Next() {
		var i ListBuildItemStatsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
			&i.Centi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildItems = `-- name: ListBuildItems :many
SELECT i.item_id, i.slug, i.name, r.colour_token AS rarity_colour_token,
       i.item_type_id, COALESCE(it.two_handed, false)::boolean AS two_handed,
       it.other_hand_type_id, oh.slug AS other_hand_type_slug, oh.name AS other_hand_type_name,
       aw.sort_order AS armour_weight_order,
       i.armor, i.critigation, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
LEFT JOIN item_types oh ON oh.id = it.other_hand_type_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
WHERE i.item_id = ANY($1::integer[])
`

type ListBuildItemsRow struct {
	ItemID            int32
	Slug              string
	Name              string
	RarityColourToken *string
	ItemTypeID        *int32
	TwoHanded         bool
	OtherHandTypeID   *int32
	OtherHandTypeSlug *string
	OtherHandTypeName *string
	ArmourWeightOrder *int32
	Armor             *int32
	Critigation       *int32
	TooltipImage      *string
}

// A build's items, with what the rules read: the type's hands (two_handed, and what a two-hander
// still allows in the other hand), the armour weight's place in the order, and the base lines. And
// the tooltip image, which the page shows beside the cursor on a slot's item name (AOC-074).
func (q *Queries) ListBuildItems(ctx context.Context, itemIds []int32) ([]ListBuildItemsRow, error) {
	rows, err := q.db.Query(ctx, listBuildItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildItemsRow{}
	for rows.Next() {
		var i ListBuildItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.RarityColourToken,
			&i.ItemTypeID,
			&i.TwoHanded,
			&i.OtherHandTypeID,
			&i.OtherHandTypeSlug,
			&i.OtherHandTypeName,
			&i.ArmourWeightOrder,
			&i.Armor,
			&i.Critigation,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildSlots = `-- name: ListBuildSlots :many

SELECT id, slug, name FROM equip_locations ORDER BY id
`

// The gear builder (AOC-051). Every query takes the whole build at once — never one per item, the
// ListItemPlaces pattern.
// The builder's rows: every equipment slot, in the seed's order (the id). AoC>TV's builder has the
// same 14 (Pierre, 2026-09-29; Necklace since AOC-054).
func (q *Queries) ListBuildSlots(ctx context.Context) ([]EquipLocation, error) {
	rows, err := q.db.Query(ctx, listBuildSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquipLocation{}
	for rows.Next() {
		var i EquipLocation
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
