// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getItem = `-- name: GetItem :one

SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, it.slug AS item_type,
       sf.slug AS slot_fit,
       aw.slug AS armour_weight, b.slug AS binding,
       i.item_level, i.requires_level, i.armor, i.critigation, i.dps, i.damage_range,
       i.set_id, s.name AS set_name,
       f.slug AS faction, i.faction_rank,
       i.pvp_source, i.has_pvp_stats, i.pvp_penalty, i.no_longer_available,
       i.tooltip_image, i.tooltip_source_url,
       c.slug AS confidence, i.source_note, i.open_question
FROM items i
JOIN rarities r ON r.id = i.rarity_id
JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
LEFT JOIN bindings b ON b.id = i.binding_id
LEFT JOIN sets s ON s.id = i.set_id
LEFT JOIN factions f ON f.id = i.faction_id
WHERE i.item_id = $1
`

type GetItemRow struct {
	ItemID            int32
	Slug              string
	Name              string
	Rarity            string
	ItemType          string
	SlotFit           *string
	ArmourWeight      *string
	Binding           *string
	ItemLevel         *int32
	RequiresLevel     *int32
	Armor             *int32
	Critigation       *int32
	Dps               pgtype.Numeric
	DamageRange       *string
	SetID             *int32
	SetName           *string
	Faction           *string
	FactionRank       *int32
	PvpSource         bool
	HasPvpStats       bool
	PvpPenalty        bool
	NoLongerAvailable *string
	TooltipImage      *string
	TooltipSourceUrl  *string
	Confidence        string
	SourceNote        string
	OpenQuestion      *string
}

// Read queries for the Armory (AOC-010). The write side belongs to the importer (AOC-011) and the
// public endpoints to AOC-012; what is here is the shape both of them read through.
//
// ⭐ EQUIP LOCATION IS A JOIN. `ListItems` filters slots through item_equip_locations, never
// through a column on items, because 390 two-handers occupy Main Hand AND Off Hand and 188 rings
// occupy EITHER finger. A query that filtered a single column would silently drop the 390 —
// the reason the join exists at all (see the migration header).
//
// ⚠️ Every read returns confidence and open_question with the row, like places.sql. A page that
// cannot show how sure we are cannot honour sourcing-standards § 3, and dropping them from the
// SELECT is how that rule quietly stops being enforced.
//
// ⚠️ Stats and spell effects are returned by SEPARATE queries from separate tables. Nothing here
// unions them, so nothing downstream can sum a mount's -8% Sprinting Stamina Drain into a build.
func (q *Queries) GetItem(ctx context.Context, itemID int32) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, itemID)
	var i GetItemRow
	err := row.Scan(
		&i.ItemID,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.ItemType,
		&i.SlotFit,
		&i.ArmourWeight,
		&i.Binding,
		&i.ItemLevel,
		&i.RequiresLevel,
		&i.Armor,
		&i.Critigation,
		&i.Dps,
		&i.DamageRange,
		&i.SetID,
		&i.SetName,
		&i.Faction,
		&i.FactionRank,
		&i.PvpSource,
		&i.HasPvpStats,
		&i.PvpPenalty,
		&i.NoLongerAvailable,
		&i.TooltipImage,
		&i.TooltipSourceUrl,
		&i.Confidence,
		&i.SourceNote,
		&i.OpenQuestion,
	)
	return i, err
}

const getItemBySlug = `-- name: GetItemBySlug :one
SELECT i.item_id FROM items i WHERE i.slug = $1
`

func (q *Queries) GetItemBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, getItemBySlug, slug)
	var item_id int32
	err := row.Scan(&item_id)
	return item_id, err
}

const listItemClasses = `-- name: ListItemClasses :many
SELECT cl.id, cl.slug, cl.name
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = $1
ORDER BY cl.name
`

type ListItemClassesRow struct {
	ID   int32
	Slug string
	Name string
}

func (q *Queries) ListItemClasses(ctx context.Context, itemID int32) ([]ListItemClassesRow, error) {
	rows, err := q.db.Query(ctx, listItemClasses, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemClassesRow{}
	for rows.Next() {
		var i ListItemClassesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCosts = `-- name: ListItemCosts :many
SELECT ic.item_source_id, cu.slug AS currency, cu.name AS currency_name, ic.amount
FROM item_costs ic
JOIN currencies cu ON cu.id = ic.currency_id
WHERE ic.item_source_id = ANY($1::bigint[])
ORDER BY ic.item_source_id, cu.name
`

type ListItemCostsRow struct {
	ItemSourceID int64
	Currency     string
	CurrencyName string
	Amount       pgtype.Numeric
}

func (q *Queries) ListItemCosts(ctx context.Context, dollar_1 []int64) ([]ListItemCostsRow, error) {
	rows, err := q.db.Query(ctx, listItemCosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemCostsRow{}
	for rows.Next() {
		var i ListItemCostsRow
		if err := rows.Scan(
			&i.ItemSourceID,
			&i.Currency,
			&i.CurrencyName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemEquipLocations = `-- name: ListItemEquipLocations :many
SELECT el.id, el.slug, el.name
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = $1
ORDER BY el.id
`

func (q *Queries) ListItemEquipLocations(ctx context.Context, itemID int32) ([]EquipLocation, error) {
	rows, err := q.db.Query(ctx, listItemEquipLocations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquipLocation{}
	for rows.Next() {
		var i EquipLocation
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSources = `-- name: ListItemSources :many
SELECT src.id, src.item_id,
       at.slug AS acquisition_type,
       src.place_id, p.name AS place_name,
       src.boss_id, bo.name AS boss_name,
       src.vendor_id, v.name AS vendor_name,
       src.quest_id, q.name AS quest_name,
       src.container_id, ct.name AS container_name,
       src.region_id, rg.name AS region_name,
       src.map_id, mp.name AS map_name,
       src.tier_id, tr.slug AS tier,
       src.is_raid, src.coords, src.section_raw, src.unchained,
       c.slug AS confidence, src.source_note, src.open_question
FROM item_sources src
JOIN confidence_levels c ON c.id = src.confidence_id
LEFT JOIN acquisition_types at ON at.id = src.acquisition_type_id
LEFT JOIN places p ON p.id = src.place_id
LEFT JOIN bosses bo ON bo.id = src.boss_id
LEFT JOIN places v ON v.id = src.vendor_id
LEFT JOIN quests q ON q.id = src.quest_id
LEFT JOIN containers ct ON ct.id = src.container_id
LEFT JOIN regions rg ON rg.id = src.region_id
LEFT JOIN maps mp ON mp.id = src.map_id
LEFT JOIN tiers tr ON tr.id = src.tier_id
WHERE src.item_id = $1
ORDER BY src.id
`

type ListItemSourcesRow struct {
	ID              int64
	ItemID          int32
	AcquisitionType *string
	PlaceID         *int32
	PlaceName       *string
	BossID          *int32
	BossName        *string
	VendorID        *int32
	VendorName      *string
	QuestID         *int32
	QuestName       *string
	ContainerID     *int32
	ContainerName   *string
	RegionID        *int32
	RegionName      *string
	MapID           *int32
	MapName         *string
	TierID          *int32
	Tier            *string
	IsRaid          bool
	Coords          *string
	SectionRaw      *string
	Unchained       bool
	Confidence      string
	SourceNote      string
	OpenQuestion    *string
}

// An item page's "where does this come from". 422 items have more than one place, so this is a
// list and never a single row.
func (q *Queries) ListItemSources(ctx context.Context, itemID int32) ([]ListItemSourcesRow, error) {
	rows, err := q.db.Query(ctx, listItemSources, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSourcesRow{}
	for rows.Next() {
		var i ListItemSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AcquisitionType,
			&i.PlaceID,
			&i.PlaceName,
			&i.BossID,
			&i.BossName,
			&i.VendorID,
			&i.VendorName,
			&i.QuestID,
			&i.QuestName,
			&i.ContainerID,
			&i.ContainerName,
			&i.RegionID,
			&i.RegionName,
			&i.MapID,
			&i.MapName,
			&i.TierID,
			&i.Tier,
			&i.IsRaid,
			&i.Coords,
			&i.SectionRaw,
			&i.Unchained,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSpellEffects = `-- name: ListItemSpellEffects :many
SELECT se.item_id, se.stat, se.value, se.sign, se.unit, se.damage_type, se.pvp
FROM item_spell_effects se
WHERE se.item_id = $1
ORDER BY se.stat
`

type ListItemSpellEffectsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

// Deliberately its own query against its own table. See the header.
func (q *Queries) ListItemSpellEffects(ctx context.Context, itemID int32) ([]ListItemSpellEffectsRow, error) {
	rows, err := q.db.Query(ctx, listItemSpellEffects, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSpellEffectsRow{}
	for rows.Next() {
		var i ListItemSpellEffectsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStats = `-- name: ListItemStats :many
SELECT st.item_id, st.stat, st.value, st.sign, st.unit, st.damage_type, st.pvp
FROM item_stats st
WHERE st.item_id = $1
ORDER BY st.stat
`

type ListItemStatsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

func (q *Queries) ListItemStats(ctx context.Context, itemID int32) ([]ListItemStatsRow, error) {
	rows, err := q.db.Query(ctx, listItemStats, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemStatsRow{}
	for rows.Next() {
		var i ListItemStatsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, r.sort_order AS rarity_sort,
       it.slug AS item_type,
       sf.slug AS slot_fit,
       i.item_level, i.requires_level, i.armor, i.dps,
       i.set_id, i.tooltip_image,
       c.slug AS confidence,
       count(*) OVER () AS total_count
FROM items i
JOIN rarities r ON r.id = i.rarity_id
JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
WHERE ($1::varchar IS NULL OR r.slug = $1::varchar)
  AND ($2::varchar IS NULL OR it.slug = $2::varchar)
  AND ($3::varchar IS NULL OR i.name ILIKE '%' || $3::varchar || '%')
  AND ($4::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_equip_locations iel
        JOIN equip_locations el ON el.id = iel.equip_location_id
        WHERE iel.item_id = i.item_id AND el.slug = $4::varchar))
  AND ($5::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_classes ic
        JOIN classes cl ON cl.id = ic.class_id
        WHERE ic.item_id = i.item_id AND cl.slug = $5::varchar))
  AND ($6::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_sources src
        JOIN places p ON p.id = src.place_id
        WHERE src.item_id = i.item_id AND p.slug = $6::varchar))
ORDER BY i.name, i.item_id
LIMIT $8::integer OFFSET $7::integer
`

type ListItemsParams struct {
	Rarity        *string
	ItemType      *string
	NameQuery     *string
	EquipLocation *string
	Class         *string
	Place         *string
	PageOffset    int32
	PageSize      int32
}

type ListItemsRow struct {
	ItemID        int32
	Slug          string
	Name          string
	Rarity        string
	RaritySort    int32
	ItemType      string
	SlotFit       *string
	ItemLevel     *int32
	RequiresLevel *int32
	Armor         *int32
	Dps           pgtype.Numeric
	SetID         *int32
	TooltipImage  *string
	Confidence    string
	TotalCount    int64
}

// The Armory list page. Every filter is optional: a NULL argument means "do not filter on this",
// which keeps one query behind every combination the page offers rather than building SQL by hand.
//
// ⭐ The equip-location filter goes through the join (EXISTS), so asking for 'off-hand' returns
// the 390 two-handers as well as the 141 off-hand-only items. That is the acceptance criterion
// this whole schema shape exists for.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.Rarity,
		arg.ItemType,
		arg.NameQuery,
		arg.EquipLocation,
		arg.Class,
		arg.Place,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.ItemType,
			&i.SlotFit,
			&i.ItemLevel,
			&i.RequiresLevel,
			&i.Armor,
			&i.Dps,
			&i.SetID,
			&i.TooltipImage,
			&i.Confidence,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCurrency = `-- name: ListItemsByCurrency :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, it.slug AS item_type,
       ic.amount, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN item_costs ic ON ic.item_source_id = src.id
JOIN currencies cu ON cu.id = ic.currency_id
WHERE cu.slug = $1
ORDER BY ic.amount, i.name
`

type ListItemsByCurrencyRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	ItemType     string
	Amount       pgtype.Numeric
	TooltipImage *string
}

// A currency page: "what does this token buy?" (DECISIONS.md 2026-09-14 — currency is an entity
// with its own page, so the fact is stated once instead of on every item bought with it).
func (q *Queries) ListItemsByCurrency(ctx context.Context, slug string) ([]ListItemsByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, listItemsByCurrency, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByCurrencyRow{}
	for rows.Next() {
		var i ListItemsByCurrencyRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.ItemType,
			&i.Amount,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByPlace = `-- name: ListItemsByPlace :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, r.sort_order AS rarity_sort,
       it.slug AS item_type, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN places p ON p.id = src.place_id
WHERE p.slug = $1
ORDER BY r.sort_order DESC, i.name
`

type ListItemsByPlaceRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	RaritySort   int32
	ItemType     string
	TooltipImage *string
}

// The reverse lookup, and the one Pierre asked for first: "what drops here?" on a place page.
func (q *Queries) ListItemsByPlace(ctx context.Context, slug string) ([]ListItemsByPlaceRow, error) {
	rows, err := q.db.Query(ctx, listItemsByPlace, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByPlaceRow{}
	for rows.Next() {
		var i ListItemsByPlaceRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.ItemType,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenItemQuestions = `-- name: ListOpenItemQuestions :many
SELECT 'item' AS kind, i.item_id AS id, i.name, i.open_question
FROM items i WHERE i.open_question IS NOT NULL
UNION ALL
SELECT 'item_source', src.item_id, i.name, src.open_question
FROM item_sources src JOIN items i ON i.item_id = src.item_id
WHERE src.open_question IS NOT NULL
UNION ALL
SELECT 'set', s.id, s.name, s.open_question
FROM sets s WHERE s.open_question IS NOT NULL
ORDER BY kind, name
`

type ListOpenItemQuestionsRow struct {
	Kind         string
	ID           int32
	Name         string
	OpenQuestion *string
}

// The counterpart of AOC-009's ListOpenQuestions: everything the item data could not answer,
// in one read, so "what do we still need to ask Pierre" stays a query and not a memory.
func (q *Queries) ListOpenItemQuestions(ctx context.Context) ([]ListOpenItemQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenItemQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenItemQuestionsRow{}
	for rows.Next() {
		var i ListOpenItemQuestionsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT s.id, s.slug, s.name, cl.slug AS class, aw.slug AS set_armour_weight,
       c.slug AS confidence, s.source_note, s.open_question,
       (SELECT count(*) FROM items i WHERE i.set_id = s.id) AS piece_count
FROM sets s
JOIN confidence_levels c ON c.id = s.confidence_id
LEFT JOIN classes cl ON cl.id = s.class_id
LEFT JOIN armour_weights aw ON aw.id = s.set_armour_weight_id
ORDER BY s.name
`

type ListSetsRow struct {
	ID              int32
	Slug            string
	Name            string
	Class           *string
	SetArmourWeight *string
	Confidence      string
	SourceNote      string
	OpenQuestion    *string
	PieceCount      int64
}

func (q *Queries) ListSets(ctx context.Context) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetsRow{}
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Class,
			&i.SetArmourWeight,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
			&i.PieceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
