// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getItem = `-- name: GetItem :one

SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, it.slug AS item_type,
       sf.slug AS slot_fit,
       aw.slug AS armour_weight, b.slug AS binding,
       -- the display names and the rarity's colour, for the item PAGE (AOC-048); /v1 keeps the slugs
       r.name AS rarity_name, r.colour_token AS rarity_colour_token, it.name AS item_type_name,
       aw.name AS armour_weight_name, b.name AS binding_name,
       i.item_level, i.requires_level, i.armor, i.critigation, i.dps, i.damage_range,
       i.set_id, s.name AS set_name, s.declared_piece_count,
       f.slug AS faction, i.faction_rank,
       i.pvp_source, i.has_pvp_stats, i.pvp_penalty, i.no_longer_available,
       i.tooltip_image, i.tooltip_source_url,
       c.slug AS confidence, i.source_note, i.open_question
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
LEFT JOIN bindings b ON b.id = i.binding_id
LEFT JOIN sets s ON s.id = i.set_id
LEFT JOIN factions f ON f.id = i.faction_id
WHERE i.item_id = $1
`

type GetItemRow struct {
	ItemID             int32
	Slug               string
	Name               string
	Rarity             string
	ItemType           *string
	SlotFit            *string
	ArmourWeight       *string
	Binding            *string
	RarityName         string
	RarityColourToken  *string
	ItemTypeName       *string
	ArmourWeightName   *string
	BindingName        *string
	ItemLevel          *int32
	RequiresLevel      *int32
	Armor              *int32
	Critigation        *int32
	Dps                pgtype.Numeric
	DamageRange        *string
	SetID              *int32
	SetName            *string
	DeclaredPieceCount *int32
	Faction            *string
	FactionRank        *int32
	PvpSource          bool
	HasPvpStats        bool
	PvpPenalty         bool
	NoLongerAvailable  *string
	TooltipImage       *string
	TooltipSourceUrl   *string
	Confidence         string
	SourceNote         string
	OpenQuestion       *string
}

// Read queries for the Armory (AOC-010). The write side belongs to the importer (AOC-011) and the
// public endpoints to AOC-012; what is here is the shape both of them read through.
//
// ⭐ EQUIP LOCATION IS A JOIN. `ListItems` filters slots through item_equip_locations, never
// through a column on items, because 390 two-handers occupy Main Hand AND Off Hand and 188 rings
// occupy EITHER finger. A query that filtered a single column would silently drop the 390 —
// the reason the join exists at all (see the migration header).
//
// ⚠️ Every read returns confidence and open_question with the row, like places.sql. A page that
// cannot show how sure we are cannot honour sourcing-standards § 3, and dropping them from the
// SELECT is how that rule quietly stops being enforced.
//
// ⚠️ Stats and spell effects are returned by SEPARATE queries from separate tables. Nothing here
// unions them, so nothing downstream can sum a mount's -8% Sprinting Stamina Drain into a build.
func (q *Queries) GetItem(ctx context.Context, itemID int32) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, itemID)
	var i GetItemRow
	err := row.Scan(
		&i.ItemID,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.ItemType,
		&i.SlotFit,
		&i.ArmourWeight,
		&i.Binding,
		&i.RarityName,
		&i.RarityColourToken,
		&i.ItemTypeName,
		&i.ArmourWeightName,
		&i.BindingName,
		&i.ItemLevel,
		&i.RequiresLevel,
		&i.Armor,
		&i.Critigation,
		&i.Dps,
		&i.DamageRange,
		&i.SetID,
		&i.SetName,
		&i.DeclaredPieceCount,
		&i.Faction,
		&i.FactionRank,
		&i.PvpSource,
		&i.HasPvpStats,
		&i.PvpPenalty,
		&i.NoLongerAvailable,
		&i.TooltipImage,
		&i.TooltipSourceUrl,
		&i.Confidence,
		&i.SourceNote,
		&i.OpenQuestion,
	)
	return i, err
}

const getItemBySlug = `-- name: GetItemBySlug :one
SELECT i.item_id FROM items i WHERE i.slug = $1
`

func (q *Queries) GetItemBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, getItemBySlug, slug)
	var item_id int32
	err := row.Scan(&item_id)
	return item_id, err
}

const itemIDSpan = `-- name: ItemIDSpan :one
SELECT coalesce(min(item_id), 0)::integer AS min_id,
       coalesce(max(item_id), 0)::integer AS max_id,
       count(*)::bigint AS total
FROM items
`

type ItemIDSpanRow struct {
	MinID int32
	MaxID int32
	Total int64
}

// The honest empty state (AOC-047): "ids run 1–4692, N absent" is computed, never typed.
func (q *Queries) ItemIDSpan(ctx context.Context) (ItemIDSpanRow, error) {
	row := q.db.QueryRow(ctx, itemIDSpan)
	var i ItemIDSpanRow
	err := row.Scan(&i.MinID, &i.MaxID, &i.Total)
	return i, err
}

const listItemClasses = `-- name: ListItemClasses :many
SELECT cl.id, cl.slug, cl.name, cl.short_name
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = $1
ORDER BY cl.name
`

type ListItemClassesRow struct {
	ID        int32
	Slug      string
	Name      string
	ShortName *string
}

func (q *Queries) ListItemClasses(ctx context.Context, itemID int32) ([]ListItemClassesRow, error) {
	rows, err := q.db.Query(ctx, listItemClasses, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemClassesRow{}
	for rows.Next() {
		var i ListItemClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCosts = `-- name: ListItemCosts :many
SELECT ic.item_source_id, cu.slug AS currency, cu.name AS currency_name, ic.amount
FROM item_costs ic
JOIN currencies cu ON cu.id = ic.currency_id
WHERE ic.item_source_id = ANY($1::bigint[])
ORDER BY ic.item_source_id, cu.name
`

type ListItemCostsRow struct {
	ItemSourceID int64
	Currency     string
	CurrencyName string
	Amount       pgtype.Numeric
}

func (q *Queries) ListItemCosts(ctx context.Context, dollar_1 []int64) ([]ListItemCostsRow, error) {
	rows, err := q.db.Query(ctx, listItemCosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemCostsRow{}
	for rows.Next() {
		var i ListItemCostsRow
		if err := rows.Scan(
			&i.ItemSourceID,
			&i.Currency,
			&i.CurrencyName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemEquipLocations = `-- name: ListItemEquipLocations :many
SELECT el.id, el.slug, el.name
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = $1
ORDER BY el.id
`

func (q *Queries) ListItemEquipLocations(ctx context.Context, itemID int32) ([]EquipLocation, error) {
	rows, err := q.db.Query(ctx, listItemEquipLocations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquipLocation{}
	for rows.Next() {
		var i EquipLocation
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageClasses = `-- name: ListItemPageClasses :many
SELECT ic.item_id, cl.slug, cl.name, cl.short_name
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = ANY($1::integer[])
ORDER BY ic.item_id, cl.id
`

type ListItemPageClassesRow struct {
	ItemID    int32
	Slug      string
	Name      string
	ShortName *string
}

// A page's class restrictions in one round trip, with the short names the row shows (AOC-046).
func (q *Queries) ListItemPageClasses(ctx context.Context, itemIds []int32) ([]ListItemPageClassesRow, error) {
	rows, err := q.db.Query(ctx, listItemPageClasses, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageClassesRow{}
	for rows.Next() {
		var i ListItemPageClassesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageCosts = `-- name: ListItemPageCosts :many
SELECT src.item_id, src.id AS item_source_id, cu.name AS currency_name, ic.amount
FROM item_costs ic
JOIN item_sources src ON src.id = ic.item_source_id
JOIN currencies cu ON cu.id = ic.currency_id
WHERE src.item_id = ANY($1::integer[])
ORDER BY src.item_id, src.id, cu.name
`

type ListItemPageCostsRow struct {
	ItemID       int32
	ItemSourceID int64
	CurrencyName string
	Amount       pgtype.Numeric
}

// A page's vendor prices in one round trip: every cost of every source, grouped by the caller.
func (q *Queries) ListItemPageCosts(ctx context.Context, itemIds []int32) ([]ListItemPageCostsRow, error) {
	rows, err := q.db.Query(ctx, listItemPageCosts, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageCostsRow{}
	for rows.Next() {
		var i ListItemPageCostsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemSourceID,
			&i.CurrencyName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageEquipLocations = `-- name: ListItemPageEquipLocations :many
SELECT iel.item_id, el.slug, el.name
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = ANY($1::integer[])
ORDER BY iel.item_id, el.id
`

type ListItemPageEquipLocationsRow struct {
	ItemID int32
	Slug   string
	Name   string
}

// A page's slots in one round trip (AOC-047), the ListItemPlaces pattern: never one query per row.
func (q *Queries) ListItemPageEquipLocations(ctx context.Context, itemIds []int32) ([]ListItemPageEquipLocationsRow, error) {
	rows, err := q.db.Query(ctx, listItemPageEquipLocations, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageEquipLocationsRow{}
	for rows.Next() {
		var i ListItemPageEquipLocationsRow
		if err := rows.Scan(&i.ItemID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPlaces = `-- name: ListItemPlaces :many
SELECT src.item_id, p.slug AS place_slug, p.name AS place_name,
       -- coalesce, not a bare cast: min() over all-NULL is NULL, and sqlc types a cast as
       -- non-null, so the scan would fail on exactly the rows that have no region.
       coalesce(min(r.slug), '')::varchar AS region_slug,
       -- ⭐ ONE EXPRESSION PER FACT (AOC-039). The tier is blanked when the place's sources disagree,
       -- exactly like the boss below: min() would state one of two tiers as fact the first time the
       -- corpus held two. And unchained is the SAME expression the list filter and ListItemSources
       -- use -- src OR place, with a NULL place read as false -- so a row cannot be findable by
       -- unchained=true and then deny it on its own page.
       coalesce(CASE WHEN count(DISTINCT t.slug) = 1 THEN min(t.slug) END, '')::varchar AS tier_slug,
       bool_or(src.unchained OR coalesce(p.unchained, false)) AS unchained,
       -- The boss only when it is unambiguous: two bosses in one place would make either name a
       -- lie, and a blank is honest where a guess is not (CLAUDE.md STEP ZERO).
       coalesce(CASE WHEN count(DISTINCT b.name) = 1 THEN min(b.name) END, '')::varchar AS boss_name
FROM item_sources src
JOIN places p ON p.id = src.place_id
LEFT JOIN regions r ON r.id = coalesce(p.region_id, src.region_id)
LEFT JOIN tiers t ON t.id = src.tier_id
LEFT JOIN bosses b ON b.id = src.boss_id
WHERE src.item_id = ANY($1::integer[])
GROUP BY src.item_id, p.slug, p.name
ORDER BY p.name
`

type ListItemPlacesRow struct {
	ItemID     int32
	PlaceSlug  string
	PlaceName  string
	RegionSlug string
	TierSlug   string
	Unchained  bool
	BossName   string
}

// The per-item place context for a page of results, fetched in ONE round trip for the whole page
// rather than per row. Used two ways:
//   - an aggregate view (region/map/tier, or no place filter) renders these as "also drops in",
//     and the item still appears ONCE -- Pierre's rule, DECISIONS.md 2026-09-13;
//   - a view that named specific places expands to one row per item per NAMED place, because there
//     the duplication is the information.
//
// The choice is made server-side from the filters, never by a client flag.
// ⚠️ GROUPED BY PLACE, not by source row. An item can have several item_sources in ONE place --
// two bosses, or a boss and a container -- and without the grouping the same dungeon appeared
// twice next to the item, which made a two-dungeon selection render four rows instead of two.
// Measured on the real data before it was written. The unit of Pierre's rule is the PLACE.
// Every individual source, with its own boss, is still on the item page via ListItemSources.
func (q *Queries) ListItemPlaces(ctx context.Context, itemIds []int32) ([]ListItemPlacesRow, error) {
	rows, err := q.db.Query(ctx, listItemPlaces, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPlacesRow{}
	for rows.Next() {
		var i ListItemPlacesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.PlaceSlug,
			&i.PlaceName,
			&i.RegionSlug,
			&i.TierSlug,
			&i.Unchained,
			&i.BossName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSlugs = `-- name: ListItemSlugs :many
SELECT i.slug
FROM items i
ORDER BY i.item_id
LIMIT $2::int OFFSET $1::int
`

type ListItemSlugsParams struct {
	PageOffset int32
	PageSize   int32
}

// AOC-025: the sitemap's item URLs, one page of them. Ordered by the source site's own id, which
// never changes, so a chunk holds the same items from one crawl to the next.
func (q *Queries) ListItemSlugs(ctx context.Context, arg ListItemSlugsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemSlugs, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSources = `-- name: ListItemSources :many
SELECT src.id, src.item_id,
       at.slug AS acquisition_type, at.name AS acquisition_type_name,
       src.place_id, p.name AS place_name, p.slug AS place_slug,
       src.boss_id, bo.name AS boss_name,
       src.vendor_id, v.name AS vendor_name,
       src.quest_id, q.name AS quest_name,
       -- what the armory's quest column said: a giver, a hub or a bucket as often as a title, so
       -- the page shows it as listed and never calls it the quest's name (quests.name is NULL)
       q.armory_label AS quest_label,
       src.container_id, ct.name AS container_name,
       src.region_id, rg.name AS region_name, rg.slug AS region_slug,
       src.map_id, mp.name AS map_name, mp.slug AS map_slug,
       src.tier_id, tr.slug AS tier, tr.name AS tier_name,
       src.is_raid, src.coords, src.section_raw,
       -- ⭐ src OR place (AOC-039): the one unchained expression, shared with the list filter and
       -- ListItemPlaces. This was the bare src.unchained -- the third spelling of one rule, which
       -- agreed with the other two only because the importer set both columns from one source.
       (src.unchained OR coalesce(p.unchained, false))::boolean AS unchained,
       c.slug AS confidence, src.source_note, src.open_question
FROM item_sources src
JOIN confidence_levels c ON c.id = src.confidence_id
LEFT JOIN acquisition_types at ON at.id = src.acquisition_type_id
LEFT JOIN places p ON p.id = src.place_id
LEFT JOIN bosses bo ON bo.id = src.boss_id
LEFT JOIN vendors v ON v.id = src.vendor_id
LEFT JOIN quests q ON q.id = src.quest_id
LEFT JOIN containers ct ON ct.id = src.container_id
LEFT JOIN regions rg ON rg.id = coalesce(p.region_id, src.region_id)
LEFT JOIN maps mp ON mp.id = coalesce(p.map_id, src.map_id)
LEFT JOIN tiers tr ON tr.id = src.tier_id
WHERE src.item_id = $1
ORDER BY src.id
`

type ListItemSourcesRow struct {
	ID                  int64
	ItemID              int32
	AcquisitionType     *string
	AcquisitionTypeName *string
	PlaceID             *int32
	PlaceName           *string
	PlaceSlug           *string
	BossID              *int32
	BossName            *string
	VendorID            *int32
	VendorName          *string
	QuestID             *int32
	QuestName           *string
	QuestLabel          *string
	ContainerID         *int32
	ContainerName       *string
	RegionID            *int32
	RegionName          *string
	RegionSlug          *string
	MapID               *int32
	MapName             *string
	MapSlug             *string
	TierID              *int32
	Tier                *string
	TierName            *string
	IsRaid              bool
	Coords              *string
	SectionRaw          *string
	Unchained           bool
	Confidence          string
	SourceNote          string
	OpenQuestion        *string
}

// An item page's "where does this come from". 237 items have more than one place — 8 with two and
// 229 with three — so this is a list and never a single row.
// ⚠️ THE PLACE DECIDES, here too. AOC-012 verify round 1 settled that a source's place is the
// stronger fact than the source's own region, and it was written into ListItems and
// ListItemPlaces -- but NOT here, so the item page said Cimmeria for a place the list called
// Stygia. 196 rows across 98 items, region and map alike, and a reader got a different answer
// depending on which endpoint they landed on (verify round 4).
//
// A read decision has to name EVERY query that publishes the fact, not the ones in front of you.
func (q *Queries) ListItemSources(ctx context.Context, itemID int32) ([]ListItemSourcesRow, error) {
	rows, err := q.db.Query(ctx, listItemSources, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSourcesRow{}
	for rows.Next() {
		var i ListItemSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AcquisitionType,
			&i.AcquisitionTypeName,
			&i.PlaceID,
			&i.PlaceName,
			&i.PlaceSlug,
			&i.BossID,
			&i.BossName,
			&i.VendorID,
			&i.VendorName,
			&i.QuestID,
			&i.QuestName,
			&i.QuestLabel,
			&i.ContainerID,
			&i.ContainerName,
			&i.RegionID,
			&i.RegionName,
			&i.RegionSlug,
			&i.MapID,
			&i.MapName,
			&i.MapSlug,
			&i.TierID,
			&i.Tier,
			&i.TierName,
			&i.IsRaid,
			&i.Coords,
			&i.SectionRaw,
			&i.Unchained,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSpellEffects = `-- name: ListItemSpellEffects :many
SELECT se.item_id, se.stat, se.value, se.sign, se.unit, se.damage_type, se.pvp
FROM item_spell_effects se
WHERE se.item_id = $1
ORDER BY se.id
`

type ListItemSpellEffectsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

// Deliberately its own query against its own table. See the header. In the tooltip's order, like
// ListItemStats.
func (q *Queries) ListItemSpellEffects(ctx context.Context, itemID int32) ([]ListItemSpellEffectsRow, error) {
	rows, err := q.db.Query(ctx, listItemSpellEffects, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSpellEffectsRow{}
	for rows.Next() {
		var i ListItemSpellEffectsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStats = `-- name: ListItemStats :many
SELECT st.item_id, st.stat, st.value, st.sign, st.unit, st.damage_type, st.pvp
FROM item_stats st
WHERE st.item_id = $1
ORDER BY st.id
`

type ListItemStatsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

// In the TOOLTIP's order (AOC-048): the importer writes each item's stats in the order its tooltip
// prints them, so the id is that order — Dexterity before Combat Rating, as the game shows it.
// It was alphabetical until then, which no reader of a tooltip would recognise.
func (q *Queries) ListItemStats(ctx context.Context, itemID int32) ([]ListItemStatsRow, error) {
	rows, err := q.db.Query(ctx, listItemStats, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemStatsRow{}
	for rows.Next() {
		var i ListItemStatsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, r.sort_order AS rarity_sort, r.colour_token AS rarity_colour_token,
       it.slug AS item_type,
       sf.slug AS slot_fit,
       aw.slug AS armour_weight, aw.name AS armour_weight_name,
       i.item_level, i.requires_level, i.armor, i.dps,
       i.set_id, i.tooltip_image,
       c.slug AS confidence,
       count(*) OVER () AS total_count
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
WHERE ($1::varchar IS NULL OR r.slug = $1::varchar)
  AND ($2::varchar IS NULL OR it.slug = $2::varchar)
  -- ESCAPE, because a name query is free text from a URL: '%' alone matched every one of the
  -- 4,646 items and '_' matched any single character. The caller escapes the metacharacters
  -- (escapeLike); this names the escape character so Postgres honours them.
  -- q matches the name, or the item's id exactly when q is a whole number (AOC-047): the armory
  -- site's ids are what people still quote, and a name search for "2183" would otherwise find
  -- nothing. id_query is NULL unless q is numeric, and NULL never equals anything.
  AND ($3::varchar IS NULL
       OR i.name ILIKE '%' || $3::varchar || '%' ESCAPE '\'
       OR i.item_id = $4::integer)
  AND ($5::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_equip_locations iel
        JOIN equip_locations el ON el.id = iel.equip_location_id
        WHERE iel.item_id = i.item_id AND el.slug = $5::varchar))
  AND ($6::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_classes ic
        JOIN classes cl ON cl.id = ic.class_id
        WHERE ic.item_id = i.item_id AND cl.slug = $6::varchar))
  -- A LIST, not one slug. Selecting two dungeons is the case Pierre's rule is about, and a
  -- single-value parameter made the caller's second choice unrepresentable -- so the service
  -- passed NULL and the place predicate silently vanished, returning all 4,646 items
  -- (AOC-012 verify round 1).
  -- ⚠️ NULL means "no filter"; an EMPTY array does not -- ` + "`" + `p.slug = ANY('{}')` + "`" + ` is false for every
  -- row. The caller passes nil rather than an empty slice, and derives that from the same
  -- predicate that decides collapsing, so the two cannot disagree (verify round 2).
  AND ($7::varchar[] IS NULL OR EXISTS (
        SELECT 1 FROM item_sources src
        JOIN places p ON p.id = src.place_id
        WHERE src.item_id = i.item_id
          AND p.slug = ANY($7::varchar[])))
  AND ($8::varchar IS NULL OR EXISTS (
        SELECT 1 FROM armour_weights aw
        WHERE aw.id = i.armour_weight_id AND aw.slug = $8::varchar))
  -- region and tier live on item_sources, not on the item: an item is "in Kheshatta" because
  -- something that drops it is. Both are aggregate views, so they collapse (see ListItemPlaces).
  AND ($9::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_sources src
        LEFT JOIN places p ON p.id = src.place_id
        -- The PLACE's region wins. 196 item_sources rows disagree with their own place's region
        -- (AOC-037), and the place row is the stronger fact: it carries name, map and region
        -- together, with an invariant test behind it, while the per-source region is derived and
        -- has none. A source with no place still falls back to its own.
        LEFT JOIN regions r2 ON r2.id = coalesce(p.region_id, src.region_id)
        WHERE src.item_id = i.item_id AND r2.slug = $9::varchar))
  AND ($10::varchar IS NULL OR EXISTS (
        SELECT 1 FROM item_sources src
        JOIN tiers t ON t.id = src.tier_id
        WHERE src.item_id = i.item_id AND t.slug = $10::varchar))
  -- ⭐ unchained is true on EITHER the source row or the place it points at. The importer sets it
  -- on the source when the armory said so, and on the place when the place itself is the Unchained
  -- version -- so testing one alone silently loses the other half.
  AND ($11::boolean IS NULL OR EXISTS (
        SELECT 1 FROM item_sources src
        LEFT JOIN places p ON p.id = src.place_id
        WHERE src.item_id = i.item_id
          AND (src.unchained OR coalesce(p.unchained, false)) = $11::boolean))
  -- pvp is three independent facts on the item, and "pvp=true" means any of them. Collapsing them
  -- into one column would lose which one is true, which the item page shows separately.
  AND ($12::boolean IS NULL
       OR (i.pvp_source OR i.has_pvp_stats OR i.pvp_penalty) = $12::boolean)
ORDER BY
  CASE WHEN $13::varchar = 'ilvl' THEN i.item_level END DESC NULLS LAST,
  CASE WHEN $13::varchar = 'id' THEN i.item_id END ASC,
  i.name, i.item_id
LIMIT $15::integer OFFSET $14::integer
`

type ListItemsParams struct {
	Rarity        *string
	ItemType      *string
	NameQuery     *string
	IDQuery       *int32
	EquipLocation *string
	Class         *string
	PlaceSlugs    []string
	ArmourWeight  *string
	Region        *string
	Tier          *string
	Unchained     *bool
	Pvp           *bool
	SortBy        string
	PageOffset    int32
	PageSize      int32
}

type ListItemsRow struct {
	ItemID            int32
	Slug              string
	Name              string
	Rarity            string
	RaritySort        int32
	RarityColourToken *string
	ItemType          *string
	SlotFit           *string
	ArmourWeight      *string
	ArmourWeightName  *string
	ItemLevel         *int32
	RequiresLevel     *int32
	Armor             *int32
	Dps               pgtype.Numeric
	SetID             *int32
	TooltipImage      *string
	Confidence        string
	TotalCount        int64
}

// The Armory list page. Every filter is optional: a NULL argument means "do not filter on this",
// which keeps one query behind every combination the page offers rather than building SQL by hand.
//
// ⭐ The equip-location filter goes through the join (EXISTS), so asking for 'off-hand' returns
// the 390 two-handers as well as the 141 off-hand-only items — 531, not 141. That is the
// acceptance criterion this whole schema shape exists for, and
// TestListItemsFindsTwoHandersWhenAskedForOffHand exercises THIS query, not a copy of it.
// ⭐ ONE query, three orders (AOC-047). A CASE per sort key keeps every filter above in one
// place; the keys are code ('name', 'ilvl', 'id' — not a game concept), validated before they
// get here. ilvl is DESCENDING with NULLs LAST, so the 50 items with no recorded level end the
// list rather than vanish or lead it; the name and id tie-breakers make every page stable.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.Rarity,
		arg.ItemType,
		arg.NameQuery,
		arg.IDQuery,
		arg.EquipLocation,
		arg.Class,
		arg.PlaceSlugs,
		arg.ArmourWeight,
		arg.Region,
		arg.Tier,
		arg.Unchained,
		arg.Pvp,
		arg.SortBy,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.RarityColourToken,
			&i.ItemType,
			&i.SlotFit,
			&i.ArmourWeight,
			&i.ArmourWeightName,
			&i.ItemLevel,
			&i.RequiresLevel,
			&i.Armor,
			&i.Dps,
			&i.SetID,
			&i.TooltipImage,
			&i.Confidence,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCurrency = `-- name: ListItemsByCurrency :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, it.slug AS item_type,
       ic.amount, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN item_costs ic ON ic.item_source_id = src.id
JOIN currencies cu ON cu.id = ic.currency_id
WHERE cu.slug = $1
ORDER BY ic.amount, i.name
`

type ListItemsByCurrencyRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	ItemType     *string
	Amount       pgtype.Numeric
	TooltipImage *string
}

// A currency page: "what does this token buy?" (DECISIONS.md 2026-09-14 — currency is an entity
// with its own page, so the fact is stated once instead of on every item bought with it).
func (q *Queries) ListItemsByCurrency(ctx context.Context, slug string) ([]ListItemsByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, listItemsByCurrency, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByCurrencyRow{}
	for rows.Next() {
		var i ListItemsByCurrencyRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.ItemType,
			&i.Amount,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByPlace = `-- name: ListItemsByPlace :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, r.sort_order AS rarity_sort,
       it.slug AS item_type, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN places p ON p.id = src.place_id
WHERE p.slug = $1
ORDER BY r.sort_order DESC, i.name
`

type ListItemsByPlaceRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	RaritySort   int32
	ItemType     *string
	TooltipImage *string
}

// The reverse lookup, and the one Pierre asked for first: "what drops here?" on a place page.
func (q *Queries) ListItemsByPlace(ctx context.Context, slug string) ([]ListItemsByPlaceRow, error) {
	rows, err := q.db.Query(ctx, listItemsByPlace, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByPlaceRow{}
	for rows.Next() {
		var i ListItemsByPlaceRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.ItemType,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenItemQuestions = `-- name: ListOpenItemQuestions :many
SELECT 'item' AS kind, i.item_id AS id, i.name, i.open_question
FROM items i WHERE i.open_question IS NOT NULL
UNION ALL
SELECT 'item_source', src.item_id, i.name, src.open_question
FROM item_sources src JOIN items i ON i.item_id = src.item_id
WHERE src.open_question IS NOT NULL
UNION ALL
SELECT 'set', s.id, s.name, s.open_question
FROM sets s WHERE s.open_question IS NOT NULL
ORDER BY kind, name
`

type ListOpenItemQuestionsRow struct {
	Kind         string
	ID           int32
	Name         string
	OpenQuestion *string
}

// The counterpart of AOC-009's ListOpenQuestions: everything the item data could not answer,
// in one read, so "what do we still need to ask Pierre" stays a query and not a memory.
func (q *Queries) ListOpenItemQuestions(ctx context.Context) ([]ListOpenItemQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenItemQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenItemQuestionsRow{}
	for rows.Next() {
		var i ListOpenItemQuestionsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetPieces = `-- name: ListSetPieces :many
SELECT i.item_id, i.slug, i.name, r.colour_token AS rarity_colour_token
FROM items i
JOIN rarities r ON r.id = i.rarity_id
WHERE i.set_id = $1
ORDER BY i.name, i.item_id
`

type ListSetPiecesRow struct {
	ItemID            int32
	Slug              string
	Name              string
	RarityColourToken *string
}

// AOC-048: every piece of one set, for the item page and /v1's set_pieces. Bounded by the data's
// own shape — the largest set holds 16 (measured 2026-09-30) — so it is part of one item's detail,
// not a list endpoint.
func (q *Queries) ListSetPieces(ctx context.Context, setID *int32) ([]ListSetPiecesRow, error) {
	rows, err := q.db.Query(ctx, listSetPieces, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetPiecesRow{}
	for rows.Next() {
		var i ListSetPiecesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.RarityColourToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT s.id, s.slug, s.name, cl.slug AS class, aw.slug AS set_armour_weight,
       c.slug AS confidence, s.source_note, s.open_question,
       s.declared_piece_count,
       (SELECT count(*) FROM items i WHERE i.set_id = s.id) AS pieces_held
FROM sets s
JOIN confidence_levels c ON c.id = s.confidence_id
LEFT JOIN classes cl ON cl.id = s.class_id
LEFT JOIN armour_weights aw ON aw.id = s.set_armour_weight_id
ORDER BY s.name
`

type ListSetsRow struct {
	ID                 int32
	Slug               string
	Name               string
	Class              *string
	SetArmourWeight    *string
	Confidence         string
	SourceNote         string
	OpenQuestion       *string
	DeclaredPieceCount *int32
	PiecesHeld         int64
}

func (q *Queries) ListSets(ctx context.Context) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetsRow{}
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Class,
			&i.SetArmourWeight,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
			&i.DeclaredPieceCount,
			&i.PiecesHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
