// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItemFacets = `-- name: CountItemFacets :many
WITH filtered AS MATERIALIZED (
  SELECT i.item_id, i.rarity_id, i.armour_weight_id, i.set_id, i.item_level, i.requires_level,
         pr.priced,
         -- The filters that have no facet of their own, as ONE flag.
         coalesce(
           ($1::varchar IS NULL OR it.slug = $1::varchar)
           -- ESCAPE, because a name query is free text from a URL: '%' alone matched every one of the
           -- 4,646 items and '_' matched any single character. The caller escapes the metacharacters
           -- (escapeLike); this names the escape character so Postgres honours them.
           -- q matches the name, or the item's id exactly when q is a whole number (AOC-047): the
           -- armory site's ids are what people still quote, and a name search for "2183" would
           -- otherwise find nothing. id_query is NULL unless q is numeric.
           AND ($2::varchar IS NULL
                OR i.name ILIKE '%' || $2::varchar || '%' ESCAPE '\'
                OR i.item_id = $3::integer)
           -- A LIST, not one slug. Selecting two dungeons is the case Pierre's rule is about, and a
           -- single-value parameter made the caller's second choice unrepresentable -- so the
           -- service passed NULL and the place predicate silently vanished, returning all 4,646
           -- items (AOC-012 verify round 1).
           -- ⚠️ NULL means "no filter"; an EMPTY array does not -- ` + "`" + `p.slug = ANY('{}')` + "`" + ` is false for
           -- every row. The caller passes nil rather than an empty slice, and derives that from the
           -- same predicate that decides collapsing, so the two cannot disagree (verify round 2).
           AND ($4::varchar[] IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND p.slug = ANY($4::varchar[])))
           -- region and tier live on item_sources, not on the item: an item is "in Kheshatta"
           -- because something that drops it is. Both are aggregate views, so they collapse.
           AND ($5::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 -- The PLACE's region wins. 196 item_sources rows disagree with their own place's
                 -- region (AOC-037), and the place row is the stronger fact: it carries name, map
                 -- and region together, with an invariant test behind it, while the per-source
                 -- region is derived and has none. A source with no place falls back to its own.
                 LEFT JOIN regions r2 ON r2.id = coalesce(p.region_id, src.region_id)
                 WHERE src.item_id = i.item_id AND r2.slug = $5::varchar))
           AND ($6::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN tiers t ON t.id = src.tier_id
                 WHERE src.item_id = i.item_id AND t.slug = $6::varchar))
           -- ⭐ unchained is true on EITHER the source row or the place it points at (AOC-039: the
           -- one expression, shared with ListItemSources and ListItemPlaces).
           AND ($7::boolean IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND (src.unchained OR coalesce(p.unchained, false)) = $7::boolean))
           -- pvp is three independent facts on the item, and "pvp=true" means any of them.
           AND ($8::boolean IS NULL
                OR (i.pvp_source OR i.has_pvp_stats OR i.pvp_penalty) = $8::boolean)
           -- ⭐ A SOURCE is ONE item_sources row (AOC-050): its tab's section, its region, map, place,
           -- boss, vendor, quest giver, container and acquisition group TOGETHER. tier= and place=
           -- above may each match a different row of the same item; a node of the source tree may
           -- not, or a tier's raid would count an item that is in the tier only somewhere else.
           -- source_tab is NULL unless a node is picked: a tab on its own filters nothing (Pierre,
           -- 2026-10-02). Region and map are the PLACE's when it has one, as everywhere (AOC-037).
           AND ($9::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN sections sc ON sc.id = src.section_id
                 JOIN source_tabs stb ON stb.id = sc.tab_id
                 LEFT JOIN places p ON p.id = src.place_id
                 LEFT JOIN regions sr ON sr.id = coalesce(p.region_id, src.region_id)
                 LEFT JOIN maps sm ON sm.id = coalesce(p.map_id, src.map_id)
                 LEFT JOIN bosses sb ON sb.id = src.boss_id
                 LEFT JOIN vendors sv ON sv.id = src.vendor_id
                 LEFT JOIN quests sq ON sq.id = src.quest_id
                 LEFT JOIN containers sct ON sct.id = src.container_id
                 LEFT JOIN acquisition_types sat ON sat.id = src.acquisition_type_id
                 LEFT JOIN acquisition_groups sag ON sag.id = sat.group_id
                 WHERE src.item_id = i.item_id
                   AND stb.slug = $9::varchar
                   AND ($10::varchar IS NULL OR sc.slug = $10::varchar)
                   -- '-' is "the row has no such level" (AOC-050 verify round 1, F1): a branch the
                   -- panel draws with that level skipped holds only the rows that lack it.
                   AND ($11::varchar IS NULL OR CASE WHEN $11::varchar = '-' THEN sr.id IS NULL ELSE sr.slug = $11::varchar END)
                   AND ($12::varchar IS NULL OR CASE WHEN $12::varchar = '-' THEN sm.id IS NULL ELSE sm.slug = $12::varchar END)
                   -- The places the service resolved: a place and every place inside it (AOC-038),
                   -- the place alone when a boss, vendor, quest giver or container follows it, or
                   -- '{-}' for no place at all.
                   AND ($13::varchar[] IS NULL OR CASE WHEN $13::varchar[] = ARRAY['-']::varchar[] THEN p.id IS NULL ELSE p.slug = ANY($13::varchar[]) END)
                   AND ($14::varchar IS NULL OR sb.slug = $14::varchar)
                   AND ($15::varchar IS NULL OR sv.slug = $15::varchar)
                   AND ($16::varchar IS NULL OR sq.slug = $16::varchar)
                   AND ($17::varchar IS NULL OR sct.slug = $17::varchar)
                   AND ($18::varchar IS NULL OR sag.slug = $18::varchar))),
           false) AS in_base,
         -- One flag per facet (AOC-049). Each is the whole of that filter's rule. A facet takes a LIST
         -- (AOC-064): any of its values, as ` + "`" + `place` + "`" + ` always has; NULL is no filter, never '{}'.
         ($19::varchar[] IS NULL OR r.slug = ANY($19::varchar[])) AS in_rarity,
         -- ⭐ The slot goes through the join, so 'off-hand' finds the 389 one-handers (they fit either
         -- hand) as well as the 141 off-hand-only items -- 530, not 141 (AOC-058).
         ($20::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_equip_locations iel
           JOIN equip_locations el ON el.id = iel.equip_location_id
           WHERE iel.item_id = i.item_id AND el.slug = ANY($20::varchar[]))) AS in_slot,
         coalesce($21::varchar[] IS NULL OR aw.slug = ANY($21::varchar[]), false) AS in_weight,
         ($22::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_classes ic
           JOIN classes cl ON cl.id = ic.class_id
           WHERE ic.item_id = i.item_id AND cl.slug = ANY($22::varchar[]))) AS in_class,
         -- A bound excludes an item with no level: it cannot be shown to be inside the range.
         coalesce(($23::integer IS NULL OR i.item_level >= $23::integer)
              AND ($24::integer IS NULL OR i.item_level <= $24::integer), false) AS in_ilvl,
         coalesce(($25::integer IS NULL OR i.requires_level >= $25::integer)
              AND ($26::integer IS NULL OR i.requires_level <= $26::integer), false) AS in_reqlvl,
         -- "Has a vendor price" matches ANY occurrence: the list shows items, not occurrences, and an
         -- item free from a boss and sold by a vendor (689 of them) has a price.
         ($27::boolean IS NULL OR pr.priced = $27::boolean) AS in_price,
         ($28::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_sources src
           JOIN item_costs ico ON ico.item_source_id = src.id
           JOIN currencies cu ON cu.id = ico.currency_id
           WHERE src.item_id = i.item_id AND cu.slug = ANY($28::varchar[]))) AS in_currency,
         coalesce($29::varchar[] IS NULL OR st.slug = ANY($29::varchar[]), false) AS in_set
  FROM items i
  JOIN rarities r ON r.id = i.rarity_id
  LEFT JOIN item_types it ON it.id = i.item_type_id
  LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
  LEFT JOIN sets st ON st.id = i.set_id
  -- One expression for "has a vendor price", read by in_price and by the price facet. A subquery
  -- with no FROM is pulled up into its references, so a query that reads neither never runs it.
  CROSS JOIN LATERAL (SELECT EXISTS (
    SELECT 1 FROM item_sources src
    JOIN item_costs ico ON ico.item_source_id = src.id
    WHERE src.item_id = i.item_id) AS priced) pr
)
SELECT 'rarity'::varchar AS facet, r.slug, r.name, ''::varchar AS short_name,
       coalesce(r.colour_token, '')::varchar AS colour_token,
       row_number() OVER (ORDER BY r.sort_order DESC) AS ord,
       count(DISTINCT f.item_id) AS items
FROM rarities r
LEFT JOIN filtered f ON f.rarity_id = r.id AND f.in_base AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set
GROUP BY r.id
UNION ALL
SELECT 'equip_location', el.slug, el.name, '', '',
       row_number() OVER (ORDER BY el.id),
       count(DISTINCT f.item_id)
FROM equip_locations el
LEFT JOIN item_equip_locations iel ON iel.equip_location_id = el.id
LEFT JOIN filtered f ON f.item_id = iel.item_id AND f.in_base AND f.in_rarity AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set
GROUP BY el.id
UNION ALL
SELECT 'armour_weight', aw.slug, aw.name, '', '',
       row_number() OVER (ORDER BY aw.sort_order DESC),
       count(DISTINCT f.item_id)
FROM armour_weights aw
LEFT JOIN filtered f ON f.armour_weight_id = aw.id AND f.in_base AND f.in_rarity AND f.in_slot AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set
GROUP BY aw.id
UNION ALL
SELECT 'class', cl.slug, cl.name, coalesce(cl.short_name, ''), '',
       row_number() OVER (ORDER BY cl.sort_order NULLS LAST, cl.name),
       count(DISTINCT f.item_id)
FROM classes cl
LEFT JOIN item_classes ic ON ic.class_id = cl.id
LEFT JOIN filtered f ON f.item_id = ic.item_id AND f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set
GROUP BY cl.id
UNION ALL
SELECT 'currency', cu.slug, cu.name, '', '',
       row_number() OVER (ORDER BY cu.name),
       count(DISTINCT f.item_id)
FROM currencies cu
LEFT JOIN item_costs ico ON ico.currency_id = cu.id
LEFT JOIN item_sources src ON src.id = ico.item_source_id
LEFT JOIN filtered f ON f.item_id = src.item_id AND f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_set
GROUP BY cu.id
UNION ALL
SELECT 'set', st.slug, st.name, '', '',
       row_number() OVER (ORDER BY st.name, st.id),
       count(DISTINCT f.item_id)
FROM sets st
LEFT JOIN filtered f ON f.set_id = st.id AND f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency
GROUP BY st.id
ORDER BY facet, ord
`

type CountItemFacetsParams struct {
	ItemType        *string
	NameQuery       *string
	IDQuery         *int32
	PlaceSlugs      []string
	Region          *string
	Tier            *string
	Unchained       *bool
	Pvp             *bool
	SourceTab       *string
	SourceSection   *string
	SourceRegion    *string
	SourceMap       *string
	SourcePlaces    []string
	SourceBoss      *string
	SourceVendor    *string
	SourceQuest     *string
	SourceContainer *string
	SourceGroup     *string
	Rarities        []string
	EquipLocations  []string
	ArmourWeights   []string
	Classes         []string
	IlvlMin         *int32
	IlvlMax         *int32
	ReqlvlMin       *int32
	ReqlvlMax       *int32
	Price           *bool
	Currencies      []string
	Sets            []string
}

type CountItemFacetsRow struct {
	Facet       string
	Slug        string
	Name        string
	ShortName   string
	ColourToken string
	Ord         int64
	Items       int64
}

// The rail's counts (AOC-049): EVERY value of each facet's vocabulary, with how many items picking
// it would leave under the other filters -- 0 included, because a value that is hidden teaches
// nothing and a greyed 0 says why. The values come from their lookup tables, never from Go
// (reference/content-model.md § 0). count(DISTINCT): an item bought with one currency from two
// vendors is one item, as it is one row of the list. `ord` is the order the rail shows them in.
func (q *Queries) CountItemFacets(ctx context.Context, arg CountItemFacetsParams) ([]CountItemFacetsRow, error) {
	rows, err := q.db.Query(ctx, countItemFacets,
		arg.ItemType,
		arg.NameQuery,
		arg.IDQuery,
		arg.PlaceSlugs,
		arg.Region,
		arg.Tier,
		arg.Unchained,
		arg.Pvp,
		arg.SourceTab,
		arg.SourceSection,
		arg.SourceRegion,
		arg.SourceMap,
		arg.SourcePlaces,
		arg.SourceBoss,
		arg.SourceVendor,
		arg.SourceQuest,
		arg.SourceContainer,
		arg.SourceGroup,
		arg.Rarities,
		arg.EquipLocations,
		arg.ArmourWeights,
		arg.Classes,
		arg.IlvlMin,
		arg.IlvlMax,
		arg.ReqlvlMin,
		arg.ReqlvlMax,
		arg.Price,
		arg.Currencies,
		arg.Sets,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountItemFacetsRow{}
	for rows.Next() {
		var i CountItemFacetsRow
		if err := rows.Scan(
			&i.Facet,
			&i.Slug,
			&i.Name,
			&i.ShortName,
			&i.ColourToken,
			&i.Ord,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expandPlaces = `-- name: ExpandPlaces :many
WITH RECURSIVE inside AS (
    SELECT p.slug AS named, p.id, p.slug
    FROM places p
    WHERE p.slug = ANY($1::varchar[])
  UNION
    SELECT inside.named, c.id, c.slug
    FROM places c JOIN inside ON c.parent_place_id = inside.id
)
SELECT inside.named::varchar AS named, inside.slug::varchar AS slug
FROM inside
ORDER BY inside.named, inside.slug
`

type ExpandPlacesRow struct {
	Named string
	Slug  string
}

// A place that CONTAINS places (AOC-038): House of Crom's loot is recorded against its two wings,
// Warmonk Monastery's against its three, so the place itself holds almost none of it. Asking for the
// place means everything in it (Pierre, 2026-09-29, DECISIONS.md), so the service hands SQL the named
// places AND every place under them, at any depth, and reads off whether anything named contained
// something. One row per (named, place inside it), the named place included as its own row.
// UNION, not UNION ALL: a cycle in parent_place_id would repeat a row, and UNION stops there.
func (q *Queries) ExpandPlaces(ctx context.Context, slugs []string) ([]ExpandPlacesRow, error) {
	rows, err := q.db.Query(ctx, expandPlaces, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpandPlacesRow{}
	for rows.Next() {
		var i ExpandPlacesRow
		if err := rows.Scan(&i.Named, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one

SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, it.slug AS item_type,
       sf.slug AS slot_fit,
       aw.slug AS armour_weight, b.slug AS binding,
       -- the display names and the rarity's colour, for the item PAGE (AOC-048); /v1 keeps the slugs
       r.name AS rarity_name, r.colour_token AS rarity_colour_token, it.name AS item_type_name,
       aw.name AS armour_weight_name, b.name AS binding_name,
       i.item_level, i.requires_level, i.armor, i.critigation, i.dps, i.damage_range,
       i.set_id, s.name AS set_name, s.declared_piece_count,
       f.slug AS faction, i.faction_rank,
       i.pvp_source, i.has_pvp_stats, i.pvp_penalty, i.no_longer_available,
       i.tooltip_image, i.tooltip_source_url,
       c.slug AS confidence, i.source_note, i.open_question
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
LEFT JOIN bindings b ON b.id = i.binding_id
LEFT JOIN sets s ON s.id = i.set_id
LEFT JOIN factions f ON f.id = i.faction_id
WHERE i.item_id = $1
`

type GetItemRow struct {
	ItemID             int32
	Slug               string
	Name               string
	Rarity             string
	ItemType           *string
	SlotFit            *string
	ArmourWeight       *string
	Binding            *string
	RarityName         string
	RarityColourToken  *string
	ItemTypeName       *string
	ArmourWeightName   *string
	BindingName        *string
	ItemLevel          *int32
	RequiresLevel      *int32
	Armor              *int32
	Critigation        *int32
	Dps                pgtype.Numeric
	DamageRange        *string
	SetID              *int32
	SetName            *string
	DeclaredPieceCount *int32
	Faction            *string
	FactionRank        *int32
	PvpSource          bool
	HasPvpStats        bool
	PvpPenalty         bool
	NoLongerAvailable  *string
	TooltipImage       *string
	TooltipSourceUrl   *string
	Confidence         string
	SourceNote         string
	OpenQuestion       *string
}

// Read queries for the Armory (AOC-010). The write side belongs to the importer (AOC-011) and the
// public endpoints to AOC-012; what is here is the shape both of them read through.
//
// ⭐ EQUIP LOCATION IS A JOIN. `ListItems` filters slots through item_equip_locations, never
// through a column on items, because 389 one-handed weapons fit EITHER hand and 187 rings EITHER
// finger (AOC-058: the first were read as "two-handers occupying both" until Pierre said otherwise).
// A query that filtered a single column would silently drop the 389 —
// the reason the join exists at all (see the migration header).
//
// ⚠️ Every read returns confidence and open_question with the row, like places.sql. A page that
// cannot show how sure we are cannot honour sourcing-standards § 3, and dropping them from the
// SELECT is how that rule quietly stops being enforced.
//
// ⚠️ Stats and spell effects are returned by SEPARATE queries from separate tables. Nothing here
// unions them, so nothing downstream can sum a mount's -8% Sprinting Stamina Drain into a build.
func (q *Queries) GetItem(ctx context.Context, itemID int32) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, itemID)
	var i GetItemRow
	err := row.Scan(
		&i.ItemID,
		&i.Slug,
		&i.Name,
		&i.Rarity,
		&i.ItemType,
		&i.SlotFit,
		&i.ArmourWeight,
		&i.Binding,
		&i.RarityName,
		&i.RarityColourToken,
		&i.ItemTypeName,
		&i.ArmourWeightName,
		&i.BindingName,
		&i.ItemLevel,
		&i.RequiresLevel,
		&i.Armor,
		&i.Critigation,
		&i.Dps,
		&i.DamageRange,
		&i.SetID,
		&i.SetName,
		&i.DeclaredPieceCount,
		&i.Faction,
		&i.FactionRank,
		&i.PvpSource,
		&i.HasPvpStats,
		&i.PvpPenalty,
		&i.NoLongerAvailable,
		&i.TooltipImage,
		&i.TooltipSourceUrl,
		&i.Confidence,
		&i.SourceNote,
		&i.OpenQuestion,
	)
	return i, err
}

const getItemBySlug = `-- name: GetItemBySlug :one
SELECT i.item_id FROM items i WHERE i.slug = $1
`

func (q *Queries) GetItemBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, getItemBySlug, slug)
	var item_id int32
	err := row.Scan(&item_id)
	return item_id, err
}

const itemFacetTotals = `-- name: ItemFacetTotals :one
WITH filtered AS MATERIALIZED (
  SELECT i.item_id, i.rarity_id, i.armour_weight_id, i.set_id, i.item_level, i.requires_level,
         pr.priced,
         -- The filters that have no facet of their own, as ONE flag.
         coalesce(
           ($1::varchar IS NULL OR it.slug = $1::varchar)
           -- ESCAPE, because a name query is free text from a URL: '%' alone matched every one of the
           -- 4,646 items and '_' matched any single character. The caller escapes the metacharacters
           -- (escapeLike); this names the escape character so Postgres honours them.
           -- q matches the name, or the item's id exactly when q is a whole number (AOC-047): the
           -- armory site's ids are what people still quote, and a name search for "2183" would
           -- otherwise find nothing. id_query is NULL unless q is numeric.
           AND ($2::varchar IS NULL
                OR i.name ILIKE '%' || $2::varchar || '%' ESCAPE '\'
                OR i.item_id = $3::integer)
           -- A LIST, not one slug. Selecting two dungeons is the case Pierre's rule is about, and a
           -- single-value parameter made the caller's second choice unrepresentable -- so the
           -- service passed NULL and the place predicate silently vanished, returning all 4,646
           -- items (AOC-012 verify round 1).
           -- ⚠️ NULL means "no filter"; an EMPTY array does not -- ` + "`" + `p.slug = ANY('{}')` + "`" + ` is false for
           -- every row. The caller passes nil rather than an empty slice, and derives that from the
           -- same predicate that decides collapsing, so the two cannot disagree (verify round 2).
           AND ($4::varchar[] IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND p.slug = ANY($4::varchar[])))
           -- region and tier live on item_sources, not on the item: an item is "in Kheshatta"
           -- because something that drops it is. Both are aggregate views, so they collapse.
           AND ($5::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 -- The PLACE's region wins. 196 item_sources rows disagree with their own place's
                 -- region (AOC-037), and the place row is the stronger fact: it carries name, map
                 -- and region together, with an invariant test behind it, while the per-source
                 -- region is derived and has none. A source with no place falls back to its own.
                 LEFT JOIN regions r2 ON r2.id = coalesce(p.region_id, src.region_id)
                 WHERE src.item_id = i.item_id AND r2.slug = $5::varchar))
           AND ($6::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN tiers t ON t.id = src.tier_id
                 WHERE src.item_id = i.item_id AND t.slug = $6::varchar))
           -- ⭐ unchained is true on EITHER the source row or the place it points at (AOC-039: the
           -- one expression, shared with ListItemSources and ListItemPlaces).
           AND ($7::boolean IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND (src.unchained OR coalesce(p.unchained, false)) = $7::boolean))
           -- pvp is three independent facts on the item, and "pvp=true" means any of them.
           AND ($8::boolean IS NULL
                OR (i.pvp_source OR i.has_pvp_stats OR i.pvp_penalty) = $8::boolean)
           -- ⭐ A SOURCE is ONE item_sources row (AOC-050): its tab's section, its region, map, place,
           -- boss, vendor, quest giver, container and acquisition group TOGETHER. tier= and place=
           -- above may each match a different row of the same item; a node of the source tree may
           -- not, or a tier's raid would count an item that is in the tier only somewhere else.
           -- source_tab is NULL unless a node is picked: a tab on its own filters nothing (Pierre,
           -- 2026-10-02). Region and map are the PLACE's when it has one, as everywhere (AOC-037).
           AND ($9::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN sections sc ON sc.id = src.section_id
                 JOIN source_tabs stb ON stb.id = sc.tab_id
                 LEFT JOIN places p ON p.id = src.place_id
                 LEFT JOIN regions sr ON sr.id = coalesce(p.region_id, src.region_id)
                 LEFT JOIN maps sm ON sm.id = coalesce(p.map_id, src.map_id)
                 LEFT JOIN bosses sb ON sb.id = src.boss_id
                 LEFT JOIN vendors sv ON sv.id = src.vendor_id
                 LEFT JOIN quests sq ON sq.id = src.quest_id
                 LEFT JOIN containers sct ON sct.id = src.container_id
                 LEFT JOIN acquisition_types sat ON sat.id = src.acquisition_type_id
                 LEFT JOIN acquisition_groups sag ON sag.id = sat.group_id
                 WHERE src.item_id = i.item_id
                   AND stb.slug = $9::varchar
                   AND ($10::varchar IS NULL OR sc.slug = $10::varchar)
                   -- '-' is "the row has no such level" (AOC-050 verify round 1, F1): a branch the
                   -- panel draws with that level skipped holds only the rows that lack it.
                   AND ($11::varchar IS NULL OR CASE WHEN $11::varchar = '-' THEN sr.id IS NULL ELSE sr.slug = $11::varchar END)
                   AND ($12::varchar IS NULL OR CASE WHEN $12::varchar = '-' THEN sm.id IS NULL ELSE sm.slug = $12::varchar END)
                   -- The places the service resolved: a place and every place inside it (AOC-038),
                   -- the place alone when a boss, vendor, quest giver or container follows it, or
                   -- '{-}' for no place at all.
                   AND ($13::varchar[] IS NULL OR CASE WHEN $13::varchar[] = ARRAY['-']::varchar[] THEN p.id IS NULL ELSE p.slug = ANY($13::varchar[]) END)
                   AND ($14::varchar IS NULL OR sb.slug = $14::varchar)
                   AND ($15::varchar IS NULL OR sv.slug = $15::varchar)
                   AND ($16::varchar IS NULL OR sq.slug = $16::varchar)
                   AND ($17::varchar IS NULL OR sct.slug = $17::varchar)
                   AND ($18::varchar IS NULL OR sag.slug = $18::varchar))),
           false) AS in_base,
         -- One flag per facet (AOC-049). Each is the whole of that filter's rule. A facet takes a LIST
         -- (AOC-064): any of its values, as ` + "`" + `place` + "`" + ` always has; NULL is no filter, never '{}'.
         ($19::varchar[] IS NULL OR r.slug = ANY($19::varchar[])) AS in_rarity,
         -- ⭐ The slot goes through the join, so 'off-hand' finds the 389 one-handers (they fit either
         -- hand) as well as the 141 off-hand-only items -- 530, not 141 (AOC-058).
         ($20::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_equip_locations iel
           JOIN equip_locations el ON el.id = iel.equip_location_id
           WHERE iel.item_id = i.item_id AND el.slug = ANY($20::varchar[]))) AS in_slot,
         coalesce($21::varchar[] IS NULL OR aw.slug = ANY($21::varchar[]), false) AS in_weight,
         ($22::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_classes ic
           JOIN classes cl ON cl.id = ic.class_id
           WHERE ic.item_id = i.item_id AND cl.slug = ANY($22::varchar[]))) AS in_class,
         -- A bound excludes an item with no level: it cannot be shown to be inside the range.
         coalesce(($23::integer IS NULL OR i.item_level >= $23::integer)
              AND ($24::integer IS NULL OR i.item_level <= $24::integer), false) AS in_ilvl,
         coalesce(($25::integer IS NULL OR i.requires_level >= $25::integer)
              AND ($26::integer IS NULL OR i.requires_level <= $26::integer), false) AS in_reqlvl,
         -- "Has a vendor price" matches ANY occurrence: the list shows items, not occurrences, and an
         -- item free from a boss and sold by a vendor (689 of them) has a price.
         ($27::boolean IS NULL OR pr.priced = $27::boolean) AS in_price,
         ($28::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_sources src
           JOIN item_costs ico ON ico.item_source_id = src.id
           JOIN currencies cu ON cu.id = ico.currency_id
           WHERE src.item_id = i.item_id AND cu.slug = ANY($28::varchar[]))) AS in_currency,
         coalesce($29::varchar[] IS NULL OR st.slug = ANY($29::varchar[]), false) AS in_set
  FROM items i
  JOIN rarities r ON r.id = i.rarity_id
  LEFT JOIN item_types it ON it.id = i.item_type_id
  LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
  LEFT JOIN sets st ON st.id = i.set_id
  -- One expression for "has a vendor price", read by in_price and by the price facet. A subquery
  -- with no FROM is pulled up into its references, so a query that reads neither never runs it.
  CROSS JOIN LATERAL (SELECT EXISTS (
    SELECT 1 FROM item_sources src
    JOIN item_costs ico ON ico.item_source_id = src.id
    WHERE src.item_id = i.item_id) AS priced) pr
)
SELECT
  count(*) FILTER (WHERE f.in_base AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set) AS any_rarity,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set) AS any_equip_location,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set) AS any_armour_weight,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set) AS any_class,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_set) AS any_currency,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency) AS any_set,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_currency AND f.in_set) AS any_price,
  count(*) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_currency AND f.in_set AND f.priced) AS priced,
  count(f.item_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set) AS ilvl_n,
  coalesce(min(f.item_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set), 0)::integer AS ilvl_lo,
  coalesce(max(f.item_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set), 0)::integer AS ilvl_hi,
  count(f.requires_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_price AND f.in_currency AND f.in_set) AS reqlvl_n,
  coalesce(min(f.requires_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_price AND f.in_currency AND f.in_set), 0)::integer AS reqlvl_lo,
  coalesce(max(f.requires_level) FILTER (WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_price AND f.in_currency AND f.in_set), 0)::integer AS reqlvl_hi
FROM filtered f
`

type ItemFacetTotalsParams struct {
	ItemType        *string
	NameQuery       *string
	IDQuery         *int32
	PlaceSlugs      []string
	Region          *string
	Tier            *string
	Unchained       *bool
	Pvp             *bool
	SourceTab       *string
	SourceSection   *string
	SourceRegion    *string
	SourceMap       *string
	SourcePlaces    []string
	SourceBoss      *string
	SourceVendor    *string
	SourceQuest     *string
	SourceContainer *string
	SourceGroup     *string
	Rarities        []string
	EquipLocations  []string
	ArmourWeights   []string
	Classes         []string
	IlvlMin         *int32
	IlvlMax         *int32
	ReqlvlMin       *int32
	ReqlvlMax       *int32
	Price           *bool
	Currencies      []string
	Sets            []string
}

type ItemFacetTotalsRow struct {
	AnyRarity        int64
	AnyEquipLocation int64
	AnyArmourWeight  int64
	AnyClass         int64
	AnyCurrency      int64
	AnySet           int64
	AnyPrice         int64
	Priced           int64
	IlvlN            int64
	IlvlLo           int32
	IlvlHi           int32
	ReqlvlN          int64
	ReqlvlLo         int32
	ReqlvlHi         int32
}

// The rail's other numbers (AOC-049), from the same flags: each group's "Any" (every flag but the
// group's own), how many items have a vendor price, and the item-level and required-level spans a
// range control can usefully ask for. A span means something only when its count (ilvl_n, reqlvl_n)
// is above 0: sqlc types a cast aggregate as non-null, so an empty span is coalesced to 0 and the
// count says whether to believe it -- never a sentinel level.
func (q *Queries) ItemFacetTotals(ctx context.Context, arg ItemFacetTotalsParams) (ItemFacetTotalsRow, error) {
	row := q.db.QueryRow(ctx, itemFacetTotals,
		arg.ItemType,
		arg.NameQuery,
		arg.IDQuery,
		arg.PlaceSlugs,
		arg.Region,
		arg.Tier,
		arg.Unchained,
		arg.Pvp,
		arg.SourceTab,
		arg.SourceSection,
		arg.SourceRegion,
		arg.SourceMap,
		arg.SourcePlaces,
		arg.SourceBoss,
		arg.SourceVendor,
		arg.SourceQuest,
		arg.SourceContainer,
		arg.SourceGroup,
		arg.Rarities,
		arg.EquipLocations,
		arg.ArmourWeights,
		arg.Classes,
		arg.IlvlMin,
		arg.IlvlMax,
		arg.ReqlvlMin,
		arg.ReqlvlMax,
		arg.Price,
		arg.Currencies,
		arg.Sets,
	)
	var i ItemFacetTotalsRow
	err := row.Scan(
		&i.AnyRarity,
		&i.AnyEquipLocation,
		&i.AnyArmourWeight,
		&i.AnyClass,
		&i.AnyCurrency,
		&i.AnySet,
		&i.AnyPrice,
		&i.Priced,
		&i.IlvlN,
		&i.IlvlLo,
		&i.IlvlHi,
		&i.ReqlvlN,
		&i.ReqlvlLo,
		&i.ReqlvlHi,
	)
	return i, err
}

const itemIDSpan = `-- name: ItemIDSpan :one
SELECT coalesce(min(item_id), 0)::integer AS min_id,
       coalesce(max(item_id), 0)::integer AS max_id,
       count(*)::bigint AS total
FROM items
`

type ItemIDSpanRow struct {
	MinID int32
	MaxID int32
	Total int64
}

// The honest empty state (AOC-047): "ids run 1–4692, N absent" is computed, never typed.
func (q *Queries) ItemIDSpan(ctx context.Context) (ItemIDSpanRow, error) {
	row := q.db.QueryRow(ctx, itemIDSpan)
	var i ItemIDSpanRow
	err := row.Scan(&i.MinID, &i.MaxID, &i.Total)
	return i, err
}

const listAcquisitionGroups = `-- name: ListAcquisitionGroups :many
SELECT slug, name FROM acquisition_groups ORDER BY sort_order
`

type ListAcquisitionGroupsRow struct {
	Slug string
	Name string
}

// The design's two halves of a location, "loot / drops" and "quest / vendor" (AOC-050), in order.
func (q *Queries) ListAcquisitionGroups(ctx context.Context) ([]ListAcquisitionGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionGroupsRow{}
	for rows.Next() {
		var i ListAcquisitionGroupsRow
		if err := rows.Scan(&i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemClasses = `-- name: ListItemClasses :many
SELECT cl.id, cl.slug, cl.name, cl.short_name
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = $1
ORDER BY cl.sort_order NULLS LAST, cl.name
`

type ListItemClassesRow struct {
	ID        int32
	Slug      string
	Name      string
	ShortName *string
}

// one order for classes everywhere (AOC-065)
func (q *Queries) ListItemClasses(ctx context.Context, itemID int32) ([]ListItemClassesRow, error) {
	rows, err := q.db.Query(ctx, listItemClasses, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemClassesRow{}
	for rows.Next() {
		var i ListItemClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCosts = `-- name: ListItemCosts :many
SELECT ic.item_source_id, cu.slug AS currency, cu.name AS currency_name, ic.amount
FROM item_costs ic
JOIN currencies cu ON cu.id = ic.currency_id
WHERE ic.item_source_id = ANY($1::bigint[])
ORDER BY ic.item_source_id, cu.name
`

type ListItemCostsRow struct {
	ItemSourceID int64
	Currency     string
	CurrencyName string
	Amount       pgtype.Numeric
}

func (q *Queries) ListItemCosts(ctx context.Context, dollar_1 []int64) ([]ListItemCostsRow, error) {
	rows, err := q.db.Query(ctx, listItemCosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemCostsRow{}
	for rows.Next() {
		var i ListItemCostsRow
		if err := rows.Scan(
			&i.ItemSourceID,
			&i.Currency,
			&i.CurrencyName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemEquipLocations = `-- name: ListItemEquipLocations :many
SELECT el.id, el.slug, el.name
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = $1
ORDER BY el.id
`

func (q *Queries) ListItemEquipLocations(ctx context.Context, itemID int32) ([]EquipLocation, error) {
	rows, err := q.db.Query(ctx, listItemEquipLocations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquipLocation{}
	for rows.Next() {
		var i EquipLocation
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageClasses = `-- name: ListItemPageClasses :many
SELECT ic.item_id, cl.slug, cl.name, cl.short_name
FROM item_classes ic
JOIN classes cl ON cl.id = ic.class_id
WHERE ic.item_id = ANY($1::integer[])
ORDER BY ic.item_id, cl.sort_order NULLS LAST, cl.id
`

type ListItemPageClassesRow struct {
	ItemID    int32
	Slug      string
	Name      string
	ShortName *string
}

// A page's class restrictions in one round trip, with the short names the row shows (AOC-046).
// one order for classes everywhere (AOC-065)
func (q *Queries) ListItemPageClasses(ctx context.Context, itemIds []int32) ([]ListItemPageClassesRow, error) {
	rows, err := q.db.Query(ctx, listItemPageClasses, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageClassesRow{}
	for rows.Next() {
		var i ListItemPageClassesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageCosts = `-- name: ListItemPageCosts :many
SELECT src.item_id, src.id AS item_source_id, cu.name AS currency_name, ic.amount
FROM item_costs ic
JOIN item_sources src ON src.id = ic.item_source_id
JOIN currencies cu ON cu.id = ic.currency_id
WHERE src.item_id = ANY($1::integer[])
ORDER BY src.item_id, src.id, cu.name
`

type ListItemPageCostsRow struct {
	ItemID       int32
	ItemSourceID int64
	CurrencyName string
	Amount       pgtype.Numeric
}

// A page's vendor prices in one round trip: every cost of every source, grouped by the caller.
func (q *Queries) ListItemPageCosts(ctx context.Context, itemIds []int32) ([]ListItemPageCostsRow, error) {
	rows, err := q.db.Query(ctx, listItemPageCosts, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageCostsRow{}
	for rows.Next() {
		var i ListItemPageCostsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemSourceID,
			&i.CurrencyName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPageEquipLocations = `-- name: ListItemPageEquipLocations :many
SELECT iel.item_id, el.slug, el.name
FROM item_equip_locations iel
JOIN equip_locations el ON el.id = iel.equip_location_id
WHERE iel.item_id = ANY($1::integer[])
ORDER BY iel.item_id, el.id
`

type ListItemPageEquipLocationsRow struct {
	ItemID int32
	Slug   string
	Name   string
}

// A page's slots in one round trip (AOC-047), the ListItemPlaces pattern: never one query per row.
func (q *Queries) ListItemPageEquipLocations(ctx context.Context, itemIds []int32) ([]ListItemPageEquipLocationsRow, error) {
	rows, err := q.db.Query(ctx, listItemPageEquipLocations, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPageEquipLocationsRow{}
	for rows.Next() {
		var i ListItemPageEquipLocationsRow
		if err := rows.Scan(&i.ItemID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPlaces = `-- name: ListItemPlaces :many
SELECT src.item_id, p.slug AS place_slug, p.name AS place_name,
       -- coalesce, not a bare cast: min() over all-NULL is NULL, and sqlc types a cast as
       -- non-null, so the scan would fail on exactly the rows that have no region.
       coalesce(min(r.slug), '')::varchar AS region_slug,
       -- ⭐ ONE EXPRESSION PER FACT (AOC-039). The tier is blanked when the place's sources disagree,
       -- exactly like the boss below: min() would state one of two tiers as fact the first time the
       -- corpus held two. And unchained is the SAME expression the list filter and ListItemSources
       -- use -- src OR place, with a NULL place read as false -- so a row cannot be findable by
       -- unchained=true and then deny it on its own page.
       coalesce(CASE WHEN count(DISTINCT t.slug) = 1 THEN min(t.slug) END, '')::varchar AS tier_slug,
       bool_or(src.unchained OR coalesce(p.unchained, false)) AS unchained,
       -- The boss only when it is unambiguous: two bosses in one place would make either name a
       -- lie, and a blank is honest where a guess is not (CLAUDE.md STEP ZERO).
       coalesce(CASE WHEN count(DISTINCT b.name) = 1 THEN min(b.name) END, '')::varchar AS boss_name
FROM item_sources src
JOIN places p ON p.id = src.place_id
LEFT JOIN regions r ON r.id = coalesce(p.region_id, src.region_id)
LEFT JOIN tiers t ON t.id = src.tier_id
LEFT JOIN bosses b ON b.id = src.boss_id
WHERE src.item_id = ANY($1::integer[])
GROUP BY src.item_id, p.slug, p.name
ORDER BY p.name
`

type ListItemPlacesRow struct {
	ItemID     int32
	PlaceSlug  string
	PlaceName  string
	RegionSlug string
	TierSlug   string
	Unchained  bool
	BossName   string
}

// The per-item place context for a page of results, fetched in ONE round trip for the whole page
// rather than per row. Used two ways:
//   - an aggregate view (region/map/tier, or no place filter) renders these as "also drops in",
//     and the item still appears ONCE -- Pierre's rule, DECISIONS.md 2026-09-13;
//   - a view that named specific places expands to one row per item per NAMED place, because there
//     the duplication is the information.
//
// The choice is made server-side from the filters, never by a client flag.
// ⚠️ GROUPED BY PLACE, not by source row. An item can have several item_sources in ONE place --
// two bosses, or a boss and a container -- and without the grouping the same dungeon appeared
// twice next to the item, which made a two-dungeon selection render four rows instead of two.
// Measured on the real data before it was written. The unit of Pierre's rule is the PLACE.
// Every individual source, with its own boss, is still on the item page via ListItemSources.
func (q *Queries) ListItemPlaces(ctx context.Context, itemIds []int32) ([]ListItemPlacesRow, error) {
	rows, err := q.db.Query(ctx, listItemPlaces, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPlacesRow{}
	for rows.Next() {
		var i ListItemPlacesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.PlaceSlug,
			&i.PlaceName,
			&i.RegionSlug,
			&i.TierSlug,
			&i.Unchained,
			&i.BossName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSlugs = `-- name: ListItemSlugs :many
SELECT i.slug
FROM items i
ORDER BY i.item_id
LIMIT $2::int OFFSET $1::int
`

type ListItemSlugsParams struct {
	PageOffset int32
	PageSize   int32
}

// AOC-025: the sitemap's item URLs, one page of them. Ordered by the source site's own id, which
// never changes, so a chunk holds the same items from one crawl to the next.
func (q *Queries) ListItemSlugs(ctx context.Context, arg ListItemSlugsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemSlugs, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSources = `-- name: ListItemSources :many
SELECT src.id, src.item_id,
       at.slug AS acquisition_type, at.name AS acquisition_type_name,
       src.place_id, p.name AS place_name, p.slug AS place_slug,
       src.boss_id, bo.name AS boss_name,
       src.vendor_id, v.name AS vendor_name,
       src.quest_id, q.name AS quest_name,
       -- what the armory's quest column said: a giver, a hub or a bucket as often as a title, so
       -- the page shows it as listed and never calls it the quest's name (quests.name is NULL)
       q.armory_label AS quest_label,
       src.container_id, ct.name AS container_name,
       src.region_id, rg.name AS region_name, rg.slug AS region_slug,
       src.map_id, mp.name AS map_name, mp.slug AS map_slug,
       src.tier_id, tr.slug AS tier, tr.name AS tier_name,
       src.is_raid, src.coords, src.section_raw,
       -- ⭐ src OR place (AOC-039): the one unchained expression, shared with the list filter and
       -- ListItemPlaces. This was the bare src.unchained -- the third spelling of one rule, which
       -- agreed with the other two only because the importer set both columns from one source.
       (src.unchained OR coalesce(p.unchained, false))::boolean AS unchained,
       c.slug AS confidence, src.source_note, src.open_question
FROM item_sources src
JOIN confidence_levels c ON c.id = src.confidence_id
LEFT JOIN acquisition_types at ON at.id = src.acquisition_type_id
LEFT JOIN places p ON p.id = src.place_id
LEFT JOIN bosses bo ON bo.id = src.boss_id
LEFT JOIN vendors v ON v.id = src.vendor_id
LEFT JOIN quests q ON q.id = src.quest_id
LEFT JOIN containers ct ON ct.id = src.container_id
LEFT JOIN regions rg ON rg.id = coalesce(p.region_id, src.region_id)
LEFT JOIN maps mp ON mp.id = coalesce(p.map_id, src.map_id)
LEFT JOIN tiers tr ON tr.id = src.tier_id
WHERE src.item_id = $1
ORDER BY src.id
`

type ListItemSourcesRow struct {
	ID                  int64
	ItemID              int32
	AcquisitionType     *string
	AcquisitionTypeName *string
	PlaceID             *int32
	PlaceName           *string
	PlaceSlug           *string
	BossID              *int32
	BossName            *string
	VendorID            *int32
	VendorName          *string
	QuestID             *int32
	QuestName           *string
	QuestLabel          *string
	ContainerID         *int32
	ContainerName       *string
	RegionID            *int32
	RegionName          *string
	RegionSlug          *string
	MapID               *int32
	MapName             *string
	MapSlug             *string
	TierID              *int32
	Tier                *string
	TierName            *string
	IsRaid              bool
	Coords              *string
	SectionRaw          *string
	Unchained           bool
	Confidence          string
	SourceNote          string
	OpenQuestion        *string
}

// An item page's "where does this come from". 237 items have more than one place — 8 with two and
// 229 with three — so this is a list and never a single row.
// ⚠️ THE PLACE DECIDES, here too. AOC-012 verify round 1 settled that a source's place is the
// stronger fact than the source's own region, and it was written into ListItems and
// ListItemPlaces -- but NOT here, so the item page said Cimmeria for a place the list called
// Stygia. 196 rows across 98 items, region and map alike, and a reader got a different answer
// depending on which endpoint they landed on (verify round 4).
//
// A read decision has to name EVERY query that publishes the fact, not the ones in front of you.
func (q *Queries) ListItemSources(ctx context.Context, itemID int32) ([]ListItemSourcesRow, error) {
	rows, err := q.db.Query(ctx, listItemSources, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSourcesRow{}
	for rows.Next() {
		var i ListItemSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AcquisitionType,
			&i.AcquisitionTypeName,
			&i.PlaceID,
			&i.PlaceName,
			&i.PlaceSlug,
			&i.BossID,
			&i.BossName,
			&i.VendorID,
			&i.VendorName,
			&i.QuestID,
			&i.QuestName,
			&i.QuestLabel,
			&i.ContainerID,
			&i.ContainerName,
			&i.RegionID,
			&i.RegionName,
			&i.RegionSlug,
			&i.MapID,
			&i.MapName,
			&i.MapSlug,
			&i.TierID,
			&i.Tier,
			&i.TierName,
			&i.IsRaid,
			&i.Coords,
			&i.SectionRaw,
			&i.Unchained,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSpellEffects = `-- name: ListItemSpellEffects :many
SELECT se.item_id, se.stat, se.value, se.sign, se.unit, se.damage_type, se.pvp
FROM item_spell_effects se
WHERE se.item_id = $1
ORDER BY se.id
`

type ListItemSpellEffectsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

// Deliberately its own query against its own table. See the header. In the tooltip's order, like
// ListItemStats.
func (q *Queries) ListItemSpellEffects(ctx context.Context, itemID int32) ([]ListItemSpellEffectsRow, error) {
	rows, err := q.db.Query(ctx, listItemSpellEffects, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSpellEffectsRow{}
	for rows.Next() {
		var i ListItemSpellEffectsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStats = `-- name: ListItemStats :many
SELECT st.item_id, st.stat, st.value, st.sign, st.unit, st.damage_type, st.pvp
FROM item_stats st
WHERE st.item_id = $1
ORDER BY st.id
`

type ListItemStatsRow struct {
	ItemID     int32
	Stat       string
	Value      pgtype.Numeric
	Sign       int16
	Unit       string
	DamageType *string
	Pvp        bool
}

// In the TOOLTIP's order (AOC-048): the importer writes each item's stats in the order its tooltip
// prints them, so the id is that order — Dexterity before Combat Rating, as the game shows it.
// It was alphabetical until then, which no reader of a tooltip would recognise.
func (q *Queries) ListItemStats(ctx context.Context, itemID int32) ([]ListItemStatsRow, error) {
	rows, err := q.db.Query(ctx, listItemStats, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemStatsRow{}
	for rows.Next() {
		var i ListItemStatsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Stat,
			&i.Value,
			&i.Sign,
			&i.Unit,
			&i.DamageType,
			&i.Pvp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
WITH filtered AS (
  SELECT i.item_id, i.rarity_id, i.armour_weight_id, i.set_id, i.item_level, i.requires_level,
         pr.priced,
         -- The filters that have no facet of their own, as ONE flag.
         coalesce(
           ($4::varchar IS NULL OR it.slug = $4::varchar)
           -- ESCAPE, because a name query is free text from a URL: '%' alone matched every one of the
           -- 4,646 items and '_' matched any single character. The caller escapes the metacharacters
           -- (escapeLike); this names the escape character so Postgres honours them.
           -- q matches the name, or the item's id exactly when q is a whole number (AOC-047): the
           -- armory site's ids are what people still quote, and a name search for "2183" would
           -- otherwise find nothing. id_query is NULL unless q is numeric.
           AND ($5::varchar IS NULL
                OR i.name ILIKE '%' || $5::varchar || '%' ESCAPE '\'
                OR i.item_id = $6::integer)
           -- A LIST, not one slug. Selecting two dungeons is the case Pierre's rule is about, and a
           -- single-value parameter made the caller's second choice unrepresentable -- so the
           -- service passed NULL and the place predicate silently vanished, returning all 4,646
           -- items (AOC-012 verify round 1).
           -- ⚠️ NULL means "no filter"; an EMPTY array does not -- ` + "`" + `p.slug = ANY('{}')` + "`" + ` is false for
           -- every row. The caller passes nil rather than an empty slice, and derives that from the
           -- same predicate that decides collapsing, so the two cannot disagree (verify round 2).
           AND ($7::varchar[] IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND p.slug = ANY($7::varchar[])))
           -- region and tier live on item_sources, not on the item: an item is "in Kheshatta"
           -- because something that drops it is. Both are aggregate views, so they collapse.
           AND ($8::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 -- The PLACE's region wins. 196 item_sources rows disagree with their own place's
                 -- region (AOC-037), and the place row is the stronger fact: it carries name, map
                 -- and region together, with an invariant test behind it, while the per-source
                 -- region is derived and has none. A source with no place falls back to its own.
                 LEFT JOIN regions r2 ON r2.id = coalesce(p.region_id, src.region_id)
                 WHERE src.item_id = i.item_id AND r2.slug = $8::varchar))
           AND ($9::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN tiers t ON t.id = src.tier_id
                 WHERE src.item_id = i.item_id AND t.slug = $9::varchar))
           -- ⭐ unchained is true on EITHER the source row or the place it points at (AOC-039: the
           -- one expression, shared with ListItemSources and ListItemPlaces).
           AND ($10::boolean IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND (src.unchained OR coalesce(p.unchained, false)) = $10::boolean))
           -- pvp is three independent facts on the item, and "pvp=true" means any of them.
           AND ($11::boolean IS NULL
                OR (i.pvp_source OR i.has_pvp_stats OR i.pvp_penalty) = $11::boolean)
           -- ⭐ A SOURCE is ONE item_sources row (AOC-050): its tab's section, its region, map, place,
           -- boss, vendor, quest giver, container and acquisition group TOGETHER. tier= and place=
           -- above may each match a different row of the same item; a node of the source tree may
           -- not, or a tier's raid would count an item that is in the tier only somewhere else.
           -- source_tab is NULL unless a node is picked: a tab on its own filters nothing (Pierre,
           -- 2026-10-02). Region and map are the PLACE's when it has one, as everywhere (AOC-037).
           AND ($12::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN sections sc ON sc.id = src.section_id
                 JOIN source_tabs stb ON stb.id = sc.tab_id
                 LEFT JOIN places p ON p.id = src.place_id
                 LEFT JOIN regions sr ON sr.id = coalesce(p.region_id, src.region_id)
                 LEFT JOIN maps sm ON sm.id = coalesce(p.map_id, src.map_id)
                 LEFT JOIN bosses sb ON sb.id = src.boss_id
                 LEFT JOIN vendors sv ON sv.id = src.vendor_id
                 LEFT JOIN quests sq ON sq.id = src.quest_id
                 LEFT JOIN containers sct ON sct.id = src.container_id
                 LEFT JOIN acquisition_types sat ON sat.id = src.acquisition_type_id
                 LEFT JOIN acquisition_groups sag ON sag.id = sat.group_id
                 WHERE src.item_id = i.item_id
                   AND stb.slug = $12::varchar
                   AND ($13::varchar IS NULL OR sc.slug = $13::varchar)
                   -- '-' is "the row has no such level" (AOC-050 verify round 1, F1): a branch the
                   -- panel draws with that level skipped holds only the rows that lack it.
                   AND ($14::varchar IS NULL OR CASE WHEN $14::varchar = '-' THEN sr.id IS NULL ELSE sr.slug = $14::varchar END)
                   AND ($15::varchar IS NULL OR CASE WHEN $15::varchar = '-' THEN sm.id IS NULL ELSE sm.slug = $15::varchar END)
                   -- The places the service resolved: a place and every place inside it (AOC-038),
                   -- the place alone when a boss, vendor, quest giver or container follows it, or
                   -- '{-}' for no place at all.
                   AND ($16::varchar[] IS NULL OR CASE WHEN $16::varchar[] = ARRAY['-']::varchar[] THEN p.id IS NULL ELSE p.slug = ANY($16::varchar[]) END)
                   AND ($17::varchar IS NULL OR sb.slug = $17::varchar)
                   AND ($18::varchar IS NULL OR sv.slug = $18::varchar)
                   AND ($19::varchar IS NULL OR sq.slug = $19::varchar)
                   AND ($20::varchar IS NULL OR sct.slug = $20::varchar)
                   AND ($21::varchar IS NULL OR sag.slug = $21::varchar))),
           false) AS in_base,
         -- One flag per facet (AOC-049). Each is the whole of that filter's rule. A facet takes a LIST
         -- (AOC-064): any of its values, as ` + "`" + `place` + "`" + ` always has; NULL is no filter, never '{}'.
         ($22::varchar[] IS NULL OR r.slug = ANY($22::varchar[])) AS in_rarity,
         -- ⭐ The slot goes through the join, so 'off-hand' finds the 389 one-handers (they fit either
         -- hand) as well as the 141 off-hand-only items -- 530, not 141 (AOC-058).
         ($23::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_equip_locations iel
           JOIN equip_locations el ON el.id = iel.equip_location_id
           WHERE iel.item_id = i.item_id AND el.slug = ANY($23::varchar[]))) AS in_slot,
         coalesce($24::varchar[] IS NULL OR aw.slug = ANY($24::varchar[]), false) AS in_weight,
         ($25::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_classes ic
           JOIN classes cl ON cl.id = ic.class_id
           WHERE ic.item_id = i.item_id AND cl.slug = ANY($25::varchar[]))) AS in_class,
         -- A bound excludes an item with no level: it cannot be shown to be inside the range.
         coalesce(($26::integer IS NULL OR i.item_level >= $26::integer)
              AND ($27::integer IS NULL OR i.item_level <= $27::integer), false) AS in_ilvl,
         coalesce(($28::integer IS NULL OR i.requires_level >= $28::integer)
              AND ($29::integer IS NULL OR i.requires_level <= $29::integer), false) AS in_reqlvl,
         -- "Has a vendor price" matches ANY occurrence: the list shows items, not occurrences, and an
         -- item free from a boss and sold by a vendor (689 of them) has a price.
         ($30::boolean IS NULL OR pr.priced = $30::boolean) AS in_price,
         ($31::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_sources src
           JOIN item_costs ico ON ico.item_source_id = src.id
           JOIN currencies cu ON cu.id = ico.currency_id
           WHERE src.item_id = i.item_id AND cu.slug = ANY($31::varchar[]))) AS in_currency,
         coalesce($32::varchar[] IS NULL OR st.slug = ANY($32::varchar[]), false) AS in_set
  FROM items i
  JOIN rarities r ON r.id = i.rarity_id
  LEFT JOIN item_types it ON it.id = i.item_type_id
  LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
  LEFT JOIN sets st ON st.id = i.set_id
  -- One expression for "has a vendor price", read by in_price and by the price facet. A subquery
  -- with no FROM is pulled up into its references, so a query that reads neither never runs it.
  CROSS JOIN LATERAL (SELECT EXISTS (
    SELECT 1 FROM item_sources src
    JOIN item_costs ico ON ico.item_source_id = src.id
    WHERE src.item_id = i.item_id) AS priced) pr
)
SELECT i.item_id, i.slug, i.name,
       r.slug AS rarity, r.sort_order AS rarity_sort, r.colour_token AS rarity_colour_token,
       it.slug AS item_type, it.name AS item_type_name,
       sf.slug AS slot_fit,
       aw.slug AS armour_weight, aw.name AS armour_weight_name,
       i.item_level, i.requires_level, i.armor, i.dps,
       i.set_id, i.tooltip_image,
       c.slug AS confidence,
       count(*) OVER () AS total_count
FROM filtered f
JOIN items i ON i.item_id = f.item_id
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN confidence_levels c ON c.id = i.confidence_id
LEFT JOIN slot_fits sf ON sf.id = i.slot_fit_id
LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
WHERE f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set
ORDER BY
  CASE WHEN $1::varchar = 'ilvl' THEN i.item_level END DESC NULLS LAST,
  CASE WHEN $1::varchar = 'id' THEN i.item_id END ASC,
  i.name, i.item_id
LIMIT $3::integer OFFSET $2::integer
`

type ListItemsParams struct {
	SortBy          string
	PageOffset      int32
	PageSize        int32
	ItemType        *string
	NameQuery       *string
	IDQuery         *int32
	PlaceSlugs      []string
	Region          *string
	Tier            *string
	Unchained       *bool
	Pvp             *bool
	SourceTab       *string
	SourceSection   *string
	SourceRegion    *string
	SourceMap       *string
	SourcePlaces    []string
	SourceBoss      *string
	SourceVendor    *string
	SourceQuest     *string
	SourceContainer *string
	SourceGroup     *string
	Rarities        []string
	EquipLocations  []string
	ArmourWeights   []string
	Classes         []string
	IlvlMin         *int32
	IlvlMax         *int32
	ReqlvlMin       *int32
	ReqlvlMax       *int32
	Price           *bool
	Currencies      []string
	Sets            []string
}

type ListItemsRow struct {
	ItemID            int32
	Slug              string
	Name              string
	Rarity            string
	RaritySort        int32
	RarityColourToken *string
	ItemType          *string
	ItemTypeName      *string
	SlotFit           *string
	ArmourWeight      *string
	ArmourWeightName  *string
	ItemLevel         *int32
	RequiresLevel     *int32
	Armor             *int32
	Dps               pgtype.Numeric
	SetID             *int32
	TooltipImage      *string
	Confidence        string
	TotalCount        int64
}

// ⭐ THE FILTER RULES ARE WRITTEN ONCE (AOC-049). Every query that filters the armory list starts with
// the same `filtered` CTE, byte for byte: one row per item, carrying one boolean per filter -- a
// flag per facet of the rail, and `in_base` for the filters that have none. The list keeps the
// items whose flags are all true. A facet counts the items whose flags are all true EXCEPT ITS OWN,
// which is "how many would this choice leave, under the other filters" -- and since the count and
// the rows read the same flags, they cannot disagree.
//
// ⛔ Edit the CTE in one query and you must edit it in all three: ListItems, CountItemFacets and
// ItemFacetTotals. TestTheFilterCTEIsOneDefinition (internal/db) reads this file and fails on any
// difference -- sqlc has no way to share a fragment between queries, so the identity is a test.
// Every flag is two-valued (NULL is coalesced to false), so "all but one" never meets a NULL.
//
// The Armory list page. Every filter is optional: a NULL argument means "do not filter on this",
// which keeps one query behind every combination the page offers rather than building SQL by hand.
//
// ⭐ The equip-location filter goes through the join (EXISTS), so asking for 'off-hand' returns
// the 389 one-handed weapons (they fit either hand) as well as the 141 off-hand-only items — 530,
// not 141 (measured 2026-09-30). That is the acceptance criterion this whole schema shape exists for,
// and TestListItemsFindsOneHandersWhenAskedForOffHand exercises THIS query, not a copy of it.
// ⭐ ONE query, three orders (AOC-047). A CASE per sort key keeps every filter above in one
// place; the keys are code ('name', 'ilvl', 'id' — not a game concept), validated before they
// get here. ilvl is DESCENDING with NULLs LAST, so the 50 items with no recorded level end the
// list rather than vanish or lead it; the name and id tie-breakers make every page stable.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.SortBy,
		arg.PageOffset,
		arg.PageSize,
		arg.ItemType,
		arg.NameQuery,
		arg.IDQuery,
		arg.PlaceSlugs,
		arg.Region,
		arg.Tier,
		arg.Unchained,
		arg.Pvp,
		arg.SourceTab,
		arg.SourceSection,
		arg.SourceRegion,
		arg.SourceMap,
		arg.SourcePlaces,
		arg.SourceBoss,
		arg.SourceVendor,
		arg.SourceQuest,
		arg.SourceContainer,
		arg.SourceGroup,
		arg.Rarities,
		arg.EquipLocations,
		arg.ArmourWeights,
		arg.Classes,
		arg.IlvlMin,
		arg.IlvlMax,
		arg.ReqlvlMin,
		arg.ReqlvlMax,
		arg.Price,
		arg.Currencies,
		arg.Sets,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.RarityColourToken,
			&i.ItemType,
			&i.ItemTypeName,
			&i.SlotFit,
			&i.ArmourWeight,
			&i.ArmourWeightName,
			&i.ItemLevel,
			&i.RequiresLevel,
			&i.Armor,
			&i.Dps,
			&i.SetID,
			&i.TooltipImage,
			&i.Confidence,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCurrency = `-- name: ListItemsByCurrency :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, it.slug AS item_type,
       ic.amount, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN item_costs ic ON ic.item_source_id = src.id
JOIN currencies cu ON cu.id = ic.currency_id
WHERE cu.slug = $1
ORDER BY ic.amount, i.name
`

type ListItemsByCurrencyRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	ItemType     *string
	Amount       pgtype.Numeric
	TooltipImage *string
}

// A currency page: "what does this token buy?" (DECISIONS.md 2026-09-14 — currency is an entity
// with its own page, so the fact is stated once instead of on every item bought with it).
func (q *Queries) ListItemsByCurrency(ctx context.Context, slug string) ([]ListItemsByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, listItemsByCurrency, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByCurrencyRow{}
	for rows.Next() {
		var i ListItemsByCurrencyRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.ItemType,
			&i.Amount,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByPlace = `-- name: ListItemsByPlace :many
SELECT DISTINCT i.item_id, i.slug, i.name, r.slug AS rarity, r.sort_order AS rarity_sort,
       it.slug AS item_type, i.tooltip_image
FROM items i
JOIN rarities r ON r.id = i.rarity_id
LEFT JOIN item_types it ON it.id = i.item_type_id
JOIN item_sources src ON src.item_id = i.item_id
JOIN places p ON p.id = src.place_id
WHERE p.slug = $1
ORDER BY r.sort_order DESC, i.name
`

type ListItemsByPlaceRow struct {
	ItemID       int32
	Slug         string
	Name         string
	Rarity       string
	RaritySort   int32
	ItemType     *string
	TooltipImage *string
}

// The reverse lookup, and the one Pierre asked for first: "what drops here?" on a place page.
func (q *Queries) ListItemsByPlace(ctx context.Context, slug string) ([]ListItemsByPlaceRow, error) {
	rows, err := q.db.Query(ctx, listItemsByPlace, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsByPlaceRow{}
	for rows.Next() {
		var i ListItemsByPlaceRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.Rarity,
			&i.RaritySort,
			&i.ItemType,
			&i.TooltipImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenItemQuestions = `-- name: ListOpenItemQuestions :many
SELECT 'item' AS kind, i.item_id AS id, i.name, i.open_question
FROM items i WHERE i.open_question IS NOT NULL
UNION ALL
SELECT 'item_source', src.item_id, i.name, src.open_question
FROM item_sources src JOIN items i ON i.item_id = src.item_id
WHERE src.open_question IS NOT NULL
UNION ALL
SELECT 'set', s.id, s.name, s.open_question
FROM sets s WHERE s.open_question IS NOT NULL
ORDER BY kind, name
`

type ListOpenItemQuestionsRow struct {
	Kind         string
	ID           int32
	Name         string
	OpenQuestion *string
}

// The counterpart of AOC-009's ListOpenQuestions: everything the item data could not answer,
// in one read, so "what do we still need to ask Pierre" stays a query and not a memory.
func (q *Queries) ListOpenItemQuestions(ctx context.Context) ([]ListOpenItemQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenItemQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenItemQuestionsRow{}
	for rows.Next() {
		var i ListOpenItemQuestionsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceHierarchy = `-- name: ListPlaceHierarchy :many
SELECT p.slug, p.name, coalesce(pp.slug, '')::varchar AS parent_slug
FROM places p LEFT JOIN places pp ON pp.id = p.parent_place_id
ORDER BY p.slug
`

type ListPlaceHierarchyRow struct {
	Slug       string
	Name       string
	ParentSlug string
}

// Every place with its parent (AOC-050): the source panel draws a place under every place above it,
// at any depth (AOC-038), and checks that a source path's places are each other's parents. 86 rows.
func (q *Queries) ListPlaceHierarchy(ctx context.Context) ([]ListPlaceHierarchyRow, error) {
	rows, err := q.db.Query(ctx, listPlaceHierarchy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaceHierarchyRow{}
	for rows.Next() {
		var i ListPlaceHierarchyRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.ParentSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionTabs = `-- name: ListSectionTabs :many
SELECT sc.slug, sc.name, t.slug AS tab_slug
FROM sections sc JOIN source_tabs t ON t.id = sc.tab_id
ORDER BY t.sort_order, sc.sort_order
`

type ListSectionTabsRow struct {
	Slug    string
	Name    string
	TabSlug string
}

// Every section and its tab: what a source path's section must belong to.
func (q *Queries) ListSectionTabs(ctx context.Context) ([]ListSectionTabsRow, error) {
	rows, err := q.db.Query(ctx, listSectionTabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSectionTabsRow{}
	for rows.Next() {
		var i ListSectionTabsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.TabSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetPieces = `-- name: ListSetPieces :many
SELECT i.item_id, i.slug, i.name, r.colour_token AS rarity_colour_token
FROM items i
JOIN rarities r ON r.id = i.rarity_id
WHERE i.set_id = $1
ORDER BY i.name, i.item_id
`

type ListSetPiecesRow struct {
	ItemID            int32
	Slug              string
	Name              string
	RarityColourToken *string
}

// AOC-048: every piece of one set, for the item page and /v1's set_pieces. Bounded by the data's
// own shape — the largest set holds 16 (measured 2026-09-30) — so it is part of one item's detail,
// not a list endpoint.
func (q *Queries) ListSetPieces(ctx context.Context, setID *int32) ([]ListSetPiecesRow, error) {
	rows, err := q.db.Query(ctx, listSetPieces, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetPiecesRow{}
	for rows.Next() {
		var i ListSetPiecesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Slug,
			&i.Name,
			&i.RarityColourToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT s.id, s.slug, s.name, cl.slug AS class, aw.slug AS set_armour_weight,
       c.slug AS confidence, s.source_note, s.open_question,
       s.declared_piece_count,
       (SELECT count(*) FROM items i WHERE i.set_id = s.id) AS pieces_held
FROM sets s
JOIN confidence_levels c ON c.id = s.confidence_id
LEFT JOIN classes cl ON cl.id = s.class_id
LEFT JOIN armour_weights aw ON aw.id = s.set_armour_weight_id
ORDER BY s.name
`

type ListSetsRow struct {
	ID                 int32
	Slug               string
	Name               string
	Class              *string
	SetArmourWeight    *string
	Confidence         string
	SourceNote         string
	OpenQuestion       *string
	DeclaredPieceCount *int32
	PiecesHeld         int64
}

func (q *Queries) ListSets(ctx context.Context) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSetsRow{}
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Class,
			&i.SetArmourWeight,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
			&i.DeclaredPieceCount,
			&i.PiecesHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceTabs = `-- name: ListSourceTabs :many
SELECT slug, name, sort_order, levels_note, groups::varchar[] AS groups
FROM source_tabs
ORDER BY sort_order
`

type ListSourceTabsRow struct {
	Slug       string
	Name       string
	SortOrder  int32
	LevelsNote string
	Groups     []string
}

// The tabs in Pierre's order, with the levels each draws above the location (AOC-050).
func (q *Queries) ListSourceTabs(ctx context.Context) ([]ListSourceTabsRow, error) {
	rows, err := q.db.Query(ctx, listSourceTabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceTabsRow{}
	for rows.Next() {
		var i ListSourceTabsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.SortOrder,
			&i.LevelsNote,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceTreeRows = `-- name: ListSourceTreeRows :many
WITH filtered AS (
  SELECT i.item_id, i.rarity_id, i.armour_weight_id, i.set_id, i.item_level, i.requires_level,
         pr.priced,
         -- The filters that have no facet of their own, as ONE flag.
         coalesce(
           ($2::varchar IS NULL OR it.slug = $2::varchar)
           -- ESCAPE, because a name query is free text from a URL: '%' alone matched every one of the
           -- 4,646 items and '_' matched any single character. The caller escapes the metacharacters
           -- (escapeLike); this names the escape character so Postgres honours them.
           -- q matches the name, or the item's id exactly when q is a whole number (AOC-047): the
           -- armory site's ids are what people still quote, and a name search for "2183" would
           -- otherwise find nothing. id_query is NULL unless q is numeric.
           AND ($3::varchar IS NULL
                OR i.name ILIKE '%' || $3::varchar || '%' ESCAPE '\'
                OR i.item_id = $4::integer)
           -- A LIST, not one slug. Selecting two dungeons is the case Pierre's rule is about, and a
           -- single-value parameter made the caller's second choice unrepresentable -- so the
           -- service passed NULL and the place predicate silently vanished, returning all 4,646
           -- items (AOC-012 verify round 1).
           -- ⚠️ NULL means "no filter"; an EMPTY array does not -- ` + "`" + `p.slug = ANY('{}')` + "`" + ` is false for
           -- every row. The caller passes nil rather than an empty slice, and derives that from the
           -- same predicate that decides collapsing, so the two cannot disagree (verify round 2).
           AND ($5::varchar[] IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND p.slug = ANY($5::varchar[])))
           -- region and tier live on item_sources, not on the item: an item is "in Kheshatta"
           -- because something that drops it is. Both are aggregate views, so they collapse.
           AND ($6::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 -- The PLACE's region wins. 196 item_sources rows disagree with their own place's
                 -- region (AOC-037), and the place row is the stronger fact: it carries name, map
                 -- and region together, with an invariant test behind it, while the per-source
                 -- region is derived and has none. A source with no place falls back to its own.
                 LEFT JOIN regions r2 ON r2.id = coalesce(p.region_id, src.region_id)
                 WHERE src.item_id = i.item_id AND r2.slug = $6::varchar))
           AND ($7::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN tiers t ON t.id = src.tier_id
                 WHERE src.item_id = i.item_id AND t.slug = $7::varchar))
           -- ⭐ unchained is true on EITHER the source row or the place it points at (AOC-039: the
           -- one expression, shared with ListItemSources and ListItemPlaces).
           AND ($8::boolean IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 LEFT JOIN places p ON p.id = src.place_id
                 WHERE src.item_id = i.item_id
                   AND (src.unchained OR coalesce(p.unchained, false)) = $8::boolean))
           -- pvp is three independent facts on the item, and "pvp=true" means any of them.
           AND ($9::boolean IS NULL
                OR (i.pvp_source OR i.has_pvp_stats OR i.pvp_penalty) = $9::boolean)
           -- ⭐ A SOURCE is ONE item_sources row (AOC-050): its tab's section, its region, map, place,
           -- boss, vendor, quest giver, container and acquisition group TOGETHER. tier= and place=
           -- above may each match a different row of the same item; a node of the source tree may
           -- not, or a tier's raid would count an item that is in the tier only somewhere else.
           -- source_tab is NULL unless a node is picked: a tab on its own filters nothing (Pierre,
           -- 2026-10-02). Region and map are the PLACE's when it has one, as everywhere (AOC-037).
           AND ($10::varchar IS NULL OR EXISTS (
                 SELECT 1 FROM item_sources src
                 JOIN sections sc ON sc.id = src.section_id
                 JOIN source_tabs stb ON stb.id = sc.tab_id
                 LEFT JOIN places p ON p.id = src.place_id
                 LEFT JOIN regions sr ON sr.id = coalesce(p.region_id, src.region_id)
                 LEFT JOIN maps sm ON sm.id = coalesce(p.map_id, src.map_id)
                 LEFT JOIN bosses sb ON sb.id = src.boss_id
                 LEFT JOIN vendors sv ON sv.id = src.vendor_id
                 LEFT JOIN quests sq ON sq.id = src.quest_id
                 LEFT JOIN containers sct ON sct.id = src.container_id
                 LEFT JOIN acquisition_types sat ON sat.id = src.acquisition_type_id
                 LEFT JOIN acquisition_groups sag ON sag.id = sat.group_id
                 WHERE src.item_id = i.item_id
                   AND stb.slug = $10::varchar
                   AND ($11::varchar IS NULL OR sc.slug = $11::varchar)
                   -- '-' is "the row has no such level" (AOC-050 verify round 1, F1): a branch the
                   -- panel draws with that level skipped holds only the rows that lack it.
                   AND ($12::varchar IS NULL OR CASE WHEN $12::varchar = '-' THEN sr.id IS NULL ELSE sr.slug = $12::varchar END)
                   AND ($13::varchar IS NULL OR CASE WHEN $13::varchar = '-' THEN sm.id IS NULL ELSE sm.slug = $13::varchar END)
                   -- The places the service resolved: a place and every place inside it (AOC-038),
                   -- the place alone when a boss, vendor, quest giver or container follows it, or
                   -- '{-}' for no place at all.
                   AND ($14::varchar[] IS NULL OR CASE WHEN $14::varchar[] = ARRAY['-']::varchar[] THEN p.id IS NULL ELSE p.slug = ANY($14::varchar[]) END)
                   AND ($15::varchar IS NULL OR sb.slug = $15::varchar)
                   AND ($16::varchar IS NULL OR sv.slug = $16::varchar)
                   AND ($17::varchar IS NULL OR sq.slug = $17::varchar)
                   AND ($18::varchar IS NULL OR sct.slug = $18::varchar)
                   AND ($19::varchar IS NULL OR sag.slug = $19::varchar))),
           false) AS in_base,
         -- One flag per facet (AOC-049). Each is the whole of that filter's rule. A facet takes a LIST
         -- (AOC-064): any of its values, as ` + "`" + `place` + "`" + ` always has; NULL is no filter, never '{}'.
         ($20::varchar[] IS NULL OR r.slug = ANY($20::varchar[])) AS in_rarity,
         -- ⭐ The slot goes through the join, so 'off-hand' finds the 389 one-handers (they fit either
         -- hand) as well as the 141 off-hand-only items -- 530, not 141 (AOC-058).
         ($21::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_equip_locations iel
           JOIN equip_locations el ON el.id = iel.equip_location_id
           WHERE iel.item_id = i.item_id AND el.slug = ANY($21::varchar[]))) AS in_slot,
         coalesce($22::varchar[] IS NULL OR aw.slug = ANY($22::varchar[]), false) AS in_weight,
         ($23::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_classes ic
           JOIN classes cl ON cl.id = ic.class_id
           WHERE ic.item_id = i.item_id AND cl.slug = ANY($23::varchar[]))) AS in_class,
         -- A bound excludes an item with no level: it cannot be shown to be inside the range.
         coalesce(($24::integer IS NULL OR i.item_level >= $24::integer)
              AND ($25::integer IS NULL OR i.item_level <= $25::integer), false) AS in_ilvl,
         coalesce(($26::integer IS NULL OR i.requires_level >= $26::integer)
              AND ($27::integer IS NULL OR i.requires_level <= $27::integer), false) AS in_reqlvl,
         -- "Has a vendor price" matches ANY occurrence: the list shows items, not occurrences, and an
         -- item free from a boss and sold by a vendor (689 of them) has a price.
         ($28::boolean IS NULL OR pr.priced = $28::boolean) AS in_price,
         ($29::varchar[] IS NULL OR EXISTS (
           SELECT 1 FROM item_sources src
           JOIN item_costs ico ON ico.item_source_id = src.id
           JOIN currencies cu ON cu.id = ico.currency_id
           WHERE src.item_id = i.item_id AND cu.slug = ANY($29::varchar[]))) AS in_currency,
         coalesce($30::varchar[] IS NULL OR st.slug = ANY($30::varchar[]), false) AS in_set
  FROM items i
  JOIN rarities r ON r.id = i.rarity_id
  LEFT JOIN item_types it ON it.id = i.item_type_id
  LEFT JOIN armour_weights aw ON aw.id = i.armour_weight_id
  LEFT JOIN sets st ON st.id = i.set_id
  -- One expression for "has a vendor price", read by in_price and by the price facet. A subquery
  -- with no FROM is pulled up into its references, so a query that reads neither never runs it.
  CROSS JOIN LATERAL (SELECT EXISTS (
    SELECT 1 FROM item_sources src
    JOIN item_costs ico ON ico.item_source_id = src.id
    WHERE src.item_id = i.item_id) AS priced) pr
)
SELECT DISTINCT src.item_id,
       sc.slug AS section_slug, sc.name AS section_name, sc.sort_order AS section_sort,
       coalesce(sr.slug, '')::varchar AS region_slug, coalesce(sr.name, '')::varchar AS region_name,
       coalesce(sr.sort_order, 0)::integer AS region_sort,
       coalesce(sm.slug, '')::varchar AS map_slug, coalesce(sm.name, '')::varchar AS map_name,
       -- The row's own place; the service draws its whole ancestry from ListPlaceHierarchy.
       coalesce(p.slug, '')::varchar AS place_slug, coalesce(p.name, '')::varchar AS place_name,
       coalesce(sb.slug, '')::varchar AS boss_slug, coalesce(sb.name, '')::varchar AS boss_name,
       coalesce(sv.slug, '')::varchar AS vendor_slug, coalesce(sv.name, '')::varchar AS vendor_name,
       -- quests.name is deliberately NULL (the real name is unknown); the armory's label is what it said.
       coalesce(sq.slug, '')::varchar AS quest_slug, coalesce(sq.name, sq.armory_label, '')::varchar AS quest_name,
       coalesce(sct.slug, '')::varchar AS container_slug, coalesce(sct.name, '')::varchar AS container_name,
       coalesce(sag.slug, '')::varchar AS group_slug,
       -- Where on its map the row's location is (AoC>TV's coordinates). The panel shows a branch's
       -- only when every row of it has the same ones (Pierre, 2026-10-02; AOC-068).
       coalesce(src.coords, '')::varchar AS coords,
       -- Whether the item passes every other filter. The tree's SHAPE is every row of the tab, so a
       -- branch the filters empty is still listed with its 0, never hidden (the rail's rule); only
       -- the rows that match are counted.
       (f.in_base AND f.in_rarity AND f.in_slot AND f.in_weight AND f.in_class AND f.in_ilvl AND f.in_reqlvl AND f.in_price AND f.in_currency AND f.in_set)::boolean AS matches
FROM filtered f
JOIN item_sources src ON src.item_id = f.item_id
JOIN sections sc ON sc.id = src.section_id
JOIN source_tabs stb ON stb.id = sc.tab_id
LEFT JOIN places p ON p.id = src.place_id
LEFT JOIN regions sr ON sr.id = coalesce(p.region_id, src.region_id)
LEFT JOIN maps sm ON sm.id = coalesce(p.map_id, src.map_id)
LEFT JOIN bosses sb ON sb.id = src.boss_id
LEFT JOIN vendors sv ON sv.id = src.vendor_id
LEFT JOIN quests sq ON sq.id = src.quest_id
LEFT JOIN containers sct ON sct.id = src.container_id
LEFT JOIN acquisition_types sat ON sat.id = src.acquisition_type_id
LEFT JOIN acquisition_groups sag ON sag.id = sat.group_id
WHERE stb.slug = $1::varchar
ORDER BY src.item_id
`

type ListSourceTreeRowsParams struct {
	Tab             string
	ItemType        *string
	NameQuery       *string
	IDQuery         *int32
	PlaceSlugs      []string
	Region          *string
	Tier            *string
	Unchained       *bool
	Pvp             *bool
	SourceTab       *string
	SourceSection   *string
	SourceRegion    *string
	SourceMap       *string
	SourcePlaces    []string
	SourceBoss      *string
	SourceVendor    *string
	SourceQuest     *string
	SourceContainer *string
	SourceGroup     *string
	Rarities        []string
	EquipLocations  []string
	ArmourWeights   []string
	Classes         []string
	IlvlMin         *int32
	IlvlMax         *int32
	ReqlvlMin       *int32
	ReqlvlMax       *int32
	Price           *bool
	Currencies      []string
	Sets            []string
}

type ListSourceTreeRowsRow struct {
	ItemID        int32
	SectionSlug   string
	SectionName   string
	SectionSort   int32
	RegionSlug    string
	RegionName    string
	RegionSort    int32
	MapSlug       string
	MapName       string
	PlaceSlug     string
	PlaceName     string
	BossSlug      string
	BossName      string
	VendorSlug    string
	VendorName    string
	QuestSlug     string
	QuestName     string
	ContainerSlug string
	ContainerName string
	GroupSlug     string
	Coords        string
	Matches       bool
}

// The source panel's raw material (AOC-050): one row per (item, the levels of ONE of its source rows)
// in a tab, with whether the item passes every OTHER filter. The service builds the tab's tree from these and
// counts distinct items per node, so a node's count is what choosing it would leave -- the rail's
// rule (AOC-049) -- and the tree's own selection is left out by calling this with no source_*
// arguments. Levels are columns of our own tables; which of them a tab draws is source_tabs.groups.
// ” is "this row has no such level" (sqlc types a coalesced column as non-null).
func (q *Queries) ListSourceTreeRows(ctx context.Context, arg ListSourceTreeRowsParams) ([]ListSourceTreeRowsRow, error) {
	rows, err := q.db.Query(ctx, listSourceTreeRows,
		arg.Tab,
		arg.ItemType,
		arg.NameQuery,
		arg.IDQuery,
		arg.PlaceSlugs,
		arg.Region,
		arg.Tier,
		arg.Unchained,
		arg.Pvp,
		arg.SourceTab,
		arg.SourceSection,
		arg.SourceRegion,
		arg.SourceMap,
		arg.SourcePlaces,
		arg.SourceBoss,
		arg.SourceVendor,
		arg.SourceQuest,
		arg.SourceContainer,
		arg.SourceGroup,
		arg.Rarities,
		arg.EquipLocations,
		arg.ArmourWeights,
		arg.Classes,
		arg.IlvlMin,
		arg.IlvlMax,
		arg.ReqlvlMin,
		arg.ReqlvlMax,
		arg.Price,
		arg.Currencies,
		arg.Sets,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceTreeRowsRow{}
	for rows.Next() {
		var i ListSourceTreeRowsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.SectionSlug,
			&i.SectionName,
			&i.SectionSort,
			&i.RegionSlug,
			&i.RegionName,
			&i.RegionSort,
			&i.MapSlug,
			&i.MapName,
			&i.PlaceSlug,
			&i.PlaceName,
			&i.BossSlug,
			&i.BossName,
			&i.VendorSlug,
			&i.VendorName,
			&i.QuestSlug,
			&i.QuestName,
			&i.ContainerSlug,
			&i.ContainerName,
			&i.GroupSlug,
			&i.Coords,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
