// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: places.sql

package sqlcgen

import (
	"context"
)

const getPlaceBySlug = `-- name: GetPlaceBySlug :one
SELECT p.id, p.slug, p.name, p.unchained, p.region_id, r.name AS region_name, r.slug AS region_slug,
       p.map_id, m.name AS map_name, p.parent_place_id, parent.name AS parent_name,
       parent.slug AS parent_slug, c.slug AS confidence, p.source_note, p.open_question
FROM places p
JOIN regions r ON r.id = p.region_id
LEFT JOIN maps m ON m.id = p.map_id
LEFT JOIN places parent ON parent.id = p.parent_place_id
JOIN confidence_levels c ON c.id = p.confidence_id
WHERE p.slug = $1
`

type GetPlaceBySlugRow struct {
	ID            int32
	Slug          string
	Name          string
	Unchained     bool
	RegionID      int32
	RegionName    string
	RegionSlug    string
	MapID         *int32
	MapName       *string
	ParentPlaceID *int32
	ParentName    *string
	ParentSlug    *string
	Confidence    string
	SourceNote    string
	OpenQuestion  *string
}

func (q *Queries) GetPlaceBySlug(ctx context.Context, slug string) (GetPlaceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPlaceBySlug, slug)
	var i GetPlaceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Unchained,
		&i.RegionID,
		&i.RegionName,
		&i.RegionSlug,
		&i.MapID,
		&i.MapName,
		&i.ParentPlaceID,
		&i.ParentName,
		&i.ParentSlug,
		&i.Confidence,
		&i.SourceNote,
		&i.OpenQuestion,
	)
	return i, err
}

const listBosses = `-- name: ListBosses :many
SELECT b.id, b.slug, b.name, b.place_id, p.name AS place_name, b.map_id, m.name AS map_name,
       b.region_id, r.name AS region_name, c.slug AS confidence, b.source_note, b.open_question
FROM bosses b
LEFT JOIN places p ON p.id = b.place_id
LEFT JOIN maps m ON m.id = b.map_id
LEFT JOIN regions r ON r.id = b.region_id
JOIN confidence_levels c ON c.id = b.confidence_id
ORDER BY b.name
`

type ListBossesRow struct {
	ID           int32
	Slug         string
	Name         string
	PlaceID      *int32
	PlaceName    *string
	MapID        *int32
	MapName      *string
	RegionID     *int32
	RegionName   *string
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

func (q *Queries) ListBosses(ctx context.Context) ([]ListBossesRow, error) {
	rows, err := q.db.Query(ctx, listBosses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBossesRow{}
	for rows.Next() {
		var i ListBossesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PlaceID,
			&i.PlaceName,
			&i.MapID,
			&i.MapName,
			&i.RegionID,
			&i.RegionName,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBossesInPlace = `-- name: ListBossesInPlace :many
SELECT b.id, b.slug, b.name, c.slug AS confidence, b.source_note, b.open_question
FROM bosses b
JOIN confidence_levels c ON c.id = b.confidence_id
WHERE b.place_id = $1
ORDER BY b.name
`

type ListBossesInPlaceRow struct {
	ID           int32
	Slug         string
	Name         string
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

func (q *Queries) ListBossesInPlace(ctx context.Context, placeID *int32) ([]ListBossesInPlaceRow, error) {
	rows, err := q.db.Query(ctx, listBossesInPlace, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBossesInPlaceRow{}
	for rows.Next() {
		var i ListBossesInPlaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfidenceLevels = `-- name: ListConfidenceLevels :many
SELECT id, slug, name, sort_order FROM confidence_levels ORDER BY sort_order
`

func (q *Queries) ListConfidenceLevels(ctx context.Context) ([]ConfidenceLevel, error) {
	rows, err := q.db.Query(ctx, listConfidenceLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfidenceLevel{}
	for rows.Next() {
		var i ConfidenceLevel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainers = `-- name: ListContainers :many
SELECT co.id, co.slug, co.name, c.slug AS confidence, co.source_note, co.open_question
FROM containers co JOIN confidence_levels c ON c.id = co.confidence_id
ORDER BY co.name
`

type ListContainersRow struct {
	ID           int32
	Slug         string
	Name         string
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

func (q *Queries) ListContainers(ctx context.Context) ([]ListContainersRow, error) {
	rows, err := q.db.Query(ctx, listContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContainersRow{}
	for rows.Next() {
		var i ListContainersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaps = `-- name: ListMaps :many
SELECT m.id, m.slug, m.name, m.region_id, r.name AS region_name,
       c.slug AS confidence, m.source_note, m.open_question
FROM maps m
LEFT JOIN regions r ON r.id = m.region_id
JOIN confidence_levels c ON c.id = m.confidence_id
ORDER BY r.sort_order NULLS LAST, m.name
`

type ListMapsRow struct {
	ID           int32
	Slug         string
	Name         string
	RegionID     *int32
	RegionName   *string
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

func (q *Queries) ListMaps(ctx context.Context) ([]ListMapsRow, error) {
	rows, err := q.db.Query(ctx, listMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMapsRow{}
	for rows.Next() {
		var i ListMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.RegionID,
			&i.RegionName,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenQuestions = `-- name: ListOpenQuestions :many
SELECT 'place' AS entity, slug, name, open_question FROM places WHERE open_question IS NOT NULL
UNION ALL
SELECT 'boss', slug, name, open_question FROM bosses WHERE open_question IS NOT NULL
UNION ALL
SELECT 'map', slug, name, open_question FROM maps WHERE open_question IS NOT NULL
UNION ALL
SELECT 'region', slug, name, open_question FROM regions WHERE open_question IS NOT NULL
UNION ALL
SELECT 'quest', slug, armory_label, open_question FROM quests WHERE open_question IS NOT NULL
UNION ALL
SELECT 'container', slug, name, open_question FROM containers WHERE open_question IS NOT NULL
ORDER BY 1, 2
`

type ListOpenQuestionsRow struct {
	Entity       string
	Slug         string
	Name         string
	OpenQuestion *string
}

// ⭐ THE LIST OF THINGS TO ASK PIERRE, in one query rather than six greps. Every entity that
// carries an unresolved question about the game, with what the question is. AOC-009 seeds ten of
// these deliberately: a blank field and a recorded doubt are both better than a confident guess.
func (q *Queries) ListOpenQuestions(ctx context.Context) ([]ListOpenQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenQuestionsRow{}
	for rows.Next() {
		var i ListOpenQuestionsRow
		if err := rows.Scan(
			&i.Entity,
			&i.Slug,
			&i.Name,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT p.id, p.slug, p.name, p.unchained, p.region_id, r.name AS region_name,
       p.map_id, m.name AS map_name, p.parent_place_id, parent.name AS parent_name,
       c.slug AS confidence, p.source_note, p.open_question
FROM places p
JOIN regions r ON r.id = p.region_id
LEFT JOIN maps m ON m.id = p.map_id
LEFT JOIN places parent ON parent.id = p.parent_place_id
JOIN confidence_levels c ON c.id = p.confidence_id
ORDER BY r.sort_order, m.name NULLS FIRST, p.name
`

type ListPlacesRow struct {
	ID            int32
	Slug          string
	Name          string
	Unchained     bool
	RegionID      int32
	RegionName    string
	MapID         *int32
	MapName       *string
	ParentPlaceID *int32
	ParentName    *string
	Confidence    string
	SourceNote    string
	OpenQuestion  *string
}

// The whole browse tree in one read: 86 rows, so the Armory page's filter needs no second query.
func (q *Queries) ListPlaces(ctx context.Context) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesRow{}
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Unchained,
			&i.RegionID,
			&i.RegionName,
			&i.MapID,
			&i.MapName,
			&i.ParentPlaceID,
			&i.ParentName,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesInPlace = `-- name: ListPlacesInPlace :many
SELECT p.id, p.slug, p.name, p.unchained, c.slug AS confidence, p.open_question
FROM places p
JOIN confidence_levels c ON c.id = p.confidence_id
WHERE p.parent_place_id = $1
ORDER BY p.name
`

type ListPlacesInPlaceRow struct {
	ID           int32
	Slug         string
	Name         string
	Unchained    bool
	Confidence   string
	OpenQuestion *string
}

// The two complexes: House of Crom's page lists its two dungeons, Warmonk Monastery's its three.
func (q *Queries) ListPlacesInPlace(ctx context.Context, parentPlaceID *int32) ([]ListPlacesInPlaceRow, error) {
	rows, err := q.db.Query(ctx, listPlacesInPlace, parentPlaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesInPlaceRow{}
	for rows.Next() {
		var i ListPlacesInPlaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Unchained,
			&i.Confidence,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuests = `-- name: ListQuests :many
SELECT q.id, q.slug, q.armory_label, q.name, q.region_id, r.name AS region_name,
       q.map_id, m.name AS map_name, c.slug AS confidence, q.source_note, q.open_question
FROM quests q
LEFT JOIN regions r ON r.id = q.region_id
LEFT JOIN maps m ON m.id = q.map_id
JOIN confidence_levels c ON c.id = q.confidence_id
ORDER BY q.armory_label
`

type ListQuestsRow struct {
	ID           int32
	Slug         string
	ArmoryLabel  string
	Name         *string
	RegionID     *int32
	RegionName   *string
	MapID        *int32
	MapName      *string
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

// `name` is NULL for all 51 — armory_label is what the source actually recorded.
func (q *Queries) ListQuests(ctx context.Context) ([]ListQuestsRow, error) {
	rows, err := q.db.Query(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestsRow{}
	for rows.Next() {
		var i ListQuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ArmoryLabel,
			&i.Name,
			&i.RegionID,
			&i.RegionName,
			&i.MapID,
			&i.MapName,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many

SELECT r.id, r.slug, r.name, r.sort_order, c.slug AS confidence, r.source_note, r.open_question
FROM regions r JOIN confidence_levels c ON c.id = r.confidence_id
ORDER BY r.sort_order
`

type ListRegionsRow struct {
	ID           int32
	Slug         string
	Name         string
	SortOrder    int32
	Confidence   string
	SourceNote   string
	OpenQuestion *string
}

// Read queries for the place entities — the browse tree behind the Armory page's location filter
// and, later, every boss page's breadcrumb (AOC-009).
//
// ⭐ WHY THESE ARE QUERIES AND NOT A GO MAP. Same reason as taxonomy.sql: region -> map -> place
// is data, not code. It already disagrees with itself in three places (Kuthchemes, the two
// Unchained variants the armory files under the wrong map), and those disagreements are ROWS
// carrying their own open_question — a Go literal could hold the names but never the provenance.
//
// ⚠️ Every list here returns confidence and open_question with the row. A page that shows a place
// without being able to show how sure we are cannot honour sourcing-standards § 3, where a
// `disputed` fact renders with a ⚠️ and both versions. Dropping them from the SELECT is how that
// rule quietly stops being enforced.
func (q *Queries) ListRegions(ctx context.Context) ([]ListRegionsRow, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionsRow{}
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
			&i.Confidence,
			&i.SourceNote,
			&i.OpenQuestion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
