// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package sqlcgen

import (
	"context"
)

const countProbes = `-- name: CountProbes :one
SELECT count(*) FROM schema_probe
`

func (q *Queries) CountProbes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProbes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProbe = `-- name: GetProbe :one

SELECT id, note, created_at FROM schema_probe WHERE id = $1
`

// Queries against the probe table. They exist to prove the sqlc chain compiles and runs;
// AOC-009/AOC-010 replace them with real ones.
func (q *Queries) GetProbe(ctx context.Context, id int32) (SchemaProbe, error) {
	row := q.db.QueryRow(ctx, getProbe, id)
	var i SchemaProbe
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}
