// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package sqlcgen

import (
	"context"
)

const listAcquisitionTypes = `-- name: ListAcquisitionTypes :many
SELECT id, slug, name FROM acquisition_types ORDER BY name
`

func (q *Queries) ListAcquisitionTypes(ctx context.Context) ([]AcquisitionType, error) {
	rows, err := q.db.Query(ctx, listAcquisitionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcquisitionType{}
	for rows.Next() {
		var i AcquisitionType
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchetypes = `-- name: ListArchetypes :many

SELECT id, slug, name FROM archetypes ORDER BY name
`

// Read queries for the taxonomy tables — the Armory page's filter lists (AOC-009).
//
// ⭐ WHY THESE ARE QUERIES AND NOT A GO SLICE. Every "kind of thing" in this product is a row
// (DECISIONS.md, 2026-09-12). A filter list built from a Go constant drifts from the database the
// first time a currency is added, and the page then offers an option nothing matches — or worse,
// omits one that does. These read the same rows the items reference.
//
// Ordered taxonomies come back in sort_order; the rest alphabetically, because that is the order a
// filter list is read in.
func (q *Queries) ListArchetypes(ctx context.Context) ([]Archetype, error) {
	rows, err := q.db.Query(ctx, listArchetypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Archetype{}
	for rows.Next() {
		var i Archetype
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArmourWeights = `-- name: ListArmourWeights :many
SELECT id, slug, name, sort_order FROM armour_weights ORDER BY sort_order
`

func (q *Queries) ListArmourWeights(ctx context.Context) ([]ArmourWeight, error) {
	rows, err := q.db.Query(ctx, listArmourWeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArmourWeight{}
	for rows.Next() {
		var i ArmourWeight
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindings = `-- name: ListBindings :many
SELECT id, slug, name FROM bindings ORDER BY name
`

func (q *Queries) ListBindings(ctx context.Context) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Binding{}
	for rows.Next() {
		var i Binding
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT c.id, c.slug, c.name, c.archetype_id, a.name AS archetype_name, c.max_armour_weight
FROM classes c JOIN archetypes a ON a.id = c.archetype_id
ORDER BY a.name, c.name
`

type ListClassesRow struct {
	ID              int32
	Slug            string
	Name            string
	ArchetypeID     int32
	ArchetypeName   string
	MaxArmourWeight *int32
}

func (q *Queries) ListClasses(ctx context.Context) ([]ListClassesRow, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesRow{}
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ArchetypeID,
			&i.ArchetypeName,
			&i.MaxArmourWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, slug, name FROM currencies ORDER BY name
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipLocations = `-- name: ListEquipLocations :many
SELECT id, slug, name FROM equip_locations ORDER BY name
`

func (q *Queries) ListEquipLocations(ctx context.Context) ([]EquipLocation, error) {
	rows, err := q.db.Query(ctx, listEquipLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EquipLocation{}
	for rows.Next() {
		var i EquipLocation
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactions = `-- name: ListFactions :many
SELECT id, slug, name FROM factions ORDER BY name
`

func (q *Queries) ListFactions(ctx context.Context) ([]Faction, error) {
	rows, err := q.db.Query(ctx, listFactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Faction{}
	for rows.Next() {
		var i Faction
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, slug, name FROM item_types ORDER BY name
`

func (q *Queries) ListItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.Query(ctx, listItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemType{}
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRarities = `-- name: ListRarities :many
SELECT id, slug, name, sort_order FROM rarities ORDER BY sort_order
`

func (q *Queries) ListRarities(ctx context.Context) ([]Rarity, error) {
	rows, err := q.db.Query(ctx, listRarities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rarity{}
	for rows.Next() {
		var i Rarity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many
SELECT id, slug, name, sort_order FROM tiers ORDER BY sort_order
`

func (q *Queries) ListTiers(ctx context.Context) ([]Tier, error) {
	rows, err := q.db.Query(ctx, listTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tier{}
	for rows.Next() {
		var i Tier
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
