-- aoc_api — the CURRENT database schema, as a living document.
--
-- GENERATED by `make schema-dump` from a migrated database. Do not hand-edit:
-- run the migration, then regenerate, and commit both together.
--
-- NOTE for AOC-010, carried from AOC-016 and AOC-017:
--   * `spell_effect` is its own column, separate from an item's `stats`. A build or
--     armour calculator sums `stats` and must never sum `spell_effect`.
--   * `vendor` is its own column, separate from `boss_or_npc`.
--   * `binding` is a 3-row lookup table, not a free-text column.
--   * `coords` is overloaded in the source data: on a quest row it is where the
--     quest-giver stands, not a dungeon entrance. Label which it is.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_probe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_probe (
    id integer NOT NULL,
    note text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: schema_probe schema_probe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_probe
    ADD CONSTRAINT schema_probe_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--


