-- aoc_api — the CURRENT database schema, as a living document.
--
-- GENERATED by `make schema-dump` from a migrated database. Do not hand-edit:
-- run the migration, then regenerate, and commit both together.
--
-- NOTE for AOC-010, carried from AOC-016 and AOC-017:
--   * `spell_effect` is its own column, separate from an item's `stats`. A build or
--     armour calculator sums `stats` and must never sum `spell_effect`.
--   * `vendor` is its own column, separate from `boss_or_npc`.
--   * `binding` is a 3-row lookup table, not a free-text column.
--   * `coords` is overloaded in the source data: on a quest row it is where the
--     quest-giver stands, not a dungeon entrance. Label which it is.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acquisition_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisition_types (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: acquisition_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.acquisition_types_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: acquisition_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.acquisition_types_id_seq OWNED BY public.acquisition_types.id;


--
-- Name: archetypes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.archetypes (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: archetypes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.archetypes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: archetypes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.archetypes_id_seq OWNED BY public.archetypes.id;


--
-- Name: armour_weights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.armour_weights (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: armour_weights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.armour_weights_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: armour_weights_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.armour_weights_id_seq OWNED BY public.armour_weights.id;


--
-- Name: bindings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bindings (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: bindings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bindings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bindings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bindings_id_seq OWNED BY public.bindings.id;


--
-- Name: bosses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bosses (
    id integer NOT NULL,
    place_id integer,
    map_id integer,
    region_id integer,
    slug character varying(96) NOT NULL,
    name character varying(96) NOT NULL,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: bosses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bosses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bosses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bosses_id_seq OWNED BY public.bosses.id;


--
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id integer NOT NULL,
    archetype_id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    max_armour_weight integer
);


--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.classes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: classes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.classes_id_seq OWNED BY public.classes.id;


--
-- Name: confidence_levels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.confidence_levels (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: confidence_levels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.confidence_levels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: confidence_levels_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.confidence_levels_id_seq OWNED BY public.confidence_levels.id;


--
-- Name: containers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.containers (
    id integer NOT NULL,
    slug character varying(96) NOT NULL,
    name character varying(96) NOT NULL,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: containers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.containers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: containers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.containers_id_seq OWNED BY public.containers.id;


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencies (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: currencies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.currencies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: currencies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.currencies_id_seq OWNED BY public.currencies.id;


--
-- Name: equip_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equip_locations (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: equip_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equip_locations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equip_locations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equip_locations_id_seq OWNED BY public.equip_locations.id;


--
-- Name: factions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factions (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: factions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.factions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: factions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.factions_id_seq OWNED BY public.factions.id;


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_classes (
    item_id integer NOT NULL,
    class_id integer NOT NULL
);


--
-- Name: item_costs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_costs (
    id bigint NOT NULL,
    item_source_id bigint NOT NULL,
    currency_id integer NOT NULL,
    amount numeric(12,2) NOT NULL
);


--
-- Name: item_costs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_costs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_costs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_costs_id_seq OWNED BY public.item_costs.id;


--
-- Name: item_equip_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_equip_locations (
    item_id integer NOT NULL,
    equip_location_id integer NOT NULL
);


--
-- Name: item_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_sources (
    id bigint NOT NULL,
    item_id integer NOT NULL,
    acquisition_type_id integer,
    place_id integer,
    boss_id integer,
    vendor_id integer,
    quest_id integer,
    container_id integer,
    region_id integer,
    map_id integer,
    tier_id integer,
    is_raid boolean DEFAULT false NOT NULL,
    coords character varying(64),
    section_raw character varying(300),
    unchained boolean DEFAULT false NOT NULL,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300),
    CONSTRAINT item_sources_boss_and_vendor_not_both CHECK (((boss_id IS NULL) OR (vendor_id IS NULL)))
);


--
-- Name: item_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_sources_id_seq OWNED BY public.item_sources.id;


--
-- Name: item_spell_effects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_spell_effects (
    id bigint NOT NULL,
    item_id integer NOT NULL,
    stat character varying(64) NOT NULL,
    value numeric(8,2) NOT NULL,
    sign smallint NOT NULL,
    unit character varying(16) NOT NULL,
    damage_type character varying(32),
    pvp boolean DEFAULT false NOT NULL,
    CONSTRAINT item_spell_effects_sign_check CHECK ((sign = ANY (ARRAY['-1'::integer, 1])))
);


--
-- Name: item_spell_effects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_spell_effects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_spell_effects_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_spell_effects_id_seq OWNED BY public.item_spell_effects.id;


--
-- Name: item_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_stats (
    id bigint NOT NULL,
    item_id integer NOT NULL,
    stat character varying(64) NOT NULL,
    value numeric(8,2) NOT NULL,
    sign smallint NOT NULL,
    unit character varying(16) NOT NULL,
    damage_type character varying(32),
    pvp boolean DEFAULT false NOT NULL,
    CONSTRAINT item_stats_sign_check CHECK ((sign = ANY (ARRAY['-1'::integer, 1])))
);


--
-- Name: item_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_stats_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_stats_id_seq OWNED BY public.item_stats.id;


--
-- Name: item_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_types (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL
);


--
-- Name: item_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_types_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_types_id_seq OWNED BY public.item_types.id;


--
-- Name: items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.items (
    item_id integer NOT NULL,
    slug character varying(160) NOT NULL,
    name character varying(160) NOT NULL,
    rarity_id integer NOT NULL,
    item_type_id integer,
    slot_fit_id integer,
    armour_weight_id integer,
    binding_id integer,
    item_level integer,
    requires_level integer,
    armor integer,
    critigation integer,
    dps numeric(6,2),
    damage_range character varying(32),
    set_id integer,
    faction_id integer,
    faction_rank integer,
    pvp_source boolean DEFAULT false NOT NULL,
    has_pvp_stats boolean DEFAULT false NOT NULL,
    pvp_penalty boolean DEFAULT false NOT NULL,
    no_longer_available character varying(300),
    tooltip_image character varying(500),
    tooltip_source_url character varying(500),
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: maps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maps (
    id integer NOT NULL,
    region_id integer,
    slug character varying(64) NOT NULL,
    name character varying(96) NOT NULL,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: maps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.maps_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: maps_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.maps_id_seq OWNED BY public.maps.id;


--
-- Name: places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.places (
    id integer NOT NULL,
    region_id integer NOT NULL,
    map_id integer,
    parent_place_id integer,
    slug character varying(96) NOT NULL,
    name character varying(96) NOT NULL,
    unchained boolean DEFAULT false NOT NULL,
    armory_instance character varying(96),
    armory_dungeon character varying(96),
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: places_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.places_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: places_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.places_id_seq OWNED BY public.places.id;


--
-- Name: quests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quests (
    id integer NOT NULL,
    region_id integer,
    map_id integer,
    slug character varying(96) NOT NULL,
    armory_label character varying(96) NOT NULL,
    name character varying(96),
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: quests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.quests_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: quests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.quests_id_seq OWNED BY public.quests.id;


--
-- Name: rarities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rarities (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: rarities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rarities_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rarities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rarities_id_seq OWNED BY public.rarities.id;


--
-- Name: regions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.regions (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.regions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: regions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.regions_id_seq OWNED BY public.regions.id;


--
-- Name: schema_probe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_probe (
    id integer NOT NULL,
    note text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sets (
    id integer NOT NULL,
    slug character varying(120) NOT NULL,
    name character varying(120) NOT NULL,
    class_id integer,
    set_armour_weight_id integer,
    declared_piece_count integer,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: sets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sets_id_seq OWNED BY public.sets.id;


--
-- Name: slot_fits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.slot_fits (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: slot_fits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.slot_fits_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: slot_fits_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.slot_fits_id_seq OWNED BY public.slot_fits.id;


--
-- Name: tiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tiers (
    id integer NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: tiers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tiers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tiers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tiers_id_seq OWNED BY public.tiers.id;


--
-- Name: vendors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendors (
    id integer NOT NULL,
    slug character varying(120) NOT NULL,
    name character varying(120) NOT NULL,
    place_id integer,
    confidence_id integer NOT NULL,
    source_note character varying(300) NOT NULL,
    open_question character varying(300)
);


--
-- Name: vendors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vendors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vendors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.vendors_id_seq OWNED BY public.vendors.id;


--
-- Name: acquisition_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_types ALTER COLUMN id SET DEFAULT nextval('public.acquisition_types_id_seq'::regclass);


--
-- Name: archetypes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.archetypes ALTER COLUMN id SET DEFAULT nextval('public.archetypes_id_seq'::regclass);


--
-- Name: armour_weights id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armour_weights ALTER COLUMN id SET DEFAULT nextval('public.armour_weights_id_seq'::regclass);


--
-- Name: bindings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bindings ALTER COLUMN id SET DEFAULT nextval('public.bindings_id_seq'::regclass);


--
-- Name: bosses id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses ALTER COLUMN id SET DEFAULT nextval('public.bosses_id_seq'::regclass);


--
-- Name: classes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes ALTER COLUMN id SET DEFAULT nextval('public.classes_id_seq'::regclass);


--
-- Name: confidence_levels id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confidence_levels ALTER COLUMN id SET DEFAULT nextval('public.confidence_levels_id_seq'::regclass);


--
-- Name: containers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers ALTER COLUMN id SET DEFAULT nextval('public.containers_id_seq'::regclass);


--
-- Name: currencies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies ALTER COLUMN id SET DEFAULT nextval('public.currencies_id_seq'::regclass);


--
-- Name: equip_locations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equip_locations ALTER COLUMN id SET DEFAULT nextval('public.equip_locations_id_seq'::regclass);


--
-- Name: factions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factions ALTER COLUMN id SET DEFAULT nextval('public.factions_id_seq'::regclass);


--
-- Name: item_costs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs ALTER COLUMN id SET DEFAULT nextval('public.item_costs_id_seq'::regclass);


--
-- Name: item_sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources ALTER COLUMN id SET DEFAULT nextval('public.item_sources_id_seq'::regclass);


--
-- Name: item_spell_effects id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spell_effects ALTER COLUMN id SET DEFAULT nextval('public.item_spell_effects_id_seq'::regclass);


--
-- Name: item_stats id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_stats ALTER COLUMN id SET DEFAULT nextval('public.item_stats_id_seq'::regclass);


--
-- Name: item_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_types ALTER COLUMN id SET DEFAULT nextval('public.item_types_id_seq'::regclass);


--
-- Name: maps id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps ALTER COLUMN id SET DEFAULT nextval('public.maps_id_seq'::regclass);


--
-- Name: places id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places ALTER COLUMN id SET DEFAULT nextval('public.places_id_seq'::regclass);


--
-- Name: quests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests ALTER COLUMN id SET DEFAULT nextval('public.quests_id_seq'::regclass);


--
-- Name: rarities id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rarities ALTER COLUMN id SET DEFAULT nextval('public.rarities_id_seq'::regclass);


--
-- Name: regions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions ALTER COLUMN id SET DEFAULT nextval('public.regions_id_seq'::regclass);


--
-- Name: sets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets ALTER COLUMN id SET DEFAULT nextval('public.sets_id_seq'::regclass);


--
-- Name: slot_fits id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_fits ALTER COLUMN id SET DEFAULT nextval('public.slot_fits_id_seq'::regclass);


--
-- Name: tiers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiers ALTER COLUMN id SET DEFAULT nextval('public.tiers_id_seq'::regclass);


--
-- Name: vendors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors ALTER COLUMN id SET DEFAULT nextval('public.vendors_id_seq'::regclass);


--
-- Name: acquisition_types acquisition_types_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_types
    ADD CONSTRAINT acquisition_types_name_key UNIQUE (name);


--
-- Name: acquisition_types acquisition_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_types
    ADD CONSTRAINT acquisition_types_pkey PRIMARY KEY (id);


--
-- Name: acquisition_types acquisition_types_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition_types
    ADD CONSTRAINT acquisition_types_slug_key UNIQUE (slug);


--
-- Name: archetypes archetypes_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.archetypes
    ADD CONSTRAINT archetypes_name_key UNIQUE (name);


--
-- Name: archetypes archetypes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.archetypes
    ADD CONSTRAINT archetypes_pkey PRIMARY KEY (id);


--
-- Name: archetypes archetypes_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.archetypes
    ADD CONSTRAINT archetypes_slug_key UNIQUE (slug);


--
-- Name: armour_weights armour_weights_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armour_weights
    ADD CONSTRAINT armour_weights_name_key UNIQUE (name);


--
-- Name: armour_weights armour_weights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armour_weights
    ADD CONSTRAINT armour_weights_pkey PRIMARY KEY (id);


--
-- Name: armour_weights armour_weights_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.armour_weights
    ADD CONSTRAINT armour_weights_slug_key UNIQUE (slug);


--
-- Name: bindings bindings_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bindings
    ADD CONSTRAINT bindings_name_key UNIQUE (name);


--
-- Name: bindings bindings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bindings
    ADD CONSTRAINT bindings_pkey PRIMARY KEY (id);


--
-- Name: bindings bindings_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bindings
    ADD CONSTRAINT bindings_slug_key UNIQUE (slug);


--
-- Name: bosses bosses_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_name_key UNIQUE (name);


--
-- Name: bosses bosses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_pkey PRIMARY KEY (id);


--
-- Name: bosses bosses_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_slug_key UNIQUE (slug);


--
-- Name: classes classes_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_name_key UNIQUE (name);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: classes classes_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_slug_key UNIQUE (slug);


--
-- Name: confidence_levels confidence_levels_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confidence_levels
    ADD CONSTRAINT confidence_levels_name_key UNIQUE (name);


--
-- Name: confidence_levels confidence_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confidence_levels
    ADD CONSTRAINT confidence_levels_pkey PRIMARY KEY (id);


--
-- Name: confidence_levels confidence_levels_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confidence_levels
    ADD CONSTRAINT confidence_levels_slug_key UNIQUE (slug);


--
-- Name: containers containers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_name_key UNIQUE (name);


--
-- Name: containers containers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_pkey PRIMARY KEY (id);


--
-- Name: containers containers_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_slug_key UNIQUE (slug);


--
-- Name: currencies currencies_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_name_key UNIQUE (name);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: currencies currencies_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_slug_key UNIQUE (slug);


--
-- Name: equip_locations equip_locations_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equip_locations
    ADD CONSTRAINT equip_locations_name_key UNIQUE (name);


--
-- Name: equip_locations equip_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equip_locations
    ADD CONSTRAINT equip_locations_pkey PRIMARY KEY (id);


--
-- Name: equip_locations equip_locations_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equip_locations
    ADD CONSTRAINT equip_locations_slug_key UNIQUE (slug);


--
-- Name: factions factions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factions
    ADD CONSTRAINT factions_name_key UNIQUE (name);


--
-- Name: factions factions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factions
    ADD CONSTRAINT factions_pkey PRIMARY KEY (id);


--
-- Name: factions factions_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factions
    ADD CONSTRAINT factions_slug_key UNIQUE (slug);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: item_classes item_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_classes
    ADD CONSTRAINT item_classes_pkey PRIMARY KEY (item_id, class_id);


--
-- Name: item_costs item_costs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT item_costs_pkey PRIMARY KEY (id);


--
-- Name: item_equip_locations item_equip_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_equip_locations
    ADD CONSTRAINT item_equip_locations_pkey PRIMARY KEY (item_id, equip_location_id);


--
-- Name: item_sources item_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_pkey PRIMARY KEY (id);


--
-- Name: item_spell_effects item_spell_effects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spell_effects
    ADD CONSTRAINT item_spell_effects_pkey PRIMARY KEY (id);


--
-- Name: item_stats item_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_stats
    ADD CONSTRAINT item_stats_pkey PRIMARY KEY (id);


--
-- Name: item_types item_types_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_types
    ADD CONSTRAINT item_types_name_key UNIQUE (name);


--
-- Name: item_types item_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_types
    ADD CONSTRAINT item_types_pkey PRIMARY KEY (id);


--
-- Name: item_types item_types_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_types
    ADD CONSTRAINT item_types_slug_key UNIQUE (slug);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (item_id);


--
-- Name: maps maps_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_name_key UNIQUE (name);


--
-- Name: maps maps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_pkey PRIMARY KEY (id);


--
-- Name: maps maps_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_slug_key UNIQUE (slug);


--
-- Name: places places_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_name_key UNIQUE (name);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: places places_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_slug_key UNIQUE (slug);


--
-- Name: quests quests_armory_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_armory_label_key UNIQUE (armory_label);


--
-- Name: quests quests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_pkey PRIMARY KEY (id);


--
-- Name: quests quests_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_slug_key UNIQUE (slug);


--
-- Name: rarities rarities_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rarities
    ADD CONSTRAINT rarities_name_key UNIQUE (name);


--
-- Name: rarities rarities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rarities
    ADD CONSTRAINT rarities_pkey PRIMARY KEY (id);


--
-- Name: rarities rarities_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rarities
    ADD CONSTRAINT rarities_slug_key UNIQUE (slug);


--
-- Name: regions regions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_name_key UNIQUE (name);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: regions regions_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_slug_key UNIQUE (slug);


--
-- Name: schema_probe schema_probe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_probe
    ADD CONSTRAINT schema_probe_pkey PRIMARY KEY (id);


--
-- Name: sets sets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_pkey PRIMARY KEY (id);


--
-- Name: sets sets_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_slug_key UNIQUE (slug);


--
-- Name: slot_fits slot_fits_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_fits
    ADD CONSTRAINT slot_fits_name_key UNIQUE (name);


--
-- Name: slot_fits slot_fits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_fits
    ADD CONSTRAINT slot_fits_pkey PRIMARY KEY (id);


--
-- Name: slot_fits slot_fits_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_fits
    ADD CONSTRAINT slot_fits_slug_key UNIQUE (slug);


--
-- Name: tiers tiers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiers
    ADD CONSTRAINT tiers_name_key UNIQUE (name);


--
-- Name: tiers tiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiers
    ADD CONSTRAINT tiers_pkey PRIMARY KEY (id);


--
-- Name: tiers tiers_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tiers
    ADD CONSTRAINT tiers_slug_key UNIQUE (slug);


--
-- Name: vendors vendors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_slug_key UNIQUE (slug);


--
-- Name: bosses_place_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bosses_place_id_idx ON public.bosses USING btree (place_id);


--
-- Name: item_classes_class_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_classes_class_id_idx ON public.item_classes USING btree (class_id);


--
-- Name: item_costs_currency_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_costs_currency_id_idx ON public.item_costs USING btree (currency_id);


--
-- Name: item_costs_item_source_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_costs_item_source_id_idx ON public.item_costs USING btree (item_source_id);


--
-- Name: item_equip_locations_equip_location_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_equip_locations_equip_location_id_idx ON public.item_equip_locations USING btree (equip_location_id);


--
-- Name: item_sources_item_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_sources_item_id_idx ON public.item_sources USING btree (item_id);


--
-- Name: item_sources_place_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_sources_place_id_idx ON public.item_sources USING btree (place_id) WHERE (place_id IS NOT NULL);


--
-- Name: item_spell_effects_item_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_spell_effects_item_id_idx ON public.item_spell_effects USING btree (item_id);


--
-- Name: item_stats_item_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_stats_item_id_idx ON public.item_stats USING btree (item_id);


--
-- Name: items_item_type_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_item_type_id_idx ON public.items USING btree (item_type_id);


--
-- Name: items_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_name_idx ON public.items USING btree (name);


--
-- Name: items_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_name_trgm_idx ON public.items USING gin (name public.gin_trgm_ops);


--
-- Name: items_rarity_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_rarity_id_idx ON public.items USING btree (rarity_id);


--
-- Name: items_set_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX items_set_id_idx ON public.items USING btree (set_id) WHERE (set_id IS NOT NULL);


--
-- Name: items_slug_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX items_slug_idx ON public.items USING btree (slug);


--
-- Name: places_armory_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX places_armory_key ON public.places USING btree (armory_instance, armory_dungeon) NULLS NOT DISTINCT WHERE ((armory_instance IS NOT NULL) OR (armory_dungeon IS NOT NULL));


--
-- Name: places_map_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX places_map_id_idx ON public.places USING btree (map_id);


--
-- Name: places_parent_place_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX places_parent_place_id_idx ON public.places USING btree (parent_place_id);


--
-- Name: places_region_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX places_region_id_idx ON public.places USING btree (region_id);


--
-- Name: bosses bosses_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: bosses bosses_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id);


--
-- Name: bosses bosses_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- Name: bosses bosses_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bosses
    ADD CONSTRAINT bosses_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: classes classes_archetype_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_archetype_id_fkey FOREIGN KEY (archetype_id) REFERENCES public.archetypes(id);


--
-- Name: classes classes_max_armour_weight_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_max_armour_weight_fkey FOREIGN KEY (max_armour_weight) REFERENCES public.armour_weights(id);


--
-- Name: containers containers_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: item_classes item_classes_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_classes
    ADD CONSTRAINT item_classes_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: item_classes item_classes_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_classes
    ADD CONSTRAINT item_classes_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE;


--
-- Name: item_costs item_costs_currency_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT item_costs_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- Name: item_costs item_costs_item_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT item_costs_item_source_id_fkey FOREIGN KEY (item_source_id) REFERENCES public.item_sources(id) ON DELETE CASCADE;


--
-- Name: item_equip_locations item_equip_locations_equip_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_equip_locations
    ADD CONSTRAINT item_equip_locations_equip_location_id_fkey FOREIGN KEY (equip_location_id) REFERENCES public.equip_locations(id);


--
-- Name: item_equip_locations item_equip_locations_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_equip_locations
    ADD CONSTRAINT item_equip_locations_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE;


--
-- Name: item_sources item_sources_acquisition_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_acquisition_type_id_fkey FOREIGN KEY (acquisition_type_id) REFERENCES public.acquisition_types(id);


--
-- Name: item_sources item_sources_boss_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_boss_id_fkey FOREIGN KEY (boss_id) REFERENCES public.bosses(id);


--
-- Name: item_sources item_sources_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: item_sources item_sources_container_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_container_id_fkey FOREIGN KEY (container_id) REFERENCES public.containers(id);


--
-- Name: item_sources item_sources_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE;


--
-- Name: item_sources item_sources_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id);


--
-- Name: item_sources item_sources_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- Name: item_sources item_sources_quest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_quest_id_fkey FOREIGN KEY (quest_id) REFERENCES public.quests(id);


--
-- Name: item_sources item_sources_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: item_sources item_sources_tier_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.tiers(id);


--
-- Name: item_sources item_sources_vendor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_sources
    ADD CONSTRAINT item_sources_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id);


--
-- Name: item_spell_effects item_spell_effects_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spell_effects
    ADD CONSTRAINT item_spell_effects_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE;


--
-- Name: item_stats item_stats_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_stats
    ADD CONSTRAINT item_stats_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE;


--
-- Name: items items_armour_weight_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_armour_weight_id_fkey FOREIGN KEY (armour_weight_id) REFERENCES public.armour_weights(id);


--
-- Name: items items_binding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_binding_id_fkey FOREIGN KEY (binding_id) REFERENCES public.bindings(id);


--
-- Name: items items_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: items items_faction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_faction_id_fkey FOREIGN KEY (faction_id) REFERENCES public.factions(id);


--
-- Name: items items_item_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_item_type_id_fkey FOREIGN KEY (item_type_id) REFERENCES public.item_types(id);


--
-- Name: items items_rarity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_rarity_id_fkey FOREIGN KEY (rarity_id) REFERENCES public.rarities(id);


--
-- Name: items items_set_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.sets(id);


--
-- Name: items items_slot_fit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_slot_fit_id_fkey FOREIGN KEY (slot_fit_id) REFERENCES public.slot_fits(id);


--
-- Name: maps maps_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: maps maps_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: places places_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: places places_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id);


--
-- Name: places places_parent_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_parent_place_id_fkey FOREIGN KEY (parent_place_id) REFERENCES public.places(id);


--
-- Name: places places_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: quests quests_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: quests quests_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id);


--
-- Name: quests quests_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: regions regions_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: sets sets_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: sets sets_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: sets sets_set_armour_weight_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_set_armour_weight_id_fkey FOREIGN KEY (set_armour_weight_id) REFERENCES public.armour_weights(id);


--
-- Name: vendors vendors_confidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_confidence_id_fkey FOREIGN KEY (confidence_id) REFERENCES public.confidence_levels(id);


--
-- Name: vendors vendors_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id);


--
-- PostgreSQL database dump complete
--


