package db_test

// The armory importer (AOC-011), against a real database.
//
// ⚠️ EVERY FIXTURE NAME IS OBVIOUSLY FAKE — "Test Blade Alpha", "Test Boss Gamma". The taxonomy
// VALUES are real because they must resolve against AOC-009's seeds, but nothing here invents a
// game fact (CLAUDE.md STEP ZERO).
//
// What these pin, in order of how much they would have hurt:
//  1. an unresolvable value aborts the transaction and leaves ZERO rows — the import never
//     half-writes and never guesses;
//  2. re-running changes nothing — the snapshot is regenerated by every data-quality ticket, so
//     this import WILL be run again;
//  3. the counts the importer reports are the counts in the database;
//  4. the two exclusions Pierre decided on actually exclude.

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/pierrehrt/aoc-api/internal/items"
)

// A small corpus exercising the shapes that matter: a two-hander (both slots), a ring (either
// slot), an item with no slot and no stats, a multi-source item, a quarantined source, an
// excluded item, and a source with two currencies.
const fixtureJSON = `[
{"item_id":9001,"name":"Test Blade Alpha","rarity":"Epic","item_type":"2HE",
 "pvp_source":false,"has_pvp_stats":false,"pvp_penalty":false,"classes":["Barbarian"],
 "armour_weight":null,"equip_location":"Main Hand, Off Hand","item_level":80,"requires_level":80,
 "armor":null,"critigation":null,"dps":157.1,"damage_range":"132-173",
 "stats":[{"stat":"Test Strength","value":78,"sign":1,"unit":"flat","damage_type":null,"pvp":false},
          {"stat":"Test Regen","value":4.5,"sign":1,"unit":"flat","damage_type":null,"pvp":false}],
 "spell_effect":[{"stat":"Test Sprint Drain","value":8,"sign":-1,"unit":"percent","damage_type":null,"pvp":false}],
 "set":"Test Set Omega","set_pieces":7,"faction":null,"faction_rank":null,
 "binding":"Binds when Picked Up","no_longer_available":false,
 "tooltip_image":"https://img.aoc-codex.app/armory/test_blade_alpha.jpg",
 "tooltip_source_url":"https://static.is-better-than.tv/armory/test_blade_alpha.jpg",
 "sources":[
  {"acquisition_type":"drop","acquisition_cost":[],"container":null,"unchained":false,
   "region":"Stygia","region_source":"pierre","map":null,"instance":null,"dungeon_or_raid":null,
   "boss_or_npc":null,"vendor":null,"quest":null,"is_raid":true,"coords":[387,639],
   "tier":"PvE 5","section_raw":"fixture","on_hold":false,"on_hold_reason":null},
  {"acquisition_type":"vendor","acquisition_cost":[{"currency":"Gold","amount":15},
                                                   {"currency":"Rare Trophy","amount":160}],
   "container":null,"unchained":false,"region":"Stygia","region_source":"derived","map":null,
   "instance":null,"dungeon_or_raid":null,"boss_or_npc":null,"vendor":"Test Vendor Delta",
   "quest":null,"is_raid":false,"coords":null,"tier":null,"section_raw":"fixture",
   "on_hold":false,"on_hold_reason":null},
  {"acquisition_type":"drop","acquisition_cost":[],"container":null,"unchained":false,
   "region":"Stygia","region_source":"derived","map":null,"instance":null,"dungeon_or_raid":null,
   "boss_or_npc":"Vistrix","vendor":null,"quest":null,"is_raid":true,"coords":null,
   "tier":"PvE 5","section_raw":"fixture","on_hold":true,"on_hold_reason":"fixture: wrong boss"}]},

{"item_id":9002,"name":"Test Ring Beta","rarity":"Rare","item_type":"Back",
 "pvp_source":false,"has_pvp_stats":false,"pvp_penalty":false,"classes":[],
 "armour_weight":null,"equip_location":"Left/Right Finger","item_level":70,"requires_level":70,
 "armor":null,"critigation":null,"dps":null,"damage_range":null,
 "stats":[],"spell_effect":[],"set":null,"set_pieces":null,"faction":null,"faction_rank":null,
 "binding":null,"no_longer_available":false,"tooltip_image":null,"tooltip_source_url":null,
 "sources":[]},

{"item_id":9003,"name":"Test Relic Gamma","rarity":"Epic","item_type":"Consumable",
 "pvp_source":false,"has_pvp_stats":false,"pvp_penalty":false,"classes":[],
 "armour_weight":null,"equip_location":"None","item_level":null,"requires_level":null,
 "armor":null,"critigation":null,"dps":null,"damage_range":null,
 "stats":[],"spell_effect":[],"set":null,"set_pieces":null,"faction":null,"faction_rank":null,
 "binding":null,"no_longer_available":"fixture: cannot be obtained any more",
 "tooltip_image":null,"tooltip_source_url":null,"sources":[]}]`

type importResult struct {
	rep *items.Report
	err error
}

func runImport(t *testing.T, pool *pgxpool.Pool, body string) importResult {
	t.Helper()
	return runImportWith(t, pool, body, items.Options{})
}

func runImportWith(t *testing.T, pool *pgxpool.Pool, body string, opt items.Options) importResult {
	t.Helper()
	ctx := context.Background()
	its, err := items.DecodeSnapshot(strings.NewReader(body))
	if err != nil {
		t.Fatalf("decoding fixture: %v", err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	l, err := items.LoadLookups(ctx, tx)
	if err != nil {
		t.Fatalf("lookups: %v", err)
	}
	rep, err := items.Import(ctx, tx, its, l, opt)
	if err == nil {
		if cerr := tx.Commit(ctx); cerr != nil {
			t.Fatalf("commit: %v", cerr)
		}
	}
	return importResult{rep: rep, err: err}
}

func TestTheFixtureImportsWithTheCountsItReports(t *testing.T) {
	pool, d := importTarget(t)
	r := runImport(t, pool, fixtureJSON)
	if r.err != nil {
		t.Fatalf("import: %v", r.err)
	}

	// 3 items in, 1 excluded by Pierre's decision -> 2 land.
	for table, want := range map[string]int{
		"items":                2,
		"item_stats":           2, // both on the blade; the ring and relic have none
		"item_spell_effects":   1, // kept apart from stats, deliberately
		"item_sources":         2, // 3 on the blade, 1 of them quarantined
		"item_costs":           2, // one source, two currencies
		"item_classes":         1,
		"item_equip_locations": 4, // blade both slots + ring either slot; relic none
		"sets":                 1,
		"vendors":              1,
	} {
		if got := count(t, d, table); got != want {
			t.Errorf("%s has %d rows, want %d", table, got, want)
		}
		if r.rep.Counts[table] != want {
			t.Errorf("the report claims %s=%d, want %d", table, r.rep.Counts[table], want)
		}
	}

	if len(r.rep.ExcludedItems) != 1 || !strings.Contains(r.rep.ExcludedItems[0], "9003") {
		t.Errorf("excluded items = %v, want the one flagged item", r.rep.ExcludedItems)
	}
	if r.rep.HeldSources != 1 {
		t.Errorf("held sources = %d, want 1", r.rep.HeldSources)
	}
	if len(r.rep.ItemsNoSources) != 1 || r.rep.ItemsNoSources[0] != 9002 {
		t.Errorf("items with no source = %v, want [9002]", r.rep.ItemsNoSources)
	}
}

// The snapshot is regenerated by every data-quality ticket, so this import will be run again.
func TestReRunningTheImportChangesNothing(t *testing.T) {
	pool, d := importTarget(t)
	if r := runImport(t, pool, fixtureJSON); r.err != nil {
		t.Fatalf("first import: %v", r.err)
	}
	first := snapshotCounts(t, pool, d)
	if r := runImport(t, pool, fixtureJSON); r.err != nil {
		t.Fatalf("second import: %v", r.err)
	}
	second := snapshotCounts(t, pool, d)
	for k, v := range first {
		if second[k] != v {
			t.Errorf("%s: %d rows after the first import, %d after the second", k, v, second[k])
		}
	}
}

// The whole point of the pre-flight: a value nobody has decided about stops everything, and
// stops it BEFORE anything is written.
func TestAnUnresolvableValueWritesNothingAtAll(t *testing.T) {
	pool, d := importTarget(t)
	bad := strings.Replace(fixtureJSON, `"rarity":"Epic"`, `"rarity":"Ultra Legendary Plus"`, 1)

	ctx := context.Background()
	its, err := items.DecodeSnapshot(strings.NewReader(bad))
	if err != nil {
		t.Fatalf("decoding: %v", err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	l, err := items.LoadLookups(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	unknown, _ := items.CheckResolvable(its, l)
	// Staleness is not asserted here: this fixture deliberately contains none of the four
	// recorded values, so all four are stale by construction. TestTheDecidedListIsAuditedAgainstTheData
	// is where that behaviour is pinned.
	if len(unknown) != 1 || unknown[0].Value != "Ultra Legendary Plus" {
		t.Fatalf("pre-flight found %v, want only the one unknown rarity", unknown)
	}
	// And nothing was written on the way to finding out.
	if got := count(t, d, "items"); got != 0 {
		t.Errorf("items has %d rows after a refused import, want 0", got)
	}
}

// A decision that no longer matches anything must fail too, or the list rots into an exemption
// nobody rechecks — the AOC-019/AOC-020/AOC-032 shape.
func TestTheDecidedListIsAuditedAgainstTheData(t *testing.T) {
	pool, _ := importTarget(t)
	ctx := context.Background()
	its, _ := items.DecodeSnapshot(strings.NewReader(fixtureJSON))
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	l, _ := items.LoadLookups(ctx, tx)

	_, stale := items.CheckResolvable(its, l)
	// The fixture contains none of the four recorded values, so every one of them is stale here.
	if len(stale) != 4 {
		t.Errorf("got %d stale decisions on a fixture that triggers none of them, want 4: %v",
			len(stale), stale)
	}
	for _, s := range stale {
		if !strings.Contains(s, "decided list") {
			t.Errorf("a stale-decision message does not explain itself: %q", s)
		}
	}
}

// importTarget gives a migrated throwaway database as both a pool (what the importer needs) and
// a *sql.DB (what this package's count() helper needs). Same database, two handles.
func importTarget(t *testing.T) (*pgxpool.Pool, *sql.DB) {
	t.Helper()
	d, url := migratedDB(t)
	pool, err := pgxpool.New(context.Background(), url)
	if err != nil {
		t.Fatalf("pool: %v", err)
	}
	t.Cleanup(pool.Close)
	return pool, d
}

func snapshotCounts(t *testing.T, pool *pgxpool.Pool, d *sql.DB) map[string]int {
	t.Helper()
	_ = pool
	out := map[string]int{}
	for _, table := range []string{"items", "item_stats", "item_spell_effects", "item_sources",
		"item_costs", "item_classes", "item_equip_locations", "sets", "vendors"} {
		out[table] = count(t, d, table)
	}
	return out
}

// ---------------------------------------------------------------------------------------------
// AOC-042 — the corpus floor.
//
// A full replace cannot tell a smaller dataset from a broken one. Before this guard a VALID
// 40-item snapshot deleted 4,646 items, inserted 40 and exited 0. Genuine truncation was never the
// danger — a cut file fails to decode — so every fixture below is well-formed and simply short,
// which is exactly what a `--limit N` smoke test produces.
//
// ⚠️ These assert THE ROW COUNT AFTERWARDS, not the error message. AOC-012's five defects all
// passed tests that checked the half being thought about; an error string proves the function
// returned, not that the corpus is still there.

// minimalItem builds a well-formed item with no stats, sources, set or vendor — the shape of
// fixture 9002 — so a corpus of any size can be built without inventing a game fact. Every name is
// obviously fake (CLAUDE.md STEP ZERO).
func minimalItem(id int) string {
	return fmt.Sprintf(`{"item_id":%d,"name":"Test Filler Item %d","rarity":"Rare","item_type":"Back",
 "pvp_source":false,"has_pvp_stats":false,"pvp_penalty":false,"classes":[],
 "armour_weight":null,"equip_location":"None","item_level":70,"requires_level":70,
 "armor":null,"critigation":null,"dps":null,"damage_range":null,
 "stats":[],"spell_effect":[],"set":null,"set_pieces":null,"faction":null,"faction_rank":null,
 "binding":null,"no_longer_available":false,"tooltip_image":null,"tooltip_source_url":null,
 "sources":[]}`, id, id)
}

// corpusOf builds a snapshot of exactly n importable items.
func corpusOf(n int) string {
	parts := make([]string, 0, n)
	for i := range n {
		parts = append(parts, minimalItem(9100+i))
	}
	return "[" + strings.Join(parts, ",\n") + "]"
}

// ⭐ THE ONE THAT MATTERS. A short but perfectly valid snapshot must not be allowed to replace a
// populated corpus, and the proof is that the corpus is STILL THERE afterwards.
func TestAShortSnapshotCannotReplaceAPopulatedCorpus(t *testing.T) {
	pool, d := importTarget(t)

	if r := runImport(t, pool, corpusOf(100)); r.err != nil {
		t.Fatalf("seeding the corpus: %v", r.err)
	}
	if got := count(t, d, "items"); got != 100 {
		t.Fatalf("setup: items = %d, want 100", got)
	}

	r := runImport(t, pool, corpusOf(40))
	if r.err == nil {
		t.Fatal("a 40-item snapshot replaced a 100-item corpus and reported success")
	}

	// The assertion that actually matters: nothing was deleted.
	if got := count(t, d, "items"); got != 100 {
		t.Errorf("items = %d after a REFUSED import, want the original 100 — the delete ran anyway", got)
	}
	// And the refusal says enough to act on: both numbers and the way out.
	for _, want := range []string{"100", "40", "-allow-shrink"} {
		if !strings.Contains(r.err.Error(), want) {
			t.Errorf("the refusal does not mention %q: %v", want, r.err)
		}
	}
}

// The first import has nothing to protect, and every dev run starts here. An empty table must
// never trip the floor, however small the snapshot.
func TestTheFirstImportIntoAnEmptyDatabaseIsNeverRefused(t *testing.T) {
	pool, d := importTarget(t)

	if got := count(t, d, "items"); got != 0 {
		t.Fatalf("setup: items = %d, want an empty table", got)
	}
	if r := runImport(t, pool, corpusOf(1)); r.err != nil {
		t.Fatalf("a 1-item first import was refused: %v", r.err)
	}
	if got := count(t, d, "items"); got != 1 {
		t.Errorf("items = %d, want 1", got)
	}
}

// The escape hatch has to work, or the guard is a wall rather than a question.
func TestAllowShrinkPermitsTheReplacement(t *testing.T) {
	pool, d := importTarget(t)

	if r := runImport(t, pool, corpusOf(100)); r.err != nil {
		t.Fatalf("seeding the corpus: %v", r.err)
	}
	r := runImportWith(t, pool, corpusOf(40), items.Options{AllowShrink: true})
	if r.err != nil {
		t.Fatalf("-allow-shrink did not permit the import: %v", r.err)
	}
	if got := count(t, d, "items"); got != 40 {
		t.Errorf("items = %d, want 40 — the override did not actually replace the corpus", got)
	}
}

// The boundary, pinned from both sides, because "roughly 90%" is not a specification. At exactly
// the floor the import proceeds; one item below it, it does not.
func TestTheFloorBoundaryIsNotOffByOne(t *testing.T) {
	if items.ShrinkFloorPercent != 90 {
		t.Fatalf("this test is written against a 90%% floor, but the constant is %d",
			items.ShrinkFloorPercent)
	}
	for _, tc := range []struct {
		name           string
		existing, next int
		wantRefused    bool
	}{
		{"exactly at the floor proceeds", 100, 90, false},
		{"one below the floor refuses", 100, 89, true},
		{"growth is never questioned", 100, 400, false},
		{"an unchanged corpus is never questioned", 100, 100, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			pool, d := importTarget(t)
			if r := runImport(t, pool, corpusOf(tc.existing)); r.err != nil {
				t.Fatalf("seeding %d items: %v", tc.existing, r.err)
			}
			r := runImport(t, pool, corpusOf(tc.next))

			if tc.wantRefused {
				if r.err == nil {
					t.Fatalf("%d -> %d was allowed, want refused", tc.existing, tc.next)
				}
				if got := count(t, d, "items"); got != tc.existing {
					t.Errorf("items = %d after a refused import, want %d", got, tc.existing)
				}
				return
			}
			if r.err != nil {
				t.Fatalf("%d -> %d was refused, want allowed: %v", tc.existing, tc.next, r.err)
			}
			if got := count(t, d, "items"); got != tc.next {
				t.Errorf("items = %d, want %d", got, tc.next)
			}
		})
	}
}

// ⚠️ The floor must be reached through Import, not only through the command. A second caller that
// went straight to internal/items would otherwise route around it — the reason the guard does not
// live in cmd/import-armory (CLAUDE.md rule 5b).
func TestTheFloorGuardsImportItselfNotTheCommand(t *testing.T) {
	pool, d := importTarget(t)
	if r := runImport(t, pool, corpusOf(100)); r.err != nil {
		t.Fatalf("seeding the corpus: %v", r.err)
	}

	// Calling items.Import directly, exactly as a future second caller would.
	ctx := context.Background()
	its, err := items.DecodeSnapshot(strings.NewReader(corpusOf(10)))
	if err != nil {
		t.Fatalf("decoding: %v", err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	l, err := items.LoadLookups(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := items.Import(ctx, tx, its, l, items.Options{}); err == nil {
		t.Error("items.Import accepted a 10-item snapshot over a 100-item corpus")
	}
	if got := count(t, d, "items"); got != 100 {
		t.Errorf("items = %d, want the original 100", got)
	}
}
